kadena-community/kadena.js

packages/libs/pactjs-utils/src/PactNumber.ts, packages/libs/pactjs-utils/src/tests/PactNumber.test.ts, packages/libs/pactjs-utils/src/tests/createExp.test.ts, packages/libs/pactjs-utils/tsconfig.json, rush.json
Cleans up code from #51 
- Delete `console.log`s
- Sort package list alphabetically in `rush.json`
- remove node from compiler options in `pactjs-utils` tsconfig.json
=> Minor cleanups

CODEOWNERS
Initial commit.
- [-] I have reviewed my changes and run the appropriate tests.
- [-] I have have run `rush change` to add the appropriate change logs.
- [-] I have added/edited docs.
- [-] I have added tutorials.
- [-] I have double checked and DEFINITELY added docs.
=> io init commit

CODEOWNERS
Resolve Ashwin's conflict
- [-] I have reviewed my changes and run the appropriate tests.
- [-] I have have run `rush change` to add the appropriate change logs.
- [-] I have added/edited docs.
- [-] I have added tutorials.
- [-] I have double checked and DEFINITELY added docs.
=> reverted CODEOWNERS file

common/changes/@kadena/cryptography-utils/feat-crypto-utils-examples_2023-02-13-17-51.json, packages/libs/cryptography-utils/README.md, packages/libs/cryptography-utils/src/hashBin.ts
There were no clear examples on how to use cryptography utils, so I added the simplest, and most commonly used examples.
=> Cryptography Util Examples

common/changes/@kadena/chainwebjs/feat-cleanup_2023-02-02-13-28.json, packages/libs/chainwebjs/README.md
=> Feat/cleanup - Readme for chainwebjs

common/changes/@kadena/client/feat-pact-command-example_2023-02-20-08-21.json, packages/libs/client/README.md, packages/libs/client/etc/client.api.md, packages/libs/client/src/pact.ts
I agree with Pascal on having a lighter weight solution to writing and executing pact code.
So, I've added docs to PactCommand and a usage example to the readme.
This closes out #161 
PactCommand usage documentation.
I've also added documentation to each of the functions in the PactCommand class.
=> PactCommand Class Usage Example

README.md
---
- https://app.asana.com/0/0/1204080173473911
=> Add docs for testing, closes #164

common/changes/@kadena/react-components/feat-stack-component_2023-03-31-07-35.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/libs/react-components/.babelrc.json, packages/libs/react-components/package.json, packages/libs/react-components/src/components/Stack/Stack.stories.tsx, packages/libs/react-components/src/components/Stack/Stack.tsx, packages/libs/react-components/src/index.ts, packages/libs/react-components/src/styles/index.ts, packages/libs/react-components/src/styles/stitches.config.ts
Adding a stack component to the component library
=> feat(kadena/ui): Stack component

common/changes/@kadena/react-components/feat-ui_iconbutton_2023-04-13-19-26.json, packages/libs/react-components/src/components/IconButton/IconButton.stories.tsx, packages/libs/react-components/src/components/IconButton/IconButton.tsx, packages/libs/react-components/src/components/IconButton/index.ts, packages/libs/react-components/src/components/Icons/index.tsx, packages/libs/react-components/src/index.ts
We need a component for a button that is just an icon
Closes [issue link]](https://app.asana.com/0/1204270938438101/1204388315302169/f)
=> [UI] add iconbutton component

common/changes/@kadena/react-components/feat-docs-theming_2023-04-17-09-44.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/apps/kadena-docs/package.json, packages/apps/kadena-docs/src/components/Header/Header.tsx, packages/apps/kadena-docs/src/components/Header/ThemeToggle.tsx, packages/apps/kadena-docs/src/components/Markdoc/Heading/Heading.tsx, packages/apps/kadena-docs/src/pages/_app.tsx, packages/libs/react-components/src/components/IconButton/IconButton.tsx
adding the capability to swith the theme of the docs
=> switch theme

common/changes/@kadena/react-components/fix-icon-size_2023-04-26-10-12.json, packages/libs/react-components/src/components/Icons/styles.ts
=> Bugfix icon (re)sizing

common/changes/@kadena/react-components/feat-new-code-icon_2023-04-26-11-25.json, packages/libs/react-components/src/components/Icons/index.tsx, packages/libs/react-components/src/components/Icons/svgs/Code.tsx
Added the code icon need for the docs
=> Code icon added

CODEOWNERS
=> Extend code owners

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/apps/kadena-docs/next.config.js, packages/apps/kadena-docs/package.json, packages/apps/kadena-docs/src/components/Layout/components/ArticleStyles.ts, packages/apps/kadena-docs/src/components/Layout/components/Aside/AsideStyles.ts, packages/apps/kadena-docs/src/components/Markdown/Paragraph/Paragraph.tsx, packages/apps/kadena-docs/src/data/menu.json, packages/apps/kadena-docs/src/pages/docs/kadena/index.tsx, packages/apps/kadena-docs/src/pages/docs/kadena/kda/index.md, packages/apps/kadena-docs/src/pages/docs/kadena/kda/kda-concepts.md, packages/apps/kadena-docs/src/pages/docs/kadena/kda/manage-kda.md, packages/apps/kadena-docs/src/pages/docs/kadena/overview.md, packages/apps/kadena-docs/src/pages/docs/kadena/wallets/chainweaver/index.md, packages/apps/kadena-docs/src/pages/docs/kadena/wallets/chainweaver/terms-of-service.md, packages/apps/kadena-docs/src/pages/docs/kadena/wallets/chainweaver/troubleshooting.md, packages/apps/kadena-docs/src/pages/docs/kadena/wallets/index.md
This is just adding mock content to the docs
and what is needed.
For this new stories were created
Closes [[issue link]](https://app.asana.com/0/1204526868335507/1204549233614301/f)
=> [docs] copy content

packages/apps/kadena-docs/src/components/Layout/components/Header/Header.tsx, packages/apps/kadena-docs/src/components/Layout/components/Header/SearchButton.tsx, packages/apps/kadena-docs/src/components/Layout/components/Header/styles.ts, packages/apps/kadena-docs/src/hooks/index.ts, packages/apps/kadena-docs/src/hooks/useOpenSearch.ts
This component is just the styling and the functionality of key press '/'
It DOES NOT open the search. that is a followup story
The modal for the search is not designed yet. so that we cant develop yet
Closes https://app.asana.com/0/1202676524474548/1204358202948598/f
=> [docs] Add header search component

packages/apps/transfer/next.config.js, packages/apps/transfer/src/components/Common/Layout/index.tsx, packages/apps/transfer/src/pages/_document.tsx, packages/apps/transfer/src/pages/check-balance/index.tsx
- only allow tsx files to get build in pages directory
- add component return type to layout
- remove unused vars in check balance
=> fix(build): nextjs config

packages/apps/transfer/src/pages/_document.tsx, packages/apps/transfer/src/pages/home/index.tsx
=> [@Kadena/transfer] Remove extra home menu buttons

packages/apps/transfer/src/pages/home/index.tsx, packages/apps/transfer/src/pages/home/styles.ts, packages/apps/transfer/src/services/key-pairs/key-pairs.ts, packages/apps/transfer/src/services/utils/file-download.ts
=> [@kadena/transfer] KeyPair Generator

.github/workflows/ci.yml
Run CI on windows-latest as well, as a preliminary check for #244
=> Add windows-latest to the pipeline

packages/apps/transfer/src/services/transfer/coin-transfer.ts, packages/apps/transfer/src/services/utils/utils.ts
=> [@kadena/transfer] Fix Transfer Amount - implement Pact Number

packages/apps/transfer/src/services/accounts/get-balance.ts, packages/apps/transfer/src/services/accounts/get-public-keys.ts, packages/apps/transfer/src/services/transfer/coin-transfer.ts, packages/apps/transfer/src/services/utils/utils.ts
=> [@kadena/transfer] Support all account types

packages/apps/transfer/.gitignore, packages/apps/transfer/README.md, packages/apps/transfer/tsconfig.json, rush.json
- remove duplicated git ignore paths
- remove duplicated ts configs
- add readme
- enabled rush check
=> fix: improve project setup

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json
The docs site was crashing in dev mode due to packages getting updated in the lock file that shouldn't have been affected. I've gone back to the last working commit, copied that pnpm-lock.yaml, and ran rush update. After doing this, the build worked
=> [@kadena/kadena-docs]: Fixing build

packages/apps/transfer/src/components/Common/Layout/MainLayout.tsx, packages/apps/transfer/src/components/Global/NavLink/index.tsx, packages/apps/transfer/src/components/Global/SidebarMenu/index.tsx, packages/apps/transfer/src/constants/routes.ts, packages/apps/transfer/src/pages/home/index.tsx
- add routes constant
- use route constants for links
=> fix: routes

packages/apps/kadena-docs/src/components/Markdown/index.ts
typescript update screwed up some types
=> [docs] fix type

docs/decisions/0002-supported-environments.md
Would be good to record the environments we support. I found it a bit difficult to scope and word it properly.
For instance, can we keep it concise and simply include supported browsers in this document as well, does that make sense?
So please feel free to comment if something is not clear, or you need more context of something, etc.
=> Add first version of "supported environments" ADR

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/apps/transfer/.eslintrc.js, packages/apps/transfer/jest.config.js, packages/apps/transfer/jest.setup.js, packages/apps/transfer/package.json, packages/apps/transfer/src/components/Common/Layout/MainLayout.spec.tsx, packages/apps/transfer/src/components/Common/Layout/MainLayout.tsx, packages/apps/transfer/src/components/Common/Layout/index.spec.tsx, packages/apps/transfer/src/components/Common/Layout/index.tsx, packages/apps/transfer/src/components/Global/Ace/index.spec.tsx, packages/apps/transfer/src/components/Global/Ace/index.tsx, packages/apps/transfer/src/components/Global/NavLink/index.spec.tsx, packages/apps/transfer/src/components/Global/Select/index.spec.tsx, packages/apps/transfer/src/components/Global/Select/index.tsx, packages/apps/transfer/src/components/Global/SidebarMenu/index.spec.tsx, packages/apps/transfer/src/components/Global/SidebarMenu/index.tsx, packages/apps/transfer/src/pages/index.spec.tsx, packages/apps/transfer/tsconfig.json
- add jest config
- add test for components
- add jest config
- add test for components
=> implement tests

docs/decisions/0001-use-adr.md, docs/decisions/0002-supported-environments.md
=> Update status of ADRs

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json
I got issues with vanilaextract in next
=> [docs] fix the vanilla extract plugin

.github/workflows/ci.yml
Remove `common/temp/build-cache` from cache paths
=> Remove `common/temp/build-cache` from cache paths

packages/libs/react-components/src/styles/colors/index.ts, packages/libs/react-ui/src/styles/themes.css.ts
increased it by 3% to meet a11y in dark mode for other intent colors
=> increased luminance of the negative surface and high contrast color

common/changes/@kadena/client/fix-client-stringified-proof_2023-06-21-15-36.json, packages/libs/client/src/contPact.ts
=> [@kadena/client] Fix stringified issue with proof

packages/tools/kda-cli/src/pact/pact.ts
=> Fix typo signatureValidationt

.github/workflows/ci.yml, .github/workflows/docs-chores.yml
=> Run format:ci only on affected packages

common/changes/@kadena/pactjs-cli/fix-pactjs-cli-readme_2023-06-27-10-05.json, packages/tools/pactjs-cli/README.md
Make the examples in the readme work
=> Correct the READMEs examples

packages/apps/transfer/src/components/Common/Layout/MainLayout.tsx, packages/apps/transfer/src/components/Common/Layout/styles.tsx, packages/apps/transfer/src/constants/kadena.ts, packages/apps/transfer/src/context/app-context.tsx, packages/apps/transfer/src/hooks/index.ts, packages/apps/transfer/src/hooks/use-did-update-effect.ts, packages/apps/transfer/src/pages/transfer/account-transactions/index.tsx, packages/apps/transfer/src/pages/transfer/cross-chain-transfer-finisher/index.tsx, packages/apps/transfer/src/services/cross-chain-transfer-finish/get-transfer-data.ts
- Fixed the Network toggle not being saved.
- Fixed the Transactions page improperly applying query params.
- Removed duplicate connect your wallet.
Fixed with the help of @rezaerami 🎉
=> [@kadena/transfer] Fix Network state and Transactions page

packages/apps/kadena-docs/src/components/Search/ResultCount.tsx, packages/apps/kadena-docs/src/components/Search/SearchResults.tsx, packages/apps/kadena-docs/src/components/Search/StaticResults.tsx, packages/apps/kadena-docs/src/components/Search/styles.ts, packages/apps/kadena-docs/src/components/SearchModal/SearchModal.tsx, packages/apps/kadena-docs/src/hooks/useSearch/utils.ts, packages/apps/kadena-docs/src/pages/search/index.tsx, packages/apps/kadena-docs/src/scripts/createSearchIndex.mjs, packages/libs/react-ui/src/components/Tabs/Tab.tsx
=> feat(docs): style search results

packages/apps/kadena-docs/next.config.mjs, packages/apps/kadena-docs/src/hooks/useSearch/useSearch.ts, packages/apps/kadena-docs/src/scripts/remarkCheckForCodeTitle.mjs
- show a header in markdown code blocks when there is no title
- fix the double search
=> fix(docs): small fixes

packages/apps/transfer/src/pages/transfer/account-transactions/index.tsx, packages/apps/transfer/src/pages/transfer/account-transactions/styles.ts
=> [@kadena/transfer] UI fixes for account transactions page

packages/apps/docs/src/pages/_app.tsx, packages/libs/react-ui/package.json
=> [@kadena/react-ui]: Fix theme export types

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/libs/react-ui/package.json
The build command was using unix commands, changed to support cross platform development.
=> [@kadena/react-ui] Cross platform build support

packages/apps/docs/src/components/BottomPageSection/components/Subscribe.tsx, packages/apps/docs/src/components/Layout/components/ArticleStyles.ts, packages/apps/docs/src/components/Layout/components/SideMenu/styles.ts, packages/libs/react-ui/src/styles/themes.css.ts
- Fixed spacing between left menu and content
- Footer and content
- typo of subscribe message
=> fix(kadena-docs): spacing of full page

CONTRIBUTING.md
=> Add section "workflow" to contrib doc

common/changes/@kadena-dev/eslint-config/fix-eslint-config-external_2023-07-07-07-55.json, common/changes/@kadena-dev/eslint-plugin/fix-eslint-config-external_2023-07-07-07-59.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/libs/react-ui/package.json, packages/tools/eslint-config/package.json, packages/tools/eslint-config/profile/lib.js, packages/tools/eslint-plugin/package.json
* Fix reusability of .prettierrc file finder in eslint config (3862e375)
* Fix dependencies for eslint packages (e8e3a5d5)
=> ESLint config external

packages/libs/react-ui/package.json, packages/libs/react-ui/src/components/Select/Option.tsx, packages/libs/react-ui/src/components/Select/Select.css.ts, packages/libs/react-ui/src/components/Select/Select.stories.tsx, packages/libs/react-ui/src/components/Select/Select.test.tsx, packages/libs/react-ui/src/components/Select/Select.tsx, packages/libs/react-ui/src/components/Select/index.ts, packages/libs/react-ui/src/components/index.ts, packages/libs/react-ui/src/index.ts
- add select component
- add story book
- add unit test
=> implement select component

packages/apps/docs/src/components/LastModifiedDate/LastModifiedDate.tsx
- Closes ["remove the lastmodifed date for now from template"](https://app.asana.com/0/1204958723576385/1204997894846993/f) 
- Commented out the lines that assemble the component, and returning `null` instead
=> [DOCS]Remove the lastmodifed date for now from template

packages/libs/react-ui/src/components/Button/Button.css.ts, packages/libs/react-ui/src/components/Button/Button.stories.tsx, packages/libs/react-ui/src/components/IconButton/IconButton.css.ts, packages/libs/react-ui/src/components/Notification/Notification.css.ts, packages/libs/react-ui/src/components/Notification/NotificationButton.css.ts, packages/libs/react-ui/src/components/Stack/Stack.stories.tsx, packages/libs/react-ui/src/components/Stack/Stack.test.tsx, packages/libs/react-ui/src/components/Table/Table.css.ts, packages/libs/react-ui/src/styles/themes.css.ts
…ttons
- Closes the ["Update color tokens"](https://app.asana.com/0/1204808093245015/1204956494923579/f) Asana ticket
- Added `info`, `disabled`, `border` and `layout` color groupings
- Added `tertiary` and `info` button colors on stories
=> Update color tokens 

common/changes/@kadena/chainweb-stream-client/feat-chainweb-stream-new-heights-event_2023-06-29-13-20.json, packages/libs/chainweb-stream-client/README.md, packages/libs/chainweb-stream-client/etc/chainweb-stream-client.api.md, packages/libs/chainweb-stream-client/src/index.ts, packages/libs/chainweb-stream-client/src/types.ts
See reasons for change in [Server side PR](https://github.com/kadena-io/chainweb-stream-server/pull/5) 
[previous client PR](https://github.com/kadena-community/kadena.js/pull/416)
=>  [@kadena/Chainweb-stream-client] Fix heights event implementation to match backend

packages/libs/react-ui/src/components/MaskedValue/MaskedValue.css.ts
=> [@kadena/react-ui] Added colors to masked value component

packages/apps/docs/src/components/Search/SearchResults.tsx, packages/apps/docs/src/components/SearchModal/SearchModal.tsx, packages/apps/docs/src/hooks/useSearch/useSearch.ts, packages/apps/docs/src/hooks/useSearch/useStream.ts
- Closes the ["add error states in the search for the UI"](https://app.asana.com/0/1204808093245015/1204957766244399/f) Asana ticket
- Added error reporting for the AI-powered searches via `Notification` component
=> [DOCS] Visual errors for search

common/changes/@kadena/chainweb-stream-client/chore-edit-kadena-client-readme_2023-07-14-06-37.json, common/changes/@kadena/client/chore-edit-kadena-client-readme_2023-07-14-06-37.json, packages/libs/chainweb-stream-client/README.md, packages/libs/client/README.md, packages/libs/client/package.json, packages/tools/create-kadena-app/README.md, packages/tools/kda-cli/README.md
Fixed links and tried to improve a few sentences.
=> Edit kadena client readme

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/apps/transfer/package.json, rush.json
Using chainweb-node-client 0.4.1 in the transfer app. this will fix the issue with IPollResponse interface.
=> fix(transfer): use correct version of chainweb-node-client

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/apps/docs/package.json, packages/libs/react-ui/package.json
it seems that the pathaliases were not resolved anymore during the build.
making the whole package break the build
=> chore(reactui): fix the build

packages/apps/transfer/src/pages/transfer/account-transactions/index.tsx, packages/apps/transfer/src/pages/transfer/cross-chain-transfer-finisher/index.tsx, packages/apps/transfer/src/pages/transfer/cross-chain-transfer-tracker/index.tsx, packages/apps/transfer/src/pages/transfer/module-explorer/index.tsx, packages/libs/react-ui/package.json
=> Fix type errors

.github/CODEOWNERS
Adding codeowners for the @kadena/react-ui package
=> Add codeowners for react-ui

common/changes/@kadena/client/chore-fix-client-dep_2023-07-18-08-10.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/libs/client/package.json
It's used in package.json#scripts
=> Add @kadena/pactjs-cli to @kadena/client devDeps

packages/apps/transfer/src/components/Common/Layout/index.tsx, packages/apps/transfer/src/components/Common/Layout/styles.css.ts
Empty boxes for now, since they will be filled with components the others are making.
=> [@kadena/transfer] Grid System

packages/apps/transfer/src/components/Common/Layout/MainLayout.tsx, packages/apps/transfer/src/pages/home/index.tsx
- remove logo from layout
- remove extra props from grid which has been removed from grid itwself
=> fix layout and grid

common/changes/@kadena/client/fix-client_2023-07-20-09-07.json, packages/libs/client/etc/client.api.md, packages/libs/client/src/client/client.ts, packages/libs/client/src/commandBuilder/tests/commandBuilder.test.ts, packages/libs/client/src/composePactCommand/test/composePactCommand.test.ts, packages/libs/client/src/composePactCommand/utils/addData.ts, packages/libs/client/src/composePactCommand/utils/payload.ts, packages/libs/client/src/composePactCommand/utils/tests/addData.test.ts, packages/libs/client/src/interfaces/IPactCommand.ts
=> fix(client): addKeyset

packages/apps/transfer/src/components/Common/Layout/styles.css.ts, packages/apps/transfer/src/pages/faucet/existing/index.tsx, packages/apps/transfer/src/pages/home/index.tsx, packages/apps/transfer/src/pages/home/styles.ts, packages/apps/transfer/src/pages/transfer/account-transactions/index.tsx, packages/apps/transfer/src/pages/transfer/cross-chain-transfer-finisher/index.tsx, packages/apps/transfer/src/pages/transfer/cross-chain-transfer-tracker/index.tsx, packages/apps/transfer/src/pages/transfer/module-explorer/index.tsx
- remove main layout from pages
- add breadcrumb to pages
- add padding to main layout chuildren
=> add breadcrumb

packages/libs/react-ui/src/components/Footer/FooterLinkItem.tsx
=> [@react-ui] Footer fix: remove a tag from footer link

common/changes/@kadena/client/main_2023-07-20-14-57.json, packages/libs/client/src/tests/pact.test.ts, packages/libs/client/src/utils/parseAsPactValue.ts, packages/libs/client/src/utils/tests/parseAsPactValue.test.ts
=> fix(client): time iso format

packages/apps/docs/.gitignore
Found this by accident while working on build caching
=> Fix casing in gitignore

common/changes/@kadena/client/fix-client-readme-links_2023-07-25-10-29.json, packages/libs/client/README.md
Fix a few links in the client readme
=> Fix links in client readme (closes #589)

packages/apps/docs/src/components/Layout/Full/components/Aside/AsideStyles.ts, packages/apps/docs/src/components/Layout/Redocly/styles.ts, packages/apps/docs/src/components/Layout/components/Header/Header.tsx, packages/apps/docs/src/components/Layout/components/Template/Template.tsx, packages/apps/docs/src/components/Layout/components/styles.ts, packages/apps/docs/src/hooks/index.ts, packages/apps/docs/src/hooks/useMenu/MenuProvider.tsx, packages/apps/docs/src/hooks/useMenu/index.ts, packages/apps/docs/src/hooks/useMenu/types.d.ts, packages/apps/docs/src/hooks/useMenu/useMenu.tsx, packages/apps/docs/src/pages/_app.tsx
the animation wasnt running any more.
=> chore(docs): fix menuheader bug

packages/apps/docs/src/components/Blog/FormatDate.tsx, packages/apps/docs/src/components/Blog/index.ts, packages/apps/docs/src/components/Layout/Blog/Blog.tsx, packages/apps/docs/src/utils/dates.ts
needed for blog:
- posts
- blog overview
- author overview page
=> chore(docs): create formatDate component

packages/libs/react-ui/src/index.ts
=> add missing export for accordion

packages/apps/transfer/src/components/Common/Layout/index.tsx, packages/apps/transfer/src/components/Common/Layout/partials/Footer/Footer.tsx, packages/apps/transfer/src/components/Global/OptionsModal/OptionsModal.tsx, packages/apps/transfer/src/pages/_app.tsx, packages/apps/transfer/src/pages/_document.tsx, packages/libs/react-ui/src/components/Footer/Footer.css.ts
- Applied the new colour scheme and fixed minor styling issues
- Removed legacy react-components
=> Footer fixes in transfer and react-ui

packages/libs/react-ui/src/components/index.ts, packages/libs/react-ui/src/index.ts
=> [@react-ui] Fix: Add ProgressBar missing imports

packages/apps/transfer/src/components/Common/Layout/index.tsx, packages/apps/transfer/src/components/Common/Layout/partials/Header/Header.tsx, packages/apps/transfer/src/components/Common/Layout/partials/Header/styles.css.ts, packages/apps/transfer/src/components/Common/Layout/partials/Header/styles.ts, packages/apps/transfer/src/components/Common/Layout/partials/Sidebar/index.tsx, packages/apps/transfer/src/components/Common/Layout/partials/Sidebar/styles.css.ts, packages/apps/transfer/src/components/Common/Layout/styles.css.ts, packages/apps/transfer/src/components/Global/WalletConnectButton/index.tsx
- use vanilla extract for header to sync with theme
- fix colors of sidebar and toolbar
- force sidebar to get dark theme
- change width of content when menu is expanded
=> fix layout

packages/libs/react-ui/src/components/Tooltip/Tooltip.css.ts, packages/libs/react-ui/src/components/Tooltip/tooltipHandler.ts
- use position fixed for tooltip since its position is calculated based on screen position of related element
=> fix tooltip

packages/apps/docs/src/components/Layout/components/Header/Header.tsx, packages/apps/docs/src/components/Layout/components/Header/styles.ts, packages/apps/docs/src/components/Layout/components/Header/useHeaderAnimation.tsx, packages/apps/docs/src/components/Layout/components/styles.ts, packages/apps/docs/src/pages/docs/blogchain/2018/the-evm-is-fundamentally-unsafe-2018-02-07.mdx, packages/apps/docs/src/pages/docs/blogchain/2018/why-we-open-sourced-our-blockchains-smart-contract-language-2018-05-04.mdx
the horzintal scrollbar was caused by to many options in the header.
Discussed with Isa. And while waiting on a permanent solution from design.
We have a responsive fontsize of the header items
=> fix(docs) fix the horizontal scrollbar by fixing the header

packages/apps/tools/locales/en/common.json, packages/apps/tools/src/components/Common/DrawerToolbar/index.tsx, packages/apps/tools/src/components/Common/DrawerToolbar/styles.css.ts, packages/apps/tools/src/components/Common/Layout/index.tsx, packages/apps/tools/src/components/Common/Layout/styles.css.ts, packages/apps/tools/src/components/Global/ResourceLinks/index.tsx, packages/apps/tools/src/components/Global/ResourceLinks/styles.css.ts, packages/apps/tools/src/pages/home/HelpCenter.tsx, packages/apps/tools/src/pages/home/index.tsx, packages/apps/tools/src/pages/home/styles.css.ts
- add drawer component
- add resource link component
- use drawer and resource link component in home
=> implement drawer

packages/apps/docs/src/scripts/importReadme.mjs
=> Remove create-kadena-app from docs readme importer

packages/libs/react-ui/package.json, packages/libs/react-ui/src/components/NavFooter/Footer.tsx, packages/libs/react-ui/src/components/Table/Table.css.ts, packages/libs/react-ui/src/components/Table/Table.stories.tsx, packages/libs/react-ui/src/components/Table/Table.tsx
- Added Striped option
- Minor styling and colour fixes
=> [@kadena/react-ui] Table Component: Striped option and styling fixes

.github/CODEOWNERS
Discussed with Steven to update codeowners so that PRs are not blocked while he is away
=> chore: Update Docs and react-ui codeowners

packages/tools/kda-cli/src/questions/init.ts
This PR tweaks the initial question for kda cli to tell users how to select an option
=> clarify initial message for kda/cli

packages/libs/react-ui/src/components/Input/Input.css.ts
=> [@kadena/react-ui] Fix input background and border colours

common/changes/@kadena/client/fix-docs-types_2023-08-03-18-22.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/apps/docs/package.json, packages/apps/docs/src/pages/api/subscribe.ts, packages/apps/docs/src/utils/staticGeneration/docs.d.ts, packages/apps/docs/tsconfig.json, packages/libs/client/README.md, packages/libs/react-components/package.json, packages/libs/react-ui/src/components/ContentHeader/ContentHeader.css.ts, packages/libs/react-ui/src/components/ContentHeader/ContentHeader.stories.tsx, packages/libs/react-ui/src/components/ContentHeader/ContentHeader.tsx, packages/tools/remark-plugins/package.json
Not sure why it was breaking on my machine and why it only builds in Node.js v16.
Either way, these changes are good to merge:
* Update changelog (3e7cc7d2)
* Apply formatting (1826b07a)
* Update lockfile (ee22c535)
* Simplify TS config (98b9bfc3)
* Fix types for mailchimp (3e21f4d7)
* Remove odd `d.ts` file (75d1f219)
This error I see often, I have no clue (dependencies were built, `node_modules` are there, all looks fine):
=> Fix some types/config in docs package

.github/workflows/ci.yml, common/config/rush/command-line.json, packages/libs/react-ui/src/components/ContentHeader/ContentHeader.tsx, rush.json
- upgrade `rush` 5.93.1 to 5.100.2 
- upgrade `pnpm` 6.7.1 to 8.6.11
- change `rush format` `rush format:ci` `rush markdown` and `rush lint` to have
- `"enableParallelism": true`
- `"ignoreDependencyOrder": true`
- `"incremental": true`
- adds custom `build` and `rebuild` to allow warnings in successful build 🎉
=> chore(rush): upgrade rush 5.93.1 to 5.100.2 AND pnpm 6.7.1 to 8.6.11

packages/apps/docs/src/components/Markdown/Youtube/Youtube.tsx, packages/apps/docs/src/components/Markdown/Youtube/styles.css.ts, packages/apps/docs/src/components/Markdown/Youtube/styles.ts
Code refactor from stitches into vanilla-extract for the `<Youtube>` markdown components
---
- https://app.asana.com/0/0/1205194857763856
=> [docs] Refactor Markdown/Youtube

packages/apps/docs/src/components/Search/Search.tsx, packages/apps/docs/src/utils/analytics.ts
- Added `search:qa` and `search:docs` to google-analytics events
---
- https://app.asana.com/0/0/1205091936807444
=> [docs] Search: add google events to new searches

packages/libs/react-ui/src/components/InputWrapper/InputHeader/InputHeader.css.ts, packages/libs/react-ui/src/components/InputWrapper/InputHeader/InputHeader.tsx, packages/libs/react-ui/src/components/Tag/Tag.css.ts, packages/libs/react-ui/src/components/Tag/Tag.stories.tsx, packages/libs/react-ui/src/components/Tag/Tag.tsx, packages/libs/react-ui/src/styles/sprinkles.css.ts, packages/libs/react-ui/src/styles/vars.css.ts
Updated the tag component to match latest styles + accept an `onClose` handler
Moved the original tag styles to the `InputWrapper` component where it is used
=> feat(@kadena/react-ui): Update Tag component

packages/libs/react-ui/src/components/Box/Box.tsx, packages/libs/react-ui/src/components/Stack/Stack.tsx
Renamed component prop to as (which determines the element that is rendered) on Box and Stack to be more consistent to what we are used when using css-in-js solutions
=> chore(@kadena/react-ui): Updated Box and Stack component api 

packages/libs/react-ui/src/components/Card/Card.css.ts
- Fixed the stack styles (removing margin between)
- Removed content layout styling so the user can determine the structure of the content
=> fix(@kadena/react-ui): Fix Card styles

common/config/rush/command-line.json
=> chore(monorepo): allow allowWarningsInSuccessfulBuild for all commands

packages/apps/docs/src/components/Layout/Blog/Blog.tsx, packages/apps/docs/src/components/Layout/Full/Full.tsx, packages/apps/docs/src/components/Layout/Landing/Landing.tsx, packages/apps/docs/src/components/Layout/Redocly/Redocly.tsx, packages/apps/docs/src/components/Layout/components/articleStyles.css.ts, packages/apps/docs/src/components/Layout/components/index.ts, packages/apps/docs/src/components/SearchModal/SearchModal.tsx, packages/apps/docs/src/components/SearchModal/styles.css.ts, packages/apps/docs/src/components/SearchModal/styles.ts, packages/apps/docs/src/pages/docs/blogchain/index.tsx, packages/apps/docs/src/pages/index.tsx, packages/apps/docs/src/pages/search/index.tsx
This PR migrates `Article` and `SearchModal` component to use vanilla extract
=> refactor(docs): migrate article + search modal component 

packages/apps/docs/src/pages/docs/kadena/wallets/index.mdx, packages/apps/docs/src/pages/docs/kadena/wallets/ledger/index.mdx
Closes: https://app.asana.com/0/1205163122576860/1205241601207510/f
=> feat(docs): add ledger user guide

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/apps/docs/next.config.mjs, packages/apps/docs/package.json, packages/apps/docs/src/components/Markdown/Tweet/Tweet.tsx, packages/apps/docs/src/components/Markdown/Tweet/index.ts, packages/apps/docs/src/components/Markdown/index.ts, packages/apps/docs/src/scripts/remarkTwitter.mjs
Closes on - https://app.asana.com/0/1205163122576860/1205116314578308/f
=> feat(embed-tweets): implement tweets component for embed tweets in blog

packages/apps/docs/src/components/Layout/components/articleStyles.css.ts
When migrating the articles styles, added the wrong value. updating it in this PR
=> fix(docs): ui fix for article component

CONTRIBUTING.md, docs/filters.md, docs/pnpm-turbo-filter.md
The `--filter` argument can be confusing, this doc tries to clarify a bit. Still, the docs of pnpm and Turborepo are leading!
=> Shed some light on pnpm + turbo --filters

packages/apps/tools/src/pages/faucet/existing/index.tsx
The Faucet contract has been redeployed (except on chain 1 due to a key signing issue), so now it's time to update this amount accordingly.
=> Update amount to 100 since contracts are deployed

.changeset/metal-buses-explode.md, packages/apps/docs/src/components/Markdown/Tweet/Tweet.tsx, packages/apps/docs/src/components/Markdown/Tweet/styles.css.ts, packages/apps/docs/src/pages/docs/blogchain/2018/consensus2018-5-lessons-from-your-first-crypto-conference-day-1-2018-04-15.md, packages/apps/docs/src/pages/docs/blogchain/2018/pact-formal-verification-for-blockchain-smart-contracts-done-right-2018-05-11.md, packages/apps/docs/src/pages/docs/blogchain/2021/how-to-scale-a-proof-of-work-blockchain-2021-03-07.md, packages/apps/docs/src/pages/docs/blogchain/2021/introducing-the-kadena-live-roadmap-2021-07-30.md, packages/apps/docs/src/pages/docs/blogchain/2021/kadena-roadmap-for-q1-2021-2021-01-14.md, packages/apps/docs/src/pages/docs/blogchain/2021/kadena-roadmap-for-q2-2021-04-05.md, packages/apps/docs/src/pages/docs/blogchain/2021/kadena-telegram-ama-with-stuart-popejoy-2021-02-05.md, packages/apps/docs/src/pages/docs/blogchain/2021/kadena-telegram-ama-with-tehmoonwalker-transcript-2021-05-29.md, packages/apps/docs/src/pages/docs/blogchain/2022/4-ways-kadena-is-taking-blockchain-mainstream-2022-04-22.md, packages/apps/docs/src/pages/docs/blogchain/2022/kadena-2022-year-in-review-2022-12-22.md, packages/apps/docs/src/pages/docs/blogchain/2022/kadena-eco-core-telegram-ama-transcript-2022-08-12.md, packages/apps/docs/src/pages/docs/blogchain/2022/kadena-eco-office-hours-transcript-2022-07-22.md, packages/apps/docs/src/pages/docs/blogchain/2022/kadena-eco-supercharges-kadena-ecosystem-2022-04-02.md, packages/apps/docs/src/pages/docs/blogchain/2022/kadena-telegram-ama-with-binance-exchange-2022-05-03.md, packages/apps/docs/src/pages/docs/blogchain/2023/chainweaver-2-2-3-improving-user-experience-with-quicksign-support-2023-02-10.md, packages/apps/docs/src/pages/docs/blogchain/2023/kadena-2023-q1-newsletter-2023-04-05.md, packages/apps/docs/src/pages/docs/blogchain/2023/kadena-2023-q2-newsletter-2023-07-06.md, packages/apps/docs/src/pages/docs/blogchain/2023/pact-core-concepts-part-ii-learn-pact-in-20-minutes-2023-04-27.md, packages/apps/docs/src/scripts/remarkTwitter.mjs
closes 
https://app.asana.com/0/1205288273408141/1205310320676409/f
https://app.asana.com/0/1205288273408141/1205310320676405/f
=> feat(docs): update tweet links to embed posts

.changeset/selfish-cobras-march.md, packages/apps/graph-client/package.json, packages/libs/chainweb-node-client/package.json, packages/libs/chainwebjs/package.json
99.9% we run `pnpm install` we don't need any of this :)
=> Remove pre/postinstall scripts

packages/apps/tools/src/pages/transactions/module-explorer/index.tsx
=> Module Explorer Page was accidentally deleted

.github/workflows/ci.yml, .github/workflows/release.yml
- Automated workflow for versioning + publishing
- GitHub and npm tokens created and added as secrets (also see comments for access granted)
- Also see https://github.com/changesets/changesets/blob/main/docs/automating-changesets.md
- For now just echo-ing the result to console (last step); could be bot(s) to send notification to Slack/Discord, anything
- We may need to give the `github-actions[bot]` user permission to push to the protected `main` branch
=> Prepare release workflow (fully automated w/ all tokens set up)

.changeset/little-ducks-stare.md, .changeset/nine-paws-marry.md, packages/tools/eslint-config/README.md, packages/tools/eslint-plugin/README.md, pnpm-lock.yaml
* Update changelog (fe2ff4aa3)
* Add minimal README.md file (7ca5ee069)
=> ESLint config plugin changelog docs

.changeset/beige-countries-pump.md, packages/apps/tools/src/pages/transactions/cross-chain-transfer-tracker/index.tsx, packages/libs/react-ui/src/components/Button/Button.css.ts, packages/libs/react-ui/src/components/Button/Button.stories.tsx, packages/libs/react-ui/src/components/Button/Button.tsx, packages/libs/react-ui/src/components/Divider/stories.css.ts, packages/libs/react-ui/src/components/InputWrapper/InputHelper/InputHelper.css.ts, packages/libs/react-ui/src/components/InputWrapper/InputWrapper.css.ts, packages/libs/react-ui/src/components/Link/Link.css.ts, packages/libs/react-ui/src/components/Notification/Notification.css.ts, packages/libs/react-ui/src/components/Pagination/Pagination.css.ts, packages/libs/react-ui/src/components/Tabs/Tabs.css.ts, packages/libs/react-ui/src/components/TrackerCard/TrackerCard.css.ts, packages/libs/react-ui/src/styles/colors.ts, packages/libs/react-ui/src/styles/vars.css.ts
This PR implements new button variants (i.e. `alternative` and `compact`) and fixes the colours and style of the existing button.
**List of changes**
- Fixed previous implementation
- Added new inverted colour tokens
- Updated existing colour tokens
- Updated variable css naming to be more descriptive
- Removed info and tertiary as color variants
- Introduced the new button variants and made the original one the `default`
- Updated the button story and its controls
_Updates to colour tokens etc were made in collaboration with Isa._
[Asana Link](https://app.asana.com/0/1205163122576860/1204873953410513/f)
=> Fix Button styles, tokens and variants

.changeset/large-humans-lay.md, packages/apps/docs/src/components/Blog/BlogItem/BlogItem.tsx, packages/apps/docs/src/components/Blog/BlogItem/styles.css.ts, packages/apps/docs/src/pages/docs/blogchain/index.tsx, packages/apps/docs/src/utils/getMostPopularPages.ts, packages/apps/docs/src/utils/index.ts, packages/apps/docs/src/utils/mostProductiveAuthors.ts
---
- https://app.asana.com/0/0/1205463431122625
=> [DOCS] feat: add extra info to the blogpost landing page

.github/workflows/integration-tests.yml
This PR fixes the integration test workflow to correctly use turbo instead of bypass it.
=> fix: workflow to correctly use turbo instead of bypass it.

.changeset/hip-wasps-compare.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/01-getting-started.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/02-running-devnet.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/03-admin-account.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/04-namespaces.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/05-keysets.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/06-smart-contract.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/07-nominate-candidates.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/08-voting.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/09-gas-station.md
This PR includes branch switching instructions to get the correct starter code for each chapter of the election dapp tutorial.
=> feat(docs): add branch switching instructions to election dapp tutorial

.changeset/brave-beers-repeat.md, packages/libs/pactjs-generator/src/contract/parsing/pactParser.ts, packages/libs/pactjs-generator/src/contract/parsing/tests/pactParser.test.ts
use parent module namespace if the module does not have a namespace
=> use parent module namespace if the module does not have a namespace

.changeset/stale-olives-act.md, packages/apps/docs/src/components/Markdown/Figure/Figure.tsx, packages/apps/docs/src/components/Markdown/Figure/styles.css.ts, packages/apps/docs/src/pages/kadena/overview.md
fixed figure element spacing issues on breakpoints
=> fixed figure element spacing issues on breakpoints

.changeset/chilly-elephants-look.md, packages/apps/graph-client/src/components/compact-transactions-table/compact-transactions-table.tsx, packages/apps/graph-client/src/components/compact-transfers-table/compact-transfers-table.tsx
---
- https://app.asana.com/0/0/1205739917747948
=> [@kadena/graph-client] Fixed the chain parameter and title attributes

.changeset/honest-eggs-lick.md, packages/apps/graph/README.md, packages/apps/graph/package.json
---
- https://app.asana.com/0/0/1205727279463857
=> [@kadena/graph] README file updated

.changeset/afraid-geese-mix.md, packages/apps/graph-client/src/pages/index.tsx
- https://app.asana.com/0/1205553603119741/1205755088427583/f
- https://app.asana.com/0/1205553603119741/1205739032590541/f
=> [@kadena/graph-client] Prefill module field and add labels

.changeset/chilly-bees-leave.md, packages/apps/graph-client/src/components/compact-transactions-table/compact-transactions-table.tsx, packages/apps/graph-client/src/components/compact-transfers-table/compact-transfers-table.tsx, packages/apps/graph-client/src/components/extended-transactions-table/extended-transactions-table.tsx, packages/apps/graph-client/src/constants/routes.ts, packages/apps/graph-client/src/graphql/queries.graph.ts, packages/apps/graph-client/src/graphql/subscriptions.graph.ts, packages/apps/graph-client/src/pages/account/transactions/[module]/[account].tsx, packages/apps/graph-client/src/pages/account/transfers/[module]/[account].tsx, packages/apps/graph-client/src/pages/block/overview/[hash].tsx, packages/apps/graph-client/src/pages/block/transactions/[hash].tsx, packages/apps/graph-client/src/pages/event/[key].tsx, packages/apps/graph-client/src/pages/index.tsx, packages/apps/graph-client/src/pages/transactions/[key].tsx, packages/apps/graph-client/src/pages/transactions/index.tsx, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/Query/transactions.ts, packages/apps/graph/src/scripts/devnet/transfer.ts
- Implemented recent transactions in the block overview page
- Implemented the `/transactions` page which shows the most recent transactions
- Adapted `graph` transactions query to make all parameters not required and dynamically add them if present
- Created `extended-transactions-table` and replaced multiple pages code with reusable component
- Fixed broken links in the transaction page (it was using block ID instead of block hash)
=> [@kadena/graph-client][@kadena/graph] Show recent and all transactions (Feature)

.changeset/unlucky-flies-rush.md, packages/apps/graph-client/src/pages/index.tsx
---
- https://app.asana.com/0/0/1205739032590546
=> [@kadena/graph-client] Implement dynamic select based on input (Feature)

.changeset/six-avocados-smoke.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/prisma/schema.prisma, packages/apps/graph/src/graph/objects/Transaction.ts, packages/apps/graph/src/graph/objects/Transfer.ts
- Added relation between tx and transfer
- Adapted graph object in accordance
- Edited the code column to display `cont` when null
---
- https://app.asana.com/0/0/1205739032590562
=> [@kadena/graph] Create relationship between transaction and transfer (Feature)

.changeset/cyan-poets-love.md, package.json, packages/libs/bootstrap-lib/package.json, packages/libs/chainweb-node-client/package.json, packages/libs/chainweb-node-client/src/spv.ts, packages/libs/chainweb-node-client/src/tests/listen.test.ts, packages/libs/chainweb-node-client/src/tests/local.test.ts, packages/libs/chainweb-node-client/src/tests/mockdata/execCommand.ts, packages/libs/chainweb-node-client/src/tests/poll.test.ts, packages/libs/chainwebjs/package.json, packages/libs/chainwebjs/src/internal.ts, pnpm-lock.yaml
* Clean up, share and remove some unused exports (3d63b8ffc)
* Remove some unused dependencies (28911174e)
* Update knip (44b941fec)
=> More housekeeping

.changeset/forty-turkeys-doubt.md, .changeset/tiny-starfishes-mix.md, packages/apps/graph-client/src/graphql/fields/signer.graph.ts, packages/apps/graph-client/src/graphql/queries.graph.ts, packages/apps/graph-client/src/graphql/subscriptions.graph.ts, packages/apps/graph-client/src/pages/transactions/[key].tsx, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/index.ts, packages/apps/graph/src/graph/objects/Signer.ts, packages/apps/graph/src/graph/objects/Transaction.ts
Implemented Signer in `graph`. Made the necessary adjustments to show signers in Transaction page.
---
- https://app.asana.com/0/0/1205801400947195
=> [@kadena/graph], [@kadena/graph-client] Implement Signer and show info in transaction page (Feat)

packages/apps/tools/src/components/Common/Layout/partials/Header/Header.tsx, packages/apps/tools/src/constants/kadena.ts, packages/apps/tools/src/context/connect-wallet-context.tsx
---
- https://app.asana.com/0/0/1205775181752843
=> Temporarily disable network selector

.changeset/cyan-elephants-fly.md, packages/libs/client-examples/src/client-utils/get-balance.ts, packages/libs/client-utils/README.md, packages/libs/client-utils/etc/client-utils-coin.api.md, packages/libs/client-utils/etc/client-utils-core.api.md, packages/libs/client-utils/src/coin/details.ts, packages/libs/client-utils/src/coin/get-balance.ts, packages/libs/client-utils/src/core/client-helpers.ts, packages/libs/client-utils/src/core/cross-chain.ts, packages/libs/client-utils/src/core/test/cross-chain-client.test.ts, packages/libs/client-utils/src/core/test/preflight-client.test.ts, packages/libs/client-utils/src/core/test/read-dirty.test.ts, packages/libs/client-utils/src/core/test/submit-client.test.ts, packages/libs/client-utils/src/core/utils/helpers.ts, packages/libs/client-utils/src/core/utils/test/helpers.test.ts, packages/libs/client-utils/src/core/utils/test/withEmitter.test.ts
* Adding more unit tests for client utils
* Fix the import ramda issue
=> Test client utils + Fixed ramda import issue

.github/CODEOWNERS
=> chore: Update react-ui codeowners

.changeset/tall-dancers-pay.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/04-namespaces.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/05-keysets.md
=> chore(docs): fix errors in election dapp tutorial

.github/workflows/manual-release.yml
Add workflow to manually publish everything.
=> [chore] add workflow to support manual publishing.

.github/workflows/manual-release.yml
=> [chore] Rename workflow

.changeset/smart-feet-dance.md, packages/libs/client/src/signing/eckoWallet/eckoTypes.ts, packages/libs/client/src/signing/eckoWallet/quicksignWithEckoWallet.ts, packages/libs/client/vitest.config.ts
update createEckoWalletQuicksign to support both "responses" and "quickSignData"
=> fix(client): createEckoWalletQuicksign

packages/libs/react-ui/src/components/Accordion/Accordion.css.ts
=> [@react-ui] Accordion: update toggle icon rotation

packages/apps/tools/src/components/Global/AccountNameField/index.tsx, packages/apps/tools/src/pages/faucet/existing/index.tsx, packages/apps/tools/src/pages/faucet/new/index.tsx
=> [@tools-website] Remove K icon in account name input

.changeset/tidy-coats-raise.md, docs/kadena-docs-style-guide.md
This is the first version of the documentation style guide for writers contributing to Kadena documentation.
The main goal of the style guide is to help anyone interested in contributing to documentation write material that is clear, concise, and consistent.
The style guide will also be available in a Notion teamspace.
https://www.notion.so/kadenateam/Documentation-resources-and-tools-efa69c0c21eb43aa97a6e387625c1796
=> [docs] First draft of Kadena documentation style guide

.changeset/little-eyes-drop.md, packages/apps/graph/cwd-extra-migrations/2.3.0.3_add_view_for_nfts.sql, packages/apps/graph/prisma/schema.prisma
=> [@kadena/graph] Reconcile View

.changeset/wet-dogs-switch.md, packages/apps/graph/.env.example, packages/apps/graph/README.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/package.json, packages/apps/graph/src/graph/Query/blocksFromHeight.ts, packages/apps/graph/src/graph/Query/completedBlockHeights.ts, packages/apps/graph/src/graph/Query/graphConfiguration.ts, packages/apps/graph/src/graph/builder.ts, packages/apps/graph/src/graph/objects/Block.ts, packages/apps/graph/src/services/tracing/trace-analyser.ts, packages/apps/graph/src/services/tracing/trace-service.ts, packages/apps/graph/src/utils/dotenv.ts, pnpm-lock.yaml
=> [@kadena/graph] Tracing and Analysing

.changeset/chilly-goats-exist.md, packages/apps/graph/prisma/schema.prisma
=> [@kadena/graph] Improved naming convention of Reconcile object

.github/CODEOWNERS
=> chore: edit client-utills code owners

packages/apps/tools/src/components/Common/Layout/partials/Header/Header.tsx, packages/apps/tools/src/components/Global/AddNetworkModal/AddNetworkModal.tsx, packages/apps/tools/src/components/Global/AddNetworkModal/styles.css.ts, packages/apps/tools/src/pages/faucet/existing/index.tsx, packages/apps/tools/src/pages/faucet/new/index.tsx, packages/apps/tools/src/services/faucet/create-principal.ts, packages/apps/tools/src/services/faucet/fund-create-new.ts, packages/apps/tools/src/services/faucet/index.ts, packages/apps/tools/src/utils/network.ts
---
- https://app.asana.com/0/0/1205768631720675
=> Feature/tools dapp/custom network

packages/tools/kadena-cli/src/devnet/commands/devnetDelete.ts, packages/tools/kadena-cli/src/devnet/utils/devnetHelpers.ts, packages/tools/kadena-cli/src/devnet/utils/docker.ts
=> fix(kadena-cli): improve error message in delete devnet command

.changeset/hip-rockets-knock.md, packages/apps/docs/src/pages/build/quickstart/index.md, packages/apps/docs/src/scripts/detectBrokenLinks.mjs, packages/apps/docs/src/scripts/importReadme/createDoc.mjs
bugfix: fix the buildscripts remove extra frontmatter and do not check on
=> [DOCS] fix: the buildscripts remove extra frontmatter and do not check on

.changeset/two-coins-hammer.md, packages/apps/graph/README.md, packages/apps/graph/src/devnet/simulation/file.ts, packages/apps/graph/src/devnet/simulation/simulate.ts
To diversify the initial testing sample, we cycle through all transfer types for the first funding transfers.
Subsequent transfers will be of the 'transfer' type to simulate normal operations.
---
- https://app.asana.com/0/0/1206142839462239
=> [@kadena/graph] Different funding transaction types on simulation (Feat)

.changeset/serious-scissors-travel.md, packages/libs/client-utils/src/nodejs/test/yaml-converter.test.ts, packages/libs/client-utils/src/nodejs/yaml-converter.ts
=> [@kadena/client-utils] Remove extra data field on IPactCommand (Fix)

packages/libs/hd-wallet/src/chainweaver/compatibility/encryption.ts, packages/libs/hd-wallet/src/chainweaver/compatibility/index.ts, packages/libs/hd-wallet/src/chainweaver/compatibility/kadenaChangePassword.ts, packages/libs/hd-wallet/src/chainweaver/compatibility/kadenaGenKeypair.ts, packages/libs/hd-wallet/src/chainweaver/compatibility/kadenaGetPublic.ts, packages/libs/hd-wallet/src/chainweaver/compatibility/kadenaGetPublicFromRootKey.ts, packages/libs/hd-wallet/src/chainweaver/compatibility/kadenaMnemonicToRootKeypair.ts, packages/libs/hd-wallet/src/chainweaver/compatibility/kadenaSign.ts, packages/libs/hd-wallet/src/chainweaver/compatibility/kadenaSignFromRootKey.ts, packages/libs/hd-wallet/src/chainweaver/index.ts, packages/libs/hd-wallet/src/chainweaver/kadena-crypto.ts, packages/libs/hd-wallet/src/chainweaver/tests/chainweaver.test.ts
=> feat: updated hd-wallet legacy methods to apply encryption

packages/apps/tools/src/services/utils/utils.ts
---
- https://app.asana.com/0/0/1206091721942276
=> Also allow WEBAUTHN- public keys

packages/apps/tools/locales/en/common.json, packages/apps/tools/src/components/Global/FormItemCard/FormItemCard.tsx, packages/apps/tools/src/components/Global/FormItemCard/styles.css.ts, packages/apps/tools/src/pages/transactions/cross-chain-transfer-tracker/styles.css.ts, packages/apps/tools/src/services/transfer-tracker/get-transfer-status.ts
=> [@tools-website] Transfer Tracker page

.changeset/wet-pugs-change.md, packages/apps/graph/src/devnet/crosschain-transfer.ts, packages/apps/graph/src/devnet/simulation/index.ts, packages/apps/graph/src/devnet/simulation/simulate.ts, packages/apps/graph/src/devnet/transfer.ts
=> [@kadena/graph] Fix minor issues regarding signing and balance checking

.changeset/eighty-hairs-yell.md, packages/libs/client-examples/package.json, packages/libs/pactjs-generator/.eslintrc.js, packages/libs/pactjs-generator/etc/pactjs-generator.api.md, packages/libs/pactjs-generator/src/contract/generation/generator.ts, packages/libs/pactjs-generator/src/contract/generation/tests/generator.test.ts, packages/libs/pactjs-generator/src/contract/parsing/pactParser.ts, packages/libs/pactjs-generator/src/contract/parsing/tests/pactParser.test.ts, packages/libs/pactjs-generator/src/contract/parsing/utils/utils.ts, packages/tools/pactjs-cli/src/contract-generate/generate.ts, packages/tools/pactjs-cli/src/retrieve-contract/tests/retrieve-contract.test.ts, packages/tools/pactjs-cli/src/utils/callLocal.ts, packages/tools/pactjs-cli/src/utils/retrieveContractFromChain.ts, packages/tools/pactjs-cli/src/utils/tests/callLocal.test.ts, packages/tools/pactjs-cli/src/utils/tests/retrieveContractFromChain.test.ts
Fixed the issue of resolving dependencies when the namespace is implicitly the same as the module namespace.
=> fix(pactjs-cli): dependency resolution

.changeset/tidy-kids-speak.md, packages/libs/client-utils/src/built-in/describe-module.ts, packages/libs/client-utils/src/integration-tests/built-in.int.test.ts
=> feat(client-utils): add describe-module

packages/tools/kadena-cli/src/keys/commands/keysWalletGenerate.ts, packages/tools/kadena-cli/src/keys/tests/walletGenerate.test.ts, packages/tools/kadena-cli/src/keys/utils/keysDisplay.ts, packages/tools/kadena-cli/src/keys/utils/storage.ts, packages/tools/kadena-cli/src/utils/command.util.ts
=> feat: example of split logic of command in cli

.changeset/rotten-geese-appear.md, packages/apps/tools/src/components/Common/Layout/styles.css.ts, packages/libs/react-ui/src/components/NavHeader/NavHeader.css.ts, packages/libs/react-ui/src/components/NavHeader/NavHeader.tsx, packages/libs/react-ui/src/components/NavHeader/NavHeaderNavigation.tsx, packages/libs/react-ui/src/components/NavHeader/useGlow.ts
=> fix: navigation is not scrollable on mobile

packages/tools/kadena-cli/src/utils/createCommand.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts, packages/tools/kadena-cli/src/utils/helpers.ts, packages/tools/kadena-cli/src/utils/tests/helpers.test.ts
=> feat: add quiet flag to stop interaction on createCommand options

packages/tools/e2e-tests/src/page-objects/tools-app/pages/faucet.page.ts, packages/tools/e2e-tests/src/support/page-objects/tools-app/pages/faucet.page.ts
This PR fixes a locator and some imports
=> Fix imports for E2E tests

.changeset/eighty-pandas-pull.md, packages/libs/react-ui/src/components/BrandLogo/svgs/Kadena.tsx, packages/libs/react-ui/src/components/BrandLogo/svgs/KadenaDevTools.tsx, packages/libs/react-ui/src/components/BrandLogo/svgs/KadenaDocs.tsx, packages/libs/react-ui/src/components/NavHeader/NavHeader.css.ts
=> [@react-ui] Fix: brand logo size

packages/apps/tools/src/pages/faucet/new/index.tsx
---
- https://app.asana.com/0/0/1206219843183938
=> Tools dApp - Faucet: Bugfix removal of public key after successful account creation

.changeset/great-spiders-lay.md, packages/libs/react-ui/src/components/Tooltip/Tooltip.css.ts
---
- https://app.asana.com/0/0/1206193208017747
=> Give zIndex to Tooltip component

.changeset/mighty-mangos-sell.md, packages/libs/react-ui/src/components/Layout/Box/Box.tsx, packages/libs/react-ui/src/components/Layout/Grid/Grid.tsx, packages/libs/react-ui/src/components/Layout/Stack/Stack.tsx
=> chore(@kadena/react-ui): Updated the Box, Stack, and Grid components to accept refs

packages/apps/tools/src/components/Global/AccountHoverTag/index.tsx, packages/apps/tools/src/pages/faucet/new/index.tsx
---
- https://app.asana.com/0/0/1206193208017745
=> Use period as masking character instead of *

packages/apps/tools/src/components/Global/OptionsModal/OptionsModal.tsx
---
- https://app.asana.com/0/0/1206193212086620
=> Make stored Setting selected value when opening modal

.changeset/thin-carrots-pull.md, packages/apps/graph/.env.example, packages/apps/graph/package.json, packages/apps/graph/src/db/prisma-client.ts, packages/apps/graph/src/graph/query/block.ts, packages/apps/graph/src/graph/subscription/new-blocks.ts, packages/apps/graph/src/utils/dotenv.ts, pnpm-lock.yaml
=> [@kadena/graph] Prisma Logging

.changeset/long-brooms-switch.md, packages/apps/graph/src/graph/objects/block.ts, packages/apps/graph/src/graph/query/completed-block-heights.ts
Certain queries were not properly optimized
=> [@kadena/graph] Add missing query params to Prisma calls

packages/apps/tools/src/pages/faucet/styles.css.ts
=> Make sure chain select box is fully visible again

.changeset/eight-falcons-sell.md, packages/apps/graph-client/src/components/extended-transactions-table/extended-transactions-table.tsx, packages/apps/graph-client/src/components/extended-transfers-table/extended-transfers-table.tsx, packages/apps/graph-client/src/pages/event/[key].tsx, packages/libs/react-ui/src/components/Pagination/PageNav.tsx, packages/libs/react-ui/src/components/Pagination/PageNum.tsx, packages/libs/react-ui/src/components/Pagination/Pagination.css.ts, packages/libs/react-ui/src/components/Pagination/Pagination.stories.tsx, packages/libs/react-ui/src/components/Pagination/Pagination.tsx
=> chore(@kadena/react-ui): Updated the Pagination component to use the Button component and new tokens

packages/tools/kadena-cli/package.json, packages/tools/kadena-cli/src/constants/config.ts, packages/tools/kadena-cli/src/keys/utils/keysHelpers.ts, packages/tools/kadena-cli/src/prompts/tx.ts, packages/tools/kadena-cli/src/tx/commands/createTransaction.ts, packages/tools/kadena-cli/src/utils/createCommand.ts, packages/tools/kadena-cli/src/utils/createCommandFlexible.ts, packages/tools/kadena-cli/src/utils/createOption.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts, packages/tools/kadena-cli/src/utils/helpers.ts, packages/tools/kadena-cli/tsconfig.json
=> [feat] kadena-cli: add new key helpers, create transaction improvements

packages/libs/react-ui/package.json, packages/libs/react-ui/src/components/Tooltip/Tooltip.stories.tsx, packages/libs/react-ui/src/components/Tooltip/Tooltip.tsx, pnpm-lock.yaml
Fixes the bug where the tooltip does not show up on hover when used with the `Button` component
=> fix(@kadena/react-ui): Make `Tooltip` component more robust

.changeset/seven-terms-smoke.md, packages/tools/kadena-cli/src/dapp/commands/dappCreate.ts, packages/tools/kadena-cli/src/dapp/index.ts, packages/tools/kadena-cli/src/program.ts, packages/tools/kadena-cli/src/prompts/genericActionPrompts.ts, packages/tools/kadena-cli/src/utils/createCommand.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts
https://app.asana.com/0/1205969628270714/1206000704279352
We have to publish create kadena app package. 
Working in cli found couple of minor issues in create kadena app package. I'll create a PR for that separately.
=> feat(dapp): implement dapp create command

packages/tools/kadena-cli/.eslintrc.cjs, packages/tools/kadena-cli/src/prompts/tx.ts, packages/tools/kadena-cli/src/tx/commands/createTransaction.ts, packages/tools/kadena-cli/src/tx/commands/templates/mapper.ts, packages/tools/kadena-cli/src/tx/commands/templates/templates.ts, packages/tools/kadena-cli/src/tx/tests/template-mapper.test.ts, packages/tools/kadena-cli/src/tx/utils/template.ts, packages/tools/kadena-cli/src/utils/createCommand.ts
=> Feat/kadena cli/create transaction3

packages/tools/e2e-tests/src/page-objects/react-ui/card.component.ts, packages/tools/e2e-tests/src/page-objects/react-ui/listBox.component.ts, packages/tools/e2e-tests/src/page-objects/tools-app/pages/faucet.page.ts
This PR adds page objects for the listBox component and updates the tools test to use it.
=> fix/ add listBox component and udpate tests

.changeset/fresh-knives-glow.md, packages/apps/graph/src/utils/dotenv.ts
=> [@kadena/graph] Change default values for marmalade branch (Fix)

.changeset/cuddly-queens-stare.md, packages/libs/client-utils/etc/client-utils-built-in.api.md, packages/libs/client-utils/src/built-in/index.ts
=> chore(client-utils): export describeModule

.changeset/hip-books-punch.md, packages/apps/graph-client/src/components/compact-transactions-table/compact-transactions-table.tsx, packages/apps/graph-client/src/components/compact-transfers-table/compact-transfers-table.tsx
---
- https://app.asana.com/0/0/1206479613829286
=> [@kadena/graph-client] Implement Tooltip in truncated columns (Clean)

packages/apps/tools/src/components/Global/AccountNameField/index.tsx, packages/apps/tools/src/hooks/use-account-details-query.ts, packages/apps/tools/src/pages/storybook/index.tsx, packages/apps/tools/src/pages/storybook/styles.css.ts
=> useAccountDetailsQuery hook

packages/apps/docs/src/config.yaml, packages/apps/docs/src/docs/marmalade/architecture/sale-contracts.md, packages/apps/docs/src/docs/marmalade/auctions/conventional-auction.md, packages/apps/docs/src/docs/marmalade/auctions/dutch-auction.md, packages/apps/docs/src/docs/marmalade/auctions/index.md, packages/apps/docs/src/docs/marmalade/index.tsx
=> feat(docs): add marmalade auction docs

.changeset/eight-paws-peel.md, packages/libs/chainweb-node-client/src/listen.ts, packages/libs/chainweb-node-client/src/local.ts, packages/libs/chainweb-node-client/src/poll.ts, packages/libs/chainweb-node-client/src/send.ts, packages/libs/chainweb-node-client/src/spv.ts
Removed all console.erros from the chainweb-code-client functions
This PR will address the issue [#1620](https://github.com/kadena-community/kadena.js/issues/1620)
=> fix(chainweb-code-client): remove console.error

.github/workflows/ci.yml
Pipelines are failing in Install rust dependencies step https://github.com/kadena-community/kadena.js/actions/runs/7888906835/job/21527791875?pr=1622
=> chore: add update before install packages

packages/tools/e2e-tests/src/tests/graph/account.test.ts, packages/tools/e2e-tests/src/tests/setup/faucet.setup.ts, packages/tools/e2e-tests/tsconfig.json
Small bit of maintenance to reduce the amount of path aliases.
=> patch: tsconfig maintenance

.changeset/small-timers-mate.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/objects/non-fungible-chain-account.ts, packages/apps/graph/src/graph/types/graphql-types.ts, packages/apps/graph/src/services/account-service.ts
=> [@kadena/graph] Remove coin related data from non-fungible account (Fix)

.changeset/fifty-pillows-breathe.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/devnet/simulation/marmalade/get-token-info.ts, packages/apps/graph/src/graph/builder.ts, packages/apps/graph/src/graph/index.ts, packages/apps/graph/src/graph/objects/token-info.ts, packages/apps/graph/src/graph/objects/token.ts, packages/apps/graph/src/graph/types/graphql-types.ts
=> [@kadena/graph] Add TokenInfo to Token (Feat)

.changeset/funny-geckos-hear.md, packages/tools/kadena-cli/src/account/commands/accountDetails.ts, packages/tools/kadena-cli/src/prompts/account.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts
Use `fungible` from account alias file and re-use account select prompt same as fund command
=> fix(account-details): remove fungible manual selection and update account selection

packages/apps/proof-of-us/package.json, packages/apps/proof-of-us/src/scripts/createEvent.ts
This PR updates the event creation script to be slightly more flexible and updates a deprecated function to the latest and greatest.
=> feat: make the script a bit more flexible

packages/tools/kadena-cli/package.json, packages/tools/kadena-cli/src/constants/config.ts, packages/tools/kadena-cli/src/index.ts, packages/tools/kadena-cli/src/keys/commands/keysDecrypt.ts, packages/tools/kadena-cli/src/prompts/tx.ts, packages/tools/kadena-cli/src/tx/commands/templates/mapper.ts, packages/tools/kadena-cli/src/tx/commands/templates/templates.ts, packages/tools/kadena-cli/src/tx/commands/txCreateTransaction.ts, packages/tools/kadena-cli/src/tx/commands/txSend.ts, packages/tools/kadena-cli/src/tx/commands/txSignWithAliasFile.ts, packages/tools/kadena-cli/src/tx/commands/txSignWithKeypair.ts, packages/tools/kadena-cli/src/tx/commands/txSignWithLocalWallet.ts, packages/tools/kadena-cli/src/tx/commands/txTestSignedTransaction.ts, packages/tools/kadena-cli/src/tx/index.ts, packages/tools/kadena-cli/src/tx/tests/transaction-live.test.ts, packages/tools/kadena-cli/src/tx/txOptions.ts, packages/tools/kadena-cli/src/tx/utils/input.ts, packages/tools/kadena-cli/src/tx/utils/storage.ts, packages/tools/kadena-cli/src/tx/utils/txHelpers.ts, packages/tools/kadena-cli/src/utils/command.util.ts, packages/tools/kadena-cli/src/utils/createCommand.ts, packages/tools/kadena-cli/src/utils/createCommandFlexible.ts, packages/tools/kadena-cli/src/utils/createOption.ts, packages/tools/kadena-cli/src/utils/helpers.ts, packages/tools/kadena-cli/src/utils/logger.ts, packages/tools/kadena-cli/src/utils/stdin.ts, pnpm-lock.yaml
=> feat: add stin processing to template,sign,send

packages/tools/kadena-cli/src/account/commands/accountFund.ts, packages/tools/kadena-cli/src/dapp/commands/dappCreate.ts
- Improve error message for dapp create missing project name
- Add additional check for fund account only for `coin`
=> fix: improve error message + fund only coin fungible

packages/apps/proof-of-us/src/components/AvatarEditor/AvatarEditor.tsx
=> fix(pou): fix avatar size

packages/tools/kadena-cli/src/tx/commands/templates/templates.ts, packages/tools/kadena-cli/src/tx/commands/txCreateTransaction.ts, packages/tools/kadena-cli/src/tx/commands/txTestSignedTransaction.ts, packages/tools/kadena-cli/src/tx/tests/template-mapper.test.ts, packages/tools/kadena-cli/src/tx/tests/transaction-live.test.ts
=> fix: cli transactions type error for amount

packages/tools/kadena-cli/package.json
=> Chore/kadena cli/version

packages/tools/kadena-cli/README.md
=> Updated Readme CLI

.changeset/smooth-beers-sit.md, packages/apps/graph-client/src/components/token-table/token-table.tsx, packages/apps/graph-client/src/pages/account/overview/[fungible]/[account].tsx, packages/apps/graph-client/src/pages/account/overview/[fungible]/[account]/[chain].tsx
=> [@kadena/graph-client] Fix Token object ChainId

.changeset/spotty-lions-exercise.md, packages/libs/react-ui/src/components/Form/NumberField/NumberField.css.ts, packages/libs/react-ui/src/components/Form/NumberField/NumberField.tsx, packages/libs/react-ui/src/components/Form/TextField/TextField.stories.tsx
This pr just widens the clickable area for the button to all the width it displays
=> chore: added clickable area for button

packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/account/commands/accountList.ts, packages/tools/kadena-cli/src/account/index.ts, packages/tools/kadena-cli/src/prompts/account.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts, packages/tools/kadena-cli/src/utils/tableDisplay.ts, packages/tools/kadena-cli/transaction-hRnCWWI_QeWLIj_w1AaV2ldcpx5tQv4yaDScgt_o_Qw.json
https://app.asana.com/0/1205969628270714/1206644161687865/f
`account list`
Screenshot reference for single `alias`  and `all` selection
=> feat(account): implement account list sub command

packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/dapp/commands/dappCreate.ts
=> Kadena CLI | improvements typograhy

.changeset/yellow-otters-guess.md, packages/apps/graph-client/package.json, packages/apps/graph-client/src/graphql/queries.graph.ts, packages/apps/graph-client/src/graphql/subscriptions.graph.ts, packages/apps/graph-client/src/pages/_app.tsx, packages/apps/graph-client/src/pages/event/[key].tsx, packages/apps/graph-client/src/pages/index.tsx, packages/apps/graph-client/src/pages/transactions/[key].tsx, packages/apps/graph/generated-schema.graphql, packages/apps/graph/package.json, packages/apps/graph/src/graph/subscription/events.ts, packages/apps/graph/src/graph/subscription/new-blocks-from-depth.ts, packages/apps/graph/src/graph/subscription/new-blocks.ts, packages/apps/graph/src/graph/subscription/transaction.ts, packages/apps/graph/src/index.ts, pnpm-lock.yaml
https://app.asana.com/0/1205801361945248/1206590017183507/f
=> [@kadena/graph] Subscriptions over WebSockets instead of SSE. Replaced ID return types with full Objects

packages/tools/kadena-cli/src/account/accountOptions.ts, packages/tools/kadena-cli/src/account/commands/accountAddFromWallet.ts, packages/tools/kadena-cli/src/account/commands/accountAddManual.ts, packages/tools/kadena-cli/src/account/commands/accountDetails.ts, packages/tools/kadena-cli/src/account/commands/accountFund.ts, packages/tools/kadena-cli/src/account/commands/accountList.ts, packages/tools/kadena-cli/src/account/commands/accountResolveAddressToName.ts, packages/tools/kadena-cli/src/account/commands/accountResolveNameToAddress.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts
Moving account related options account options from global options
=> refactor(cli): move account options from global options

packages/apps/proof-of-us/src/EditorForm/EditorForm.tsx, packages/apps/proof-of-us/src/EditorForm/style.css.ts, packages/apps/proof-of-us/src/components/AvatarEditor/AvatarEditor.tsx, packages/apps/proof-of-us/src/components/AvatarEditor/styles.css.ts, packages/apps/proof-of-us/src/components/Button/SharedButton.css.ts, packages/apps/proof-of-us/src/components/Button/style.css.ts, packages/apps/proof-of-us/src/components/DetailView/DetailView.tsx, packages/apps/proof-of-us/src/components/DetailView/style.css.ts, packages/apps/proof-of-us/src/components/IconButton/style.css.ts, packages/apps/proof-of-us/src/components/ListSignees/ListSignees.tsx, packages/apps/proof-of-us/src/components/ListSignees/Signee.tsx, packages/apps/proof-of-us/src/components/Modal/Modal.tsx, packages/apps/proof-of-us/src/components/ScreenHeight/ScreenHeight.tsx, packages/apps/proof-of-us/src/components/ShareView/ShareView.tsx, packages/apps/proof-of-us/src/components/ShareView/style.css.ts, packages/apps/proof-of-us/src/components/SignStatus/style.css.ts, packages/apps/proof-of-us/src/components/TitleHeader/TitleHeader.tsx, packages/apps/proof-of-us/src/features/Share/ConnectShare.tsx, packages/apps/proof-of-us/src/styles/tokens.css.ts
- Added title to AvatarEditor
- Added "Tap to Tag" Modal
- Changed success color acccording to the design
- Adapting styles to the design
=> feat(pou): Fix styles, adding modal

.changeset/orange-taxis-rescue.md, packages/apps/graph-client/src/graphql/queries.graph.ts, packages/apps/graph-client/src/graphql/subscriptions.graph.ts, packages/apps/graph-client/src/pages/event/[key].tsx
=> [@kadena/graph-client] Added parameters filter to events page

packages/tools/kadena-cli/src/keys/utils/keysHelpers.ts, packages/tools/kadena-cli/src/tx/utils/txHelpers.ts, packages/tools/kadena-cli/src/tx/utils/txSignWithLocalWallet.ts
=> fix: show full key name instead of alias, better error handing in sign

packages/apps/proof-of-us/src/components/ImagePositions/TagInfo.tsx
=> fix: spellingerror

packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/keys/index.ts, packages/tools/kadena-cli/src/networks/index.ts, packages/tools/kadena-cli/src/wallets/index.ts
rename all subcommands to singular form
=> refactor(cli): make sub command to singular form

packages/apps/docs/src/config.yaml, packages/apps/docs/src/docs/pact/reference/index.md, packages/apps/docs/src/docs/pact/reference/pact-repl-cli.md
Move the ToC from the narrative structure branch back into the current structure.
=> Add ToC to language reference and add cli

.changeset/witty-spoons-call.md, packages/apps/graph-client/src/components/compact-transactions-table/compact-transactions-table.tsx, packages/apps/graph-client/src/components/compact-transfers-table/compact-transfers-table.tsx, packages/apps/graph-client/src/components/extended-transactions-table/extended-transactions-table.tsx, packages/apps/graph-client/src/components/extended-transfers-table/extended-transfers-table.tsx, packages/apps/graph-client/src/graphql/fields/transaction.graph.ts, packages/apps/graph-client/src/graphql/queries.graph.ts, packages/apps/graph-client/src/pages/transactions/[key].tsx, packages/apps/graph/src/graph/objects/block.ts, packages/apps/graph/src/graph/objects/transaction-command.ts, packages/apps/graph/src/graph/objects/transaction-payload.ts
=> [@kadena/graph-client] Cont and Exec Payload renaming (Fix)

packages/tools/kadena-cli/src/account/accountOptions.ts, packages/tools/kadena-cli/src/keys/utils/keysDisplay.ts, packages/tools/kadena-cli/src/prompts/tx.ts, packages/tools/kadena-cli/src/utils/command.util.ts, packages/tools/kadena-cli/src/utils/createCommand.ts, packages/tools/kadena-cli/src/utils/helpers.ts, packages/tools/kadena-cli/src/wallets/commands/walletsWalletGenerate.ts
=> feat(kadena-cli): only show repeat command line when prompts were used

packages/apps/proof-of-us/src/components/Status/LoadingStatus.tsx, packages/apps/proof-of-us/src/styles/loader.css.ts
=> added loading state

.changeset/chilled-foxes-poke.md, packages/apps/proof-of-us/src/utils/proofOfUs.ts, packages/libs/client/etc/client.api.md, packages/libs/client/src/composePactCommand/README.md, packages/libs/client/src/composePactCommand/utils/addSigner.ts, packages/libs/client/src/interfaces/IPactCommand.ts
=> feat(client): add webAuthn scheme

.github/ISSUE_TEMPLATE/001-bug_report.yml, packages/tools/kadena-cli/src/prompts/security.ts, packages/tools/kadena-cli/src/tx/commands/txSignOptions.ts, packages/tools/kadena-cli/src/tx/utils/txSignWithAliasFile.ts, packages/tools/kadena-cli/src/tx/utils/txSignWithLocalWallet.ts, packages/tools/kadena-cli/src/utils/createCommand.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts, packages/tools/kadena-cli/src/utils/helpers.ts, packages/tools/kadena-cli/src/wallets/commands/walletsChangeWalletPassword.ts, packages/tools/kadena-cli/src/wallets/commands/walletsDecrypt.ts, packages/tools/kadena-cli/src/wallets/commands/walletsHdGenerate.ts, packages/tools/kadena-cli/src/wallets/commands/walletsImportWallet.ts, packages/tools/kadena-cli/src/wallets/commands/walletsWalletGenerate.ts
=> Feat/kadena cli/passwordflag

packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/prompts/network.ts, packages/tools/kadena-cli/src/prompts/tx.ts, packages/tools/kadena-cli/src/tx/commands/txSend.ts, packages/tools/kadena-cli/src/tx/txOptions.ts, packages/tools/kadena-cli/src/tx/utils/txHelpers.ts
send transactions based upon the network, and verify them with the transaction command
=> fix(kadena-cli) send transaction

packages/libs/client-examples/tsconfig.json, packages/libs/client-utils/build.config.ts, packages/libs/client-utils/config/api-extractor-built-in.json, packages/libs/client-utils/config/api-extractor-coin.json, packages/libs/client-utils/config/api-extractor-core.json, packages/libs/client-utils/etc/client-utils-coin.api.md, packages/libs/client-utils/etc/client-utils-core.api.md, packages/libs/client-utils/package.json, packages/libs/client-utils/src/core/cross-chain.ts, packages/libs/client-utils/tsconfig.json, packages/libs/toolbox/build.config.ts, pnpm-lock.yaml
using unbuild to create correct esm modules
=> chore(client-utils): esm

packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/account/commands/accountCreate.ts, packages/tools/kadena-cli/src/account/index.ts, packages/tools/kadena-cli/src/account/utils/__tests__/createAccountOnMainnet.test.ts, packages/tools/kadena-cli/src/account/utils/createAccountOnMainnet.ts, packages/tools/kadena-cli/src/mocks/handlers.ts
https://app.asana.com/0/1205969628270714/1206644161687868/f
account creation on only `mainnet`
`kadena account create`
=> feat(account): implement account create sub command

packages/tools/kadena-cli/src/index.ts
=> fix: crypto not defined error for node <= 18

packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/prompts/security.ts, packages/tools/kadena-cli/src/prompts/tx.ts, packages/tools/kadena-cli/src/tx/commands/templates/templates.ts, packages/tools/kadena-cli/src/tx/commands/txCreateTransaction.ts, packages/tools/kadena-cli/src/tx/utils/storage.ts, packages/tools/kadena-cli/src/tx/utils/template.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts, packages/tools/kadena-cli/src/utils/tableDisplay.ts, packages/tools/kadena-cli/src/wallets/commands/walletsWalletGenerate.ts
=> feat(kadena-cli): update template variable handling

packages/tools/kadena-cli/src/tx/utils/txSignWithAliasFile.ts, packages/tools/kadena-cli/src/tx/utils/txSignWithKeypair.ts, packages/tools/kadena-cli/src/tx/utils/txSignWithLocalWallet.ts, packages/tools/kadena-cli/src/wallets/commands/walletsImportWallet.ts
=> chore(kadena-cli): ask pw again for import and fix output for sign

.github/CODEOWNERS, turbo.json
This PR fixes a typo in the turbo config as well as update codeowners
=> fix: typo in turbo config

packages/tools/kadena-cli/src/account/accountOptions.ts, packages/tools/kadena-cli/src/account/commands/accountAddFromWallet.ts, packages/tools/kadena-cli/src/account/commands/accountAddManual.ts, packages/tools/kadena-cli/src/account/commands/accountCreate.ts, packages/tools/kadena-cli/src/account/commands/accountDetails.ts, packages/tools/kadena-cli/src/dapp/commands/dappCreate.ts, packages/tools/kadena-cli/src/dapp/dappOptions.ts, packages/tools/kadena-cli/src/devnet/commands/devnetCreate.ts, packages/tools/kadena-cli/src/devnet/commands/devnetDelete.ts, packages/tools/kadena-cli/src/devnet/commands/devnetManage.ts, packages/tools/kadena-cli/src/devnet/commands/devnetRun.ts, packages/tools/kadena-cli/src/devnet/commands/devnetStop.ts, packages/tools/kadena-cli/src/devnet/commands/devnetUpdate.ts, packages/tools/kadena-cli/src/devnet/devnetOptions.ts, packages/tools/kadena-cli/src/keys/commands/keysPlainGenerate.ts, packages/tools/kadena-cli/src/keys/keysOptions.ts, packages/tools/kadena-cli/src/networks/commands/networkCreate.ts, packages/tools/kadena-cli/src/networks/commands/networkDelete.ts, packages/tools/kadena-cli/src/networks/commands/networkManage.ts, packages/tools/kadena-cli/src/networks/networkOptions.ts, packages/tools/kadena-cli/src/typescript/commands/typescriptGenerateCommand.ts, packages/tools/kadena-cli/src/typescript/typescriptOptions.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts, packages/tools/kadena-cli/src/wallets/commands/walletsDeleteWallet.ts, packages/tools/kadena-cli/src/wallets/commands/walletsImportWallet.ts, packages/tools/kadena-cli/src/wallets/commands/walletsList.ts, packages/tools/kadena-cli/src/wallets/commands/walletsWalletGenerate.ts, packages/tools/kadena-cli/src/wallets/walletOptions.ts
https://app.asana.com/0/1205969628270714/1206464568955822
=> refactor(cli): move non shared options from global options

packages/apps/tools/src/components/Global/LoadingCard/index.tsx, packages/apps/tools/src/components/Global/LoadingCard/styles.css.ts, packages/apps/tools/src/components/Partials/transactions/transfer/sign-form-receiver.tsx, packages/apps/tools/src/components/Partials/transactions/transfer/sign-form-sender.tsx, packages/apps/tools/src/components/Partials/transactions/transfer/submit-transaction-details.tsx, packages/apps/tools/src/hooks/use-account-details-query.ts
=> Tools dApp - Card components with loading state

.changeset/large-hornets-glow.md, packages/libs/client/README.md, packages/libs/client/etc/client.api.md, packages/libs/client/src/composePactCommand/test/composePactCommand.test.ts, packages/libs/client/src/composePactCommand/utils/addSigner.ts, packages/libs/client/src/composePactCommand/utils/addVerifier.ts, packages/libs/client/src/composePactCommand/utils/patchCommand.ts, packages/libs/client/src/composePactCommand/utils/tests/addVerifier.test.ts, packages/libs/client/src/createTransactionBuilder/createTransactionBuilder.ts, packages/libs/client/src/createTransactionBuilder/tests/createTransactionBuilder.test.ts, packages/libs/client/src/interfaces/IPactCommand.ts
Adding support for verifiers based on [verifiers proposal](https://github.com/kadena-io/KIPs/pull/57/files)
=> feat(client): add verifiers

packages/apps/tools/locales/en/common.json, packages/apps/tools/src/components/Partials/transactions/transfer/right-info-sidebar.tsx, packages/apps/tools/src/components/Partials/transactions/transfer/styles.css.ts, packages/apps/tools/src/pages/transactions/transfer/index.tsx
=> [@tools-dapp] Add right sidebar with extra info

.changeset/sweet-needles-worry.md, .github/workflows/ci.yml, packages/apps/graph/src/graph/objects/transfer.ts, packages/apps/graph/src/utils/errors.ts
=> [@kadena/graph] Fix transaction field in transfer object (Fix)

packages/tools/kadena-cli/src/account/commands/accountAddFromWallet.ts, packages/tools/kadena-cli/src/account/commands/accountAddManual.ts, packages/tools/kadena-cli/src/account/utils/addHelpers.ts, packages/tools/kadena-cli/src/keys/utils/keysDisplay.ts, packages/tools/kadena-cli/src/keys/utils/storage.ts, packages/tools/kadena-cli/src/tx/commands/templates/templates.ts, packages/tools/kadena-cli/src/tx/commands/txCreateTransaction.ts, packages/tools/kadena-cli/src/utils/path.util.ts, packages/tools/kadena-cli/src/wallets/commands/walletsHdGenerate.ts
=> feat(kadena-cli): print paths of written file relative to cwd

.changeset/wild-boats-worry.md, packages/apps/graph/src/graph/subscription/events.ts, packages/apps/graph/src/graph/subscription/new-blocks-from-depth.ts, packages/apps/graph/src/graph/subscription/new-blocks.ts
---
- https://app.asana.com/0/0/1206831525805634
=> [@kadena/graph] Subscriptions now only return truely new data

packages/apps/tools/locales/en/common.json, packages/apps/tools/src/components/Partials/transactions/transfer/add-public-keys.tsx, packages/apps/tools/src/components/Partials/transactions/transfer/sign-form-receiver.tsx, packages/apps/tools/src/components/Partials/transactions/transfer/sign-form-sender.tsx, packages/apps/tools/src/components/Partials/transactions/transfer/sign-form.tsx
=> Feat/tools dapp/ledger transfer improvements

.changeset/lazy-crabs-move.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/objects/event.ts, packages/apps/graph/src/graph/query/events.ts
---
- https://app.asana.com/0/0/1206878350413067
=> [@kadena/graph] Fix transaction on events object (Fix)

.changeset/lazy-cars-clean.md, packages/apps/graph/README.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/query/events.ts, packages/apps/graph/src/graph/query/gas-limit-estimate.ts, packages/apps/graph/src/graph/query/transaction.ts, packages/apps/graph/src/graph/subscription/events.ts, packages/apps/graph/src/graph/subscription/transaction.ts
https://app.asana.com/0/1205801361945248/1206879623773053/f
=> [@kadena/graph] Improved schema docs and transaction query

packages/e2e/e2e-base/src/constants/colors.constants.ts
This PR updates colour constants that are used in tools tests
=> fix: update color constants after UI updates

.changeset/four-rockets-jam.md, packages/apps/graph/.env.example, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/query/fungible-account.ts, packages/apps/graph/src/graph/query/fungible-chain-account.ts, packages/apps/graph/src/utils/default.ts, packages/apps/graph/src/utils/dotenv.ts
---
- https://app.asana.com/0/0/1206918504101440
=> [@kadena/graph] Fungible queries - make fungible name not required (Feat)

packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/networks/commands/networkDefault.ts, packages/tools/kadena-cli/src/networks/networkOptions.ts, packages/tools/kadena-cli/src/prompts/network.ts, packages/tools/kadena-cli/src/utils/helpers.ts
---
- https://app.asana.com/0/0/1206877879294040
=> feat(network): network unset with none

packages/apps/proof-of-us/src/components/AvatarEditor/AvatarEditor.tsx, packages/apps/proof-of-us/src/components/AvatarEditor/styles.css.ts, packages/apps/proof-of-us/src/components/Header/style.css.ts, packages/apps/proof-of-us/src/components/ImagePositions/style.css.ts, packages/apps/proof-of-us/src/components/Status/ErrorStatus.tsx, packages/apps/proof-of-us/src/pages/user/proof-of-us/t/[id]/[requestkey]/index.tsx, packages/apps/proof-of-us/src/styles/global.css.ts
- Fix landscape camera mode
- Adding Dashboard button in case of error after signing
=> fix(pou): Fix landscape camera mode

.changeset/silly-ladybugs-itch.md, packages/apps/graph/src/graph/objects/event.ts, packages/apps/graph/src/graph/objects/miner-key.ts, packages/apps/graph/src/graph/objects/transfer.ts
Fixes issues caused by this PR that made nested queries not possible anymore: https://github.com/kadena-community/kadena.js/pull/1763/files
---
- https://app.asana.com/0/0/1206889100027941
=> [@kadena/graph] Restore nested querying

.changeset/rare-foxes-remain.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/package.json, packages/apps/graph/src/graph/builder.ts, packages/apps/graph/src/graph/query/block.ts, packages/apps/graph/src/graph/query/blocks-from-depth.ts, packages/apps/graph/src/graph/query/blocks-from-height.ts, packages/apps/graph/src/graph/query/completed-block-heights.ts, packages/apps/graph/src/graph/query/events.ts, packages/apps/graph/src/graph/query/fungible-account-by-public-key.ts, packages/apps/graph/src/graph/query/fungible-account.ts, packages/apps/graph/src/graph/query/fungible-chain-account-by-public-key.ts, packages/apps/graph/src/graph/query/fungible-chain-account.ts, packages/apps/graph/src/graph/query/gas-limit-estimate.ts, packages/apps/graph/src/graph/query/non-fungible-account.ts, packages/apps/graph/src/graph/query/non-fungible-chain-account.ts, packages/apps/graph/src/graph/query/pact-query.ts, packages/apps/graph/src/graph/query/transaction-by-public-key.ts, packages/apps/graph/src/graph/query/transaction.ts, packages/apps/graph/src/graph/query/transactions.ts, packages/apps/graph/src/graph/query/transfers.ts, packages/apps/graph/src/graph/subscription/events.ts, packages/apps/graph/src/graph/subscription/new-blocks-from-depth.ts, packages/apps/graph/src/graph/subscription/new-blocks.ts, packages/apps/graph/src/graph/subscription/transaction.ts, packages/apps/graph/src/utils/errors.ts, pnpm-lock.yaml
---
- https://app.asana.com/0/0/1206879623773042
=> [@kadena/graph] Add input validation to queries and subscriptions

packages/tools/kadena-cli/src/account/utils/__tests__/fund.test.ts, packages/tools/kadena-cli/src/account/utils/fund.ts
---
- https://app.asana.com/0/0/1206807019750955
=> fix(account): Add account creation message for fund command

.changeset/proud-otters-fry.md, packages/apps/graph/README.md
---
- https://app.asana.com/0/0/1206879623773063
=> [@kadena/graph] Improve functional documentation (Documentation)

packages/apps/proof-of-us/src/components/AccountProvider/AccountProvider.tsx, packages/apps/proof-of-us/src/components/Modal/Modal.tsx, packages/apps/proof-of-us/src/components/Modal/style.css.ts, packages/apps/proof-of-us/src/components/ScreenHeight/style.css.ts, packages/apps/proof-of-us/src/components/SocialShare/SocialShare.tsx, packages/apps/proof-of-us/src/components/SocialShare/style.css.ts, packages/apps/proof-of-us/src/features/Share/AttendanceShare.tsx, packages/apps/proof-of-us/src/features/Share/ConnectShare.tsx, packages/apps/proof-of-us/src/pages/user/index.tsx
- Fix share buttons markup for desktop
- Fix the path for the SpireKey
- Limit views to 800px except Camera page and ConnectShare
=> fix(pou): Fix share markup for desktop

.changeset/soft-socks-warn.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/query/transaction.ts, packages/apps/graph/src/graph/query/transactions.ts
---
- https://app.asana.com/0/0/1206918504101420
=> [@kadena/graph] Add minimum depth in Transaction queries (Feat)

packages/tools/kadena-cli/src/account/commands/accountDetails.ts, packages/tools/kadena-cli/src/account/commands/accountList.ts, packages/tools/kadena-cli/src/keys/utils/keysDisplay.ts, packages/tools/kadena-cli/src/networks/utils/networkDisplay.ts, packages/tools/kadena-cli/src/tx/commands/txCreateTransaction.ts, packages/tools/kadena-cli/src/tx/commands/txStatus.ts, packages/tools/kadena-cli/src/tx/utils/txDisplayHelper.ts, packages/tools/kadena-cli/src/tx/utils/txSignWithKeypair.ts, packages/tools/kadena-cli/src/tx/utils/txSignWithWallet.ts, packages/tools/kadena-cli/src/utils/createCommand.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts, packages/tools/kadena-cli/src/utils/logger.ts, packages/tools/kadena-cli/src/wallets/commands/walletAdd.ts, packages/tools/kadena-cli/src/wallets/commands/walletExport.ts, packages/tools/kadena-cli/src/wallets/commands/walletGenerateKey.ts, packages/tools/kadena-cli/src/wallets/commands/walletImport.ts
introduce --json and --yaml flags.
=> Feat/kadena cli/formatted output

.changeset/blue-meals-fry.md, packages/apps/graph/src/graph/query/blocks-from-depth.ts, packages/apps/graph/src/graph/query/events.ts, packages/apps/graph/src/graph/query/transaction.ts, packages/apps/graph/src/graph/query/transactions.ts, packages/apps/graph/src/graph/subscription/events.ts, packages/apps/graph/src/graph/subscription/new-blocks-from-depth.ts, packages/apps/graph/src/services/complexity.ts, packages/apps/graph/src/services/depth-service.ts
Added confirmation depth to queries and subscriptions where minimum depth is an argument;
---
- https://app.asana.com/0/0/1206941884773067
=> [@kadena/graph] Implement confirmation depth calculations (Feat)

.github/actions/archive-logs/action.yaml, .github/actions/archive-volumes/action.yaml, .github/actions/end-to-end-tests/action.yaml, .github/actions/runner-setup/action.yaml, .github/actions/sandbox/action.yaml, .github/workflows/ci.yml, packages/e2e/e2e-graph/tests/transaction.test.ts
This PR refactors commonly used steps in pipelines to a generic composite action
=> Chore: update CI to use a composite action for runner setup

.github/CODEOWNERS, packages/libs/react-ui/README.md
=> chore(@kadena/react-ui): Update codeowners

.changeset/thin-lies-impress.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/devnet/simulation/marmalade/create-token-id.ts, packages/apps/graph/src/graph/objects/non-fungible-account.ts, packages/apps/graph/src/graph/objects/non-fungible-chain-account.ts, packages/apps/graph/src/services/systems-check.ts, packages/apps/graph/src/utils/network.ts
- Added some missing documentation
- Fixed marmalade simulation
- Altered systems check to dynamically get the `apiVersion`
---
- https://app.asana.com/0/0/1206998285880293
=> [@kadena/graph] Small fixes and improvements (Fix, Feat. Chore)

.github/labeler.yml, packages/tools/scripts/generate-labels.ts, packages/tools/scripts/validate-labels.ts
This PR re-adds the ```@kadena/``` prefix to labels
=> Fix: No longer remove prefix and regen labels.

.changeset/shy-bugs-deny.md, packages/apps/graph/src/utils/dotenv.ts
=> [@kadena/graph] Change dotenv default values (Fix)

.changeset/chatty-elephants-taste.md, packages/libs/react-ui/src/components/Popover/Popover.css.ts
=> [@react-ui] Fix flickering on Select component

.changeset/bright-llamas-talk.md, packages/apps/graph/src/devnet/simulation/coin/simulate.ts, packages/apps/graph/src/devnet/simulation/marmalade/simulate.ts
---
- https://app.asana.com/0/0/1207000252925555
=> [@kadena/graph] Small improvements for marmalade simulation (Fix)

packages/tools/kadena-cli/src/account/accountOptions.ts, packages/tools/kadena-cli/src/dapp/dappOptions.ts, packages/tools/kadena-cli/src/keys/keysOptions.ts, packages/tools/kadena-cli/src/tx/txOptions.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts
Improve helper text for account sub commands
=> chore: improve help description for account command options

packages/tools/kadena-cli/package.json, packages/tools/kadena-cli/src/account/commands/accountDelete.ts, packages/tools/kadena-cli/src/account/utils/__tests__/createAccountConfigFile.test.ts, packages/tools/kadena-cli/src/account/utils/accountHelpers.ts, packages/tools/kadena-cli/src/account/utils/addHelpers.ts, packages/tools/kadena-cli/src/config/commands/configInit.ts, packages/tools/kadena-cli/src/config/commands/configPath.ts, packages/tools/kadena-cli/src/config/configOptions.ts, packages/tools/kadena-cli/src/config/index.ts, packages/tools/kadena-cli/src/constants/config.ts, packages/tools/kadena-cli/src/constants/networks.ts, packages/tools/kadena-cli/src/networks/commands/networkCreate.ts, packages/tools/kadena-cli/src/networks/commands/networkDefault.ts, packages/tools/kadena-cli/src/networks/commands/networkManage.ts, packages/tools/kadena-cli/src/networks/utils/networkDisplay.ts, packages/tools/kadena-cli/src/networks/utils/networkHelpers.ts, packages/tools/kadena-cli/src/prompts/config.ts, packages/tools/kadena-cli/src/prompts/index.ts, packages/tools/kadena-cli/src/prompts/network.ts, packages/tools/kadena-cli/src/services/config/config.service.ts, packages/tools/kadena-cli/src/services/service-error.ts, packages/tools/kadena-cli/src/test-setup.ts, packages/tools/kadena-cli/src/tx/commands/templates/templates.ts, packages/tools/kadena-cli/src/tx/commands/txCreateTransaction.ts, packages/tools/kadena-cli/src/utils/createCommand.ts, packages/tools/kadena-cli/src/utils/helpers.ts, packages/tools/kadena-cli/src/utils/logger-utils.ts, packages/tools/kadena-cli/src/utils/logger.ts, packages/tools/kadena-cli/src/wallets/commands/walletAdd.ts
=> chore(kadena-cli): add option to config init in home directory

packages/tools/kadena-cli/src/account/commands/accountDetails.ts, packages/tools/kadena-cli/src/account/types.ts
---
- https://app.asana.com/0/0/1206903799270993
=> fix: add support for balance as a object with decimal

packages/apps/proof-of-us/src/components/Confirmation/Confirmation.tsx, packages/apps/proof-of-us/src/components/Confirmation/styles.css.ts, packages/apps/proof-of-us/src/components/ConnectView/ConnectView.tsx, packages/apps/proof-of-us/src/components/ConnectView/styles.css.ts, packages/apps/proof-of-us/src/components/DetailView/DetailView.tsx, packages/apps/proof-of-us/src/components/Modal/style.css.ts, packages/apps/proof-of-us/src/components/SocialShare/SocialShare.tsx, packages/apps/proof-of-us/src/pages/user/index.tsx
- Confirmation popup for Logout
- Bold header for Modals
- Native confirm() popups changed to Custom Confirmation Modal
- Confirm for Drop out btn
=> feat(pou): Add a confirmation popup for Logout

.changeset/selfish-mayflies-arrive.md, packages/apps/graph/src/graph/objects/non-fungible-account.ts, packages/apps/graph/src/graph/objects/non-fungible-chain-account.ts
Consulted @jermaine150 to make sure of this
---
- https://app.asana.com/0/0/1206988211560494
=> Non-fungible accounts' transactions: inclusion of marmalade v1 

.changeset/kind-dancers-bow.md, packages/apps/graph/README.md
---
- https://app.asana.com/0/0/1207034879037534
=> Documentation on Devnet's Graph

packages/tools/kadena-cli/src/program.ts
**Usage: index [options] [command]**
should be:
**Usage: kadena [options] [command]**
This pr solves this.
=> replace index with cli name from constants

packages/tools/kadena-cli/src/networks/commands/networkDelete.ts, packages/tools/kadena-cli/src/networks/utils/networkHelpers.ts, packages/tools/kadena-cli/src/prompts/network.ts
fixes the network delete option when user set default network is not available.
=> fix: network delete when default network is not set

.changeset/chatty-balloons-rest.md, packages/apps/graph/src/services/chainweb-node/mempool.ts
=> Fix issue on Mempool functions regarding network id and api version

.changeset/eighty-hotels-jog.md, packages/apps/graph/.env.example, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/builder.ts, packages/apps/graph/src/graph/index.ts, packages/apps/graph/src/graph/objects/pact-query-response.ts, packages/apps/graph/src/graph/query/pact-query.ts, packages/apps/graph/src/graph/types/graphql-types.ts, packages/apps/graph/src/utils/dotenv.ts
---
- https://app.asana.com/0/0/1207034879037533
=> Add timeout to pact queries and create PactQueryResponse object

.changeset/five-garlics-film.md, packages/apps/graph/src/graph/builder.ts, packages/apps/graph/src/graph/objects/transaction.ts, packages/apps/graph/src/index.ts, packages/apps/graph/src/services/chainweb-node/estimate-gas-limit.ts, packages/apps/graph/src/services/chainweb-node/fungible-account-details.ts, packages/apps/graph/src/services/chainweb-node/mempool.ts, packages/apps/graph/src/services/chainweb-node/non-fungible-account-details.ts, packages/apps/graph/src/services/chainweb-node/raw-query.ts, packages/apps/graph/src/services/systems-check.ts, packages/apps/graph/src/utils/network.ts
* Network config is simplified and runs during system checks instead of before.
* Errors that are not related to the system checks now properly get displayed.
---
- https://app.asana.com/0/0/1207044550959310
=> Fixed network config retrieval running before system checks

packages/tools/kadena-cli/src/prompts/tx.ts
=> fix(kadena-cli): mislabeled prompts in tx add

.changeset/strange-mirrors-tickle.md, packages/apps/graph/README.md, packages/apps/graph/src/graph/query/events.ts, packages/apps/graph/src/graph/subscription/events.ts
=> Event subscription optimization

packages/tools/kadena-cli/README.md
---
- https://app.asana.com/0/0/1206951762878103
=> chore: update command options/arguments in readme

.changeset/good-moose-ring.md, packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/account/accountOptions.ts, packages/tools/kadena-cli/src/account/commands/accountDetails.ts, packages/tools/kadena-cli/src/account/commands/accountFund.ts, packages/tools/kadena-cli/src/account/utils/__tests__/accountDetails.test.ts, packages/tools/kadena-cli/src/account/utils/__tests__/createAndTransferFunds.test.ts, packages/tools/kadena-cli/src/account/utils/__tests__/fund.test.ts, packages/tools/kadena-cli/src/account/utils/__tests__/transferFund.test.ts, packages/tools/kadena-cli/src/account/utils/createAndTransferFunds.ts, packages/tools/kadena-cli/src/account/utils/fund.ts, packages/tools/kadena-cli/src/account/utils/fundHelpers.ts, packages/tools/kadena-cli/src/account/utils/transferFund.ts, packages/tools/kadena-cli/src/constants/account.ts, packages/tools/kadena-cli/src/constants/networks.ts, packages/tools/kadena-cli/src/devnet/faucet/deploy/index.ts, packages/tools/kadena-cli/src/prompts/genericActionPrompts.ts, packages/tools/kadena-cli/src/prompts/network.ts
---
- https://app.asana.com/0/0/1206951762878097
=> feat(fund): enable account funding on devnet

packages/tools/kadena-cli/src/utils/logger.ts, packages/tools/kadena-cli/src/utils/test.util.ts, packages/tools/kadena-cli/src/wallets/commands/walletDelete.ts, packages/tools/kadena-cli/src/wallets/tests/walletsDeleteWallet.test.ts
=> feat(kadena-cli): improve test for delete wallet, add test helper

.changeset/dry-coins-juggle.md, packages/apps/docs/src/components/BottomPageSection/components/Subscribe.tsx, packages/apps/docs/src/components/Layout/components/SideMenu/SideMenu.tsx, packages/apps/docs/src/components/SearchBar/SearchBar.tsx, packages/apps/proof-of-us/src/components/TextField/TextField.tsx, packages/apps/tools/src/components/Common/Layout/partials/Header/Header.tsx, packages/apps/tools/src/components/Common/Layout/partials/Header/styles.css.ts, packages/apps/tools/src/components/Global/AccountNameField/index.tsx, packages/apps/tools/src/components/Global/PublicKeyField/index.tsx, packages/apps/tools/src/components/Global/RequestKeyField/index.tsx, packages/apps/tools/src/components/Partials/transactions/transfer/add-public-keys.tsx, packages/apps/tools/src/components/Partials/transactions/transfer/ledger-details.tsx, packages/libs/react-ui/src/components/Form/ActionButtons/NumberFieldActions.tsx, packages/libs/react-ui/src/components/Form/Field/Field.tsx, packages/libs/react-ui/src/components/Form/Form.css.ts, packages/libs/react-ui/src/components/Form/FormFieldHeader/FormFieldHeader.css.ts, packages/libs/react-ui/src/components/Form/FormFieldHeader/FormFieldHeader.tsx, packages/libs/react-ui/src/components/Form/FormFieldHelpText/FormFieldHelpText.css.ts, packages/libs/react-ui/src/components/Form/NumberField/NumberField.css.ts, packages/libs/react-ui/src/components/Form/NumberField/NumberField.stories.tsx, packages/libs/react-ui/src/components/Form/NumberField/NumberField.test.tsx, packages/libs/react-ui/src/components/Form/NumberField/NumberField.tsx, packages/libs/react-ui/src/components/Form/TextField/TextField.stories.tsx, packages/libs/react-ui/src/components/Form/TextField/TextField.test.tsx, packages/libs/react-ui/src/components/Form/TextField/TextField.tsx, packages/libs/react-ui/src/components/Form/TextareaField/TextareaField.css.ts, packages/libs/react-ui/src/components/Tooltip/Tooltip.css.ts, packages/libs/react-ui/src/components/Tree/TreeItems.tsx, packages/libs/react-ui/src/storyDecorators/index.ts
In this PR I've updated the textField component to the new branding.
=> Feat(react UI)/new input components

.changeset/loud-horses-fetch.md, packages/apps/tools/src/pages/transactions/cross-chain-transfer-finisher/index.tsx, packages/libs/react-ui/src/components/Form/TextareaField/TextareaField.css.ts, packages/libs/react-ui/src/components/Form/TextareaField/TextareaField.stories.tsx, packages/libs/react-ui/src/components/Form/TextareaField/TextareaField.tsx
With this PR the textarea gets the rebranding update.
=> feat: update textarea to new styles

packages/tools/kadena-cli/README.md
Added docs for interactive mode.
=> feat(kadena-cli) added interactive mode docs

packages/tools/kadena-cli/README.md
=> chore(kadena-cli) fix wrong command in docs

packages/apps/graph/src/devnet/deployment/marmalade/config/arguments.ts, packages/apps/graph/src/devnet/deployment/marmalade/deploy.ts
Updates the script to deploy the updated file naming syntax and version upgrades from https://github.com/kadena-io/marmalade/pull/197
=> fix(graph): update `marmalade:deploy` to deploy the updated files in marmalade repo

.changeset/strange-windows-remain.md, packages/libs/react-ui/src/components/Badge/Badge.css.ts, packages/libs/react-ui/src/components/Badge/Badge.stories.tsx
there are new variants for the badge and this includes those
=> chore: badge colorset

packages/libs/client-utils/src/nodejs/deploy-from-directory.ts, packages/libs/client-utils/src/nodejs/marmalade/deployment/defaults.ts, packages/libs/client-utils/src/nodejs/marmalade/deployment/deploy.ts, packages/libs/client-utils/src/nodejs/services/download-git-files.ts
Due to some changes in the marmalade contracts a small change was necessary in the deployment flow.
---
- https://app.asana.com/0/0/1207203046553937
=> Adjustment of marmalade deployment scripts (Feat)

packages/tools/kadena-cli/src/wallets/commands/walletAdd.ts
---
- https://app.asana.com/0/0/1207213600471992
=> fix: log message for account fund command

packages/tools/kadena-cli/src/networks/networkOptions.ts
=> fix(kadena-cli): fix duplicate flag usage in network

packages/tools/kadena-cli/src/wallets/commands/walletImport.ts, packages/tools/kadena-cli/src/wallets/utils/walletHelpers.ts
Make logging of mnemonic more noticable so the end user knows its importance.
=> chore(kadena-cli) make mnemonic phrase more noticable

packages/tools/kadena-cli/src/account/commands/accountAddFromWallet.ts, packages/tools/kadena-cli/src/config/commands/configInit.ts, packages/tools/kadena-cli/src/prompts/account.ts, packages/tools/kadena-cli/src/prompts/config.ts, packages/tools/kadena-cli/src/prompts/devnet.ts, packages/tools/kadena-cli/src/prompts/generic.ts, packages/tools/kadena-cli/src/prompts/keys.ts, packages/tools/kadena-cli/src/prompts/network.ts, packages/tools/kadena-cli/src/prompts/simulate.ts, packages/tools/kadena-cli/src/prompts/tx.ts, packages/tools/kadena-cli/src/prompts/typescript.ts, packages/tools/kadena-cli/src/prompts/wallets.ts, packages/tools/kadena-cli/src/tx/commands/txSignOptions.ts, packages/tools/kadena-cli/src/wallets/commands/walletChangePassword.ts, packages/tools/kadena-cli/src/wallets/commands/walletGenerateKey.ts, packages/tools/kadena-cli/src/wallets/commands/walletImport.ts
---
- https://app.asana.com/0/0/1207158682603339
=> fix: prompt message ending with colon

packages/tools/kadena-cli/src/account/commands/accountAddFromWallet.ts, packages/tools/kadena-cli/src/constants/config.ts, packages/tools/kadena-cli/src/constants/global.ts, packages/tools/kadena-cli/src/prompts/account.ts, packages/tools/kadena-cli/src/prompts/network.ts, packages/tools/kadena-cli/src/prompts/tx.ts, packages/tools/kadena-cli/src/prompts/wallets.ts
---
- https://app.asana.com/0/0/1207158683269838
=> fix: add custom instruction for checkbox selection

packages/tools/kadena-cli/src/account/commands/accountDetails.ts, packages/tools/kadena-cli/src/account/commands/accountList.ts
---
- https://app.asana.com/0/0/1207158683269807
=> fix: account alias command table header

packages/tools/kadena-cli/src/account/accountOptions.ts, packages/tools/kadena-cli/src/account/commands/accountAddFromWallet.ts, packages/tools/kadena-cli/src/prompts/account.ts
Screenshot reference for `index alias public key` 
---
- https://app.asana.com/0/0/1207170077788327
=> fix(account): when display public keys from wallet prefix index and alias

packages/tools/kadena-cli/src/test-setup.ts, packages/tools/kadena-cli/src/tx/commands/txTestSignedTransaction.ts, packages/tools/kadena-cli/src/tx/tests/createTransaction.test.ts, packages/tools/kadena-cli/src/tx/tests/send.test.ts, packages/tools/kadena-cli/src/tx/tests/sign.test.ts, packages/tools/kadena-cli/src/tx/tests/transaction-legacy-live.test.ts, packages/tools/kadena-cli/src/tx/tests/transaction-live.test.ts, packages/tools/kadena-cli/src/tx/utils/txHelpers.ts, packages/tools/kadena-cli/src/tx/utils/txSignWithKeypair.ts, packages/tools/kadena-cli/src/tx/utils/txSignWithWallet.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts
=> feat(kadena-cli): fix legacy signing and add more tests

packages/tools/kadena-cli/src/prompts/account.ts, packages/tools/kadena-cli/src/prompts/network.ts, packages/tools/kadena-cli/src/wallets/commands/walletDelete.ts
added explicit write check for delete wallet
[x]network delete
[x]account delete
[x]wallet delete
=> feat(kadena-cli) explicitly write yes / no for crucial deletion steps

packages/tools/kadena-cli/src/account/accountAddOptions.ts, packages/tools/kadena-cli/src/account/accountOptions.ts, packages/tools/kadena-cli/src/account/commands/accountAdd.ts, packages/tools/kadena-cli/src/account/commands/accountAddFromWallet.ts, packages/tools/kadena-cli/src/account/commands/accountAddManual.ts, packages/tools/kadena-cli/src/account/index.ts, packages/tools/kadena-cli/src/account/utils/__tests__/createAccountName.test.ts, packages/tools/kadena-cli/src/account/utils/createAccountName.ts, packages/tools/kadena-cli/src/prompts/account.ts
---
- https://app.asana.com/0/0/1207181783526431
=> feat(account): combine account add-manual and add-from-wallet into one command

.changeset/fast-experts-admire.md, packages/apps/explorer/src/components/chain-activity-graph/chain-activity-graph.tsx, packages/apps/explorer/src/pages/index.tsx
---
- https://app.asana.com/0/0/1207266388895057
=> K:Explorer Activity Graph Component

packages/tools/kadena-cli/src/account/accountAddOptions.ts, packages/tools/kadena-cli/src/account/accountOptions.ts, packages/tools/kadena-cli/src/account/commands/accountAddFromWallet.ts, packages/tools/kadena-cli/src/account/commands/accountAddManual.ts, packages/tools/kadena-cli/src/account/tests/accountAdd.test.ts, packages/tools/kadena-cli/src/account/types.ts, packages/tools/kadena-cli/src/account/utils/__tests__/addAccount.test.ts, packages/tools/kadena-cli/src/account/utils/__tests__/mocks.ts, packages/tools/kadena-cli/src/account/utils/addAccount.ts, packages/tools/kadena-cli/src/account/utils/createAccountConfigFile.ts, packages/tools/kadena-cli/src/prompts/account.ts
---
- https://app.asana.com/0/0/1207178351013591
=> feat(account): remove on chain validation for add from wallet option and make conditional validation for manual

.changeset/healthy-jobs-battle.md, packages/apps/explorer/src/components/block-activity-graph/block-activity-graph.tsx
---
- https://app.asana.com/0/0/1207266388895065
=> Block Activity Graph added

packages/tools/kadena-cli/src/config/commands/configInit.ts, packages/tools/kadena-cli/src/test-setup.ts, packages/tools/kadena-cli/src/tx/commands/templates/templates.ts, packages/tools/kadena-cli/src/tx/tests/transaction-live.test.ts
=> fix(kadena-cli): safetransfer fixes and test improvements

packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/account/accountAddOptions.ts, packages/tools/kadena-cli/src/account/commands/accountAddFromWallet.ts, packages/tools/kadena-cli/src/account/commands/accountAddManual.ts, packages/tools/kadena-cli/src/account/tests/accountAdd.test.ts, packages/tools/kadena-cli/src/prompts/account.ts, packages/tools/kadena-cli/src/wallets/commands/walletAdd.ts, packages/tools/kadena-cli/src/wallets/commands/walletGenerateKey.ts, packages/tools/kadena-cli/src/wallets/utils/walletHelpers.ts
---
- https://app.asana.com/0/0/1207259327882927
=> feat(account): public keys selection improvement for manual and wallet type

packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/keys/utils/keysDisplay.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts
=> Docs/kadena cli/docs improvements

packages/tools/kadena-cli/README.md
=> feat(kadena-cli) fixes

packages/apps/docs/src/docs/reference/cli-README.md, packages/tools/kadena-cli/src/constants/account.ts
replaces https://github.com/kadena-community/kadena.js/pull/2106
=> docs(kadena-cli): fix errors and add export subcommand

packages/tools/kadena-cli/package.json, packages/tools/kadena-cli/rollup.config.mjs, packages/tools/kadena-cli/src/index.ts, packages/tools/kadena-cli/src/utils/createOption.ts, packages/tools/kadena-cli/tsconfig.json, pnpm-lock.yaml
=> feat(kadena-cli): add bundler

.changeset/itchy-dogs-melt.md, packages/libs/react-ui/src/styles/tokens/contract.css.ts, packages/libs/react-ui/src/styles/tokens/dark.css.ts, packages/libs/react-ui/src/styles/tokens/light.css.ts
=> chore: token sync

packages/apps/docs/src/docs/participate/docs.md, packages/apps/docs/src/pages/index.tsx
=> Remove obsolete references

packages/apps/docs/src/docs/build/nft-marmalade/concrete-policies.md, packages/apps/docs/src/docs/build/nft-marmalade/create-a-collection.md, packages/apps/docs/src/docs/build/nft-marmalade/create-nft.md, packages/apps/docs/src/docs/reference/marmalade/policy-manager.md, packages/apps/docs/src/docs/reference/marmalade/sale-contracts.md
@ggobugi27 @wooglie @jermaine150 Looking for a review/approval for this minor title change.
=> Minor name change for contract architecture

.changeset/thirty-gifts-train.md, packages/apps/docs/src/components/Markdown/Code/style.css.ts
=> docs inline code styling fix

.changeset/perfect-cheetahs-visit.md, packages/libs/react-ui/src/components/Badge/Badge.css.ts, packages/libs/react-ui/src/index.ts
added the high contrast variant and fixed the inline spacing for the large variant
=> added the high contrast variant

packages/libs/react-ui/src/components/Modal/Modal.css.ts
the background should be blurred or not full opaque
=> fix: background

packages/tools/kadena-cli/src/utils/stdin.ts
=> fix(kadena-cli): fix cli tests when run via turbo

packages/apps/docs/src/docs/build/authentication/register-an-account.md
The Kadena SpireKey has had some major updates. This PR brings the documentation back in sync with the functionality of the application.
=> chore(docs): update spirekey registration docs

.changeset/pretty-crabs-jog.md, packages/libs/hd-wallet/src/SLIP10/kadenaGenKeypairFromSeed.ts, packages/libs/hd-wallet/src/SLIP10/kadenaGetPublic.ts, packages/libs/hd-wallet/src/SLIP10/kadenaSign.ts, packages/libs/hd-wallet/src/SLIP10/utils/isDerivationPathTemplateValid.ts, packages/libs/hd-wallet/src/SLIP10/utils/tests/isDerivationPathTemplateValid.test.ts
=> improve(hd-wallet): verify that the derivation path template includes <index>

packages/libs/client-utils/src/integration-tests/support/helpers.ts, packages/libs/client-utils/src/marmalade/burn-token.ts, packages/libs/client-utils/src/marmalade/buy-token.ts, packages/libs/client-utils/src/marmalade/create-auction.ts, packages/libs/client-utils/src/marmalade/create-token.ts, packages/libs/client-utils/src/marmalade/get-quote-info.ts, packages/libs/client-utils/src/marmalade/helpers.ts, packages/libs/client-utils/src/marmalade/index.ts, packages/libs/client-utils/src/marmalade/mint-token.ts, packages/libs/client-utils/src/marmalade/offer-token.ts, packages/libs/client-utils/src/marmalade/place-bid.ts, packages/libs/client-utils/src/marmalade/transfer-create-token.ts, packages/libs/client-utils/src/marmalade/transfer-token.ts, packages/libs/client-utils/src/marmalade/update-auction.ts, packages/libs/client-utils/src/marmalade/withdraw-token.ts
Added `getQuoteInfo` function in this PR and reorganized some imports
=> [@kadena/client-utils]: added getQuoteInfo function

packages/tools/kadena-cli/src/dapp/commands/dappCreate.ts, packages/tools/kadena-cli/src/dapp/tests/dappCreate.test.ts
---
- https://app.asana.com/0/0/1207147478057776
=> test: add tests for dapp add command

.changeset/rotten-falcons-fix.md, packages/apps/graph/src/graph/subscription/transaction.ts
=> Ensure Subscriptions do not yield same values

.changeset/silent-grapes-live.md, packages/libs/react-ui/src/components/Button/Button.css.ts, packages/libs/react-ui/src/components/Tabs/Tab.tsx, packages/libs/react-ui/src/components/Tabs/TabPanel.tsx, packages/libs/react-ui/src/components/Tabs/Tabs.css.ts, packages/libs/react-ui/src/components/Tabs/Tabs.stories.tsx, packages/libs/react-ui/src/components/Tabs/Tabs.tsx, packages/libs/react-ui/src/components/Tabs/TabsPagination.tsx, packages/libs/react-ui/src/components/Tabs/utils/calculateScroll.test.tsx, packages/libs/react-ui/src/components/Tabs/utils/calculateScroll.tsx, packages/libs/react-ui/src/components/Tabs/utils/getMinimalChildWidth.test.tsx, packages/libs/react-ui/src/components/Tabs/utils/getMinimalChildWidth.tsx, packages/libs/react-ui/src/utils/debounce.test.ts, packages/libs/react-ui/src/utils/debounce.ts, packages/libs/react-ui/src/utils/index.ts
This PR will update the tabs component to the new brand update.
Also included:
- Pagination for the tabs list. 
- focus on active item when rendered.
- Support scroll and pagination on all devices.
=> feat: initial rebranding and added pagination for tabs component

.changeset/hip-tomatoes-smile.md, packages/libs/react-ui/src/components/Dialog/Dialog.stories.tsx, packages/libs/react-ui/src/components/Notification/Notification.stories.tsx, packages/libs/react-ui/src/components/Tabs/Tabs.stories.tsx
=> stable status to ui components

.changeset/shy-pianos-own.md, packages/apps/explorer/package.json, packages/apps/explorer/src/components/layout/media.ts, packages/apps/explorer/src/pages/_app.tsx, pnpm-lock.yaml
=> Explorer Media SSR

packages/apps/docs/src/docs/build/frontend/kadena-client.md, packages/apps/docs/src/docs/reference/kadena-client/kadena-js.md
=> fix some formatting issues around poll functions

packages/libs/hd-wallet/src/chainweaver/compatibility/kadenaSign.ts, packages/libs/hd-wallet/src/chainweaver/compatibility/kadenaSignFromRootKey.ts, packages/libs/hd-wallet/src/chainweaver/tests/chainweaver.test.ts
=> hd-wallet: renamed massage to hash in kadenaSign for better readability

.github/PULL_REQUEST_TEMPLATE.md
To improve the quality and speed of the reviewers work, we've added a two sections to be filled when submitting a PR.
This allows us to be consious about what they're testing, and allows the reviewer to give feedback on what is tested. It also allows the reviewer to get a head start when working through the PR
=> chore(monorepo): add testing to pr template

packages/apps/dev-wallet/src/App/layout-mini.tsx
Fix theme toggle UI in layout mini
=> fix(dev-wallet): fix theme toggle in layout mini

.changeset/config.json, .changeset/lemon-masks-tan.md
Add missing Changeset for added `client-utils` functionality (`list-modules`)  (plus fixed `changeset add` command)
projects)
=> Add missing Changeset for added client-utils functionality

.changeset/chatty-laws-mate.md, packages/tools/kadena-cli/src/commands/tx/commands/txHistory.ts, packages/tools/kadena-cli/src/commands/tx/commands/txLocal.ts, packages/tools/kadena-cli/src/commands/tx/commands/txSend.ts, packages/tools/kadena-cli/src/commands/tx/commands/txStatus.ts, packages/tools/kadena-cli/src/commands/tx/index.ts, packages/tools/kadena-cli/src/commands/tx/utils/txHelpers.ts, packages/tools/kadena-cli/src/constants/config.ts
Replaces: https://github.com/kadena-community/kadena.js/pull/2200
=> feat(tx-logs): add tx history command

.changeset/popular-items-rush.md, packages/apps/graph/src/graph/objects/transfer.ts
projects)
---
- https://app.asana.com/0/0/1207497173734584
=> Fix cross chain transfers counterpart find

.changeset/plenty-feet-juggle.md, packages/apps/explorer/src/graphql/fragments/account.graph.ts, packages/apps/explorer/src/graphql/fragments/events.graph.ts, packages/apps/explorer/src/graphql/fragments/transactions.graph.ts, packages/apps/explorer/src/graphql/queries/account.graph.ts, packages/apps/explorer/src/graphql/queries/blocks-from-heights-graph.ts, packages/apps/explorer/src/graphql/queries/events.graph.ts, packages/apps/explorer/src/graphql/queries/transactions.graph.ts
projects)
---
- https://app.asana.com/0/0/1207526146558813
=> Queries and fragments needed for main seach

.changeset/large-rice-study.md, packages/apps/explorer/src/components/copy-button/copy-button.tsx, packages/apps/explorer/src/components/data-render-component/data-render-component-horizontal/data-render-component-horizontal.tsx, packages/apps/explorer/src/components/data-render-component/data-render-component-vertical/data-render-component-vertical.tsx, packages/apps/explorer/src/components/data-render-component/data-render-component-vertical/styles.css.ts, packages/apps/explorer/src/components/data-render-component/data-render-component.tsx, packages/apps/explorer/src/components/transaction-components/transaction-request-component.tsx, packages/apps/explorer/src/components/transaction-components/transaction-result-component.tsx, packages/apps/explorer/src/pages/transaction/[requestKey].tsx
Related Issue/Asana ticket: https://app.asana.com/0/1205801361945248/1207539088840401/f
=> fix(explorer): styling of the transactions page

.changeset/swift-parrots-shop.md, packages/libs/react-ui/README.md, packages/libs/react-ui/package.json, packages/libs/react-ui/src/styles/global.css.ts
Short description: Fixed the references from `Kadena Design System` to Kadena's `Kode Design System`
projects)
=> fix design system name

.changeset/pink-scissors-behave.md, packages/libs/react-ui/README.md
=> name fix leftover

packages/libs/client-utils/src/integration-tests/marmalade.int.test.ts, packages/libs/client-utils/src/marmalade/config.ts, packages/libs/client-utils/src/marmalade/create-token.ts, packages/libs/client-utils/src/marmalade/helpers.ts, packages/libs/client-utils/src/marmalade/policy-config.ts
rename updatable to non updatable uri policy
=> chore: rename updatable to non updatable uri policy

.changeset/gold-bulldogs-smell.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/query/events.ts, packages/apps/graph/src/graph/query/transactions.ts
projects)
---
- https://app.asana.com/0/0/1207573252092703
=> Add `maxHeigh` and `minHeight` to Events and Transactions queries

.changeset/wet-pugs-end.md, packages/libs/react-ui/src/components/Form/Checkbox/Checkbox.css.ts
=> Checkbox icon token fix

pnpm-lock.yaml
=> fix lockfile

.changeset/three-coins-tap.md, packages/apps/explorer/.env.example
=> Fix local `.env` variables

packages/apps/tools/locales/en/common.json, packages/apps/tools/package.json, packages/apps/tools/src/components/Global/CustomAccordion/CustomAccordion.tsx, packages/apps/tools/src/components/Global/CustomTree/CustomTree.css.ts, packages/apps/tools/src/components/Global/CustomTree/CustomTree.tsx, packages/apps/tools/src/components/Global/CustomTree/CustomTreeNode.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/SidePanel/index.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/SidePanel/search-bar.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/SidePanel/styles.css.ts, packages/apps/tools/src/components/Global/ModuleExplorer/index.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/statusbar.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/utils.test.ts, packages/apps/tools/src/components/Global/ModuleExplorer/utils.ts, packages/apps/tools/src/hooks/use-modules-query.ts, packages/apps/tools/src/pages/modules/explorer/index.tsx, packages/apps/tools/src/pages/modules/explorer/utils.ts, pnpm-lock.yaml
This PR contains the search bar which is part of the lefthand side of the modules explorer.
projects)
---
- https://app.asana.com/0/0/1207526466628692
=> Tools dApp - Module Explorer UX/UI revamp - Search bar

.gitignore
Short description: ignore `.envrc` for use with direnv
=> chore(monorepo): ignore .envrc for use with direnv

packages/apps/tools/src/components/Common/Layout/partials/Header/Header.tsx, packages/apps/tools/src/components/Global/CustomAccordion/CustomAccordion.css.ts, packages/apps/tools/src/components/Global/CustomTree/CustomTree.css.ts, packages/apps/tools/src/components/Global/CustomTree/CustomTree.tsx, packages/apps/tools/src/components/Global/CustomTree/CustomTreeNode.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/index.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/tabs.tsx, packages/apps/tools/src/pages/modules/explorer/index.tsx, packages/apps/tools/src/pages/modules/explorer/utils.test.ts, packages/apps/tools/src/pages/modules/explorer/utils.ts, packages/apps/tools/src/resources/styles/globals.css
This PR contains various small UX/UI improvements after doing a walkthrough with Albert & Isa.
projects)
---
- https://app.asana.com/0/0/1206834560303155
=> Tools dApp - Module Explorer UX/UI small improvements

packages/apps/tools/src/constants/side-menu-items.tsx, packages/apps/tools/src/pages/home/index.tsx
This PR enables the Modules Explorer to be reachable through the side menu & top navigation. Essentially _releasing_ the Modules Explorer to production.
projects)
---
- https://app.asana.com/0/0/1206832610116440
=> [Tools dApp] - Release Modules Explorer

.changeset/fifty-radios-train.md, .github/CODEOWNERS, packages/libs/react-ui/src/styles/README.md
Related Issue/Asana ticket: https://app.asana.com/0/1206752931509995/1207508621817372/f
=> chore(react-ui): add documentation for the useTheme hook

packages/apps/docs/src/docs/build/dev-with-cli.md, packages/apps/docs/src/docs/reference/cli/cli-config.md
Related Issue/Asana ticket: https://app.asana.com/0/1205619636589593/1207470622100857
https://app.asana.com/0/1205969628270714/1207307903477047
Short description: Change `kadena config path` to `kadena config show` and update output.
projects)
=> Update kadena config show

packages/apps/docs/src/docs/build/nft-marmalade/create-a-collection.md, packages/apps/docs/src/docs/build/nft-marmalade/create-nft.md
projects)
---
- https://app.asana.com/0/0/1207594668314375
=> [Docs] Update Create a non-fungible token to use the ledger mint function and update both the NFT and collection tutorials with the URI guard

.changeset/silly-scissors-wait.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/query/completed-block-heights.ts
projects)
---
- https://app.asana.com/0/0/1207646412962492
=> Fix completed heights issue

.changeset/modern-rabbits-mix.md, packages/libs/react-ui/src/components/Table/Table.css.ts
https://app.asana.com/0/1205801361945248/1207674743008134/f
=> fix(reactui): fix the width issue from table

.changeset/strange-shrimps-share.md, packages/apps/explorer/.prettierignore, packages/apps/explorer/README.md
projects)
---
- https://app.asana.com/0/0/1207573241734880
=> Update documentation on Explorer - related to graph dependency

.changeset/hot-apricots-grin.md, packages/libs/react-ui/README.md, packages/libs/react-ui/src/components/Form/Checkbox/CheckboxGroup.stories.tsx, packages/libs/react-ui/src/components/Form/Checkbox/CheckboxGroup.tsx, packages/libs/react-ui/src/components/Form/Combobox/Combobox.tsx, packages/libs/react-ui/src/components/Form/Field/Field.tsx, packages/libs/react-ui/src/components/Form/Form.css.ts, packages/libs/react-ui/src/components/Form/FormFieldHeader/FormFieldHeader.css.ts, packages/libs/react-ui/src/components/Form/FormFieldHeader/FormFieldHeader.tsx, packages/libs/react-ui/src/components/Form/NumberField/NumberField.css.ts, packages/libs/react-ui/src/components/Form/NumberField/NumberField.stories.tsx, packages/libs/react-ui/src/components/Form/NumberField/NumberField.tsx, packages/libs/react-ui/src/components/Form/NumberField/NumberFieldActions.tsx, packages/libs/react-ui/src/components/Form/RadioGroup/RadioGroup.stories.tsx, packages/libs/react-ui/src/components/Form/RadioGroup/RadioGroup.tsx, packages/libs/react-ui/src/components/Form/Select/Select.stories.tsx, packages/libs/react-ui/src/components/Form/Select/Select.tsx, packages/libs/react-ui/src/components/Form/TextField/TextField.stories.tsx, packages/libs/react-ui/src/components/Form/TextField/TextField.tsx, packages/libs/react-ui/src/components/Table/TableSelectionCell.tsx, packages/libs/react-ui/src/styles/utils.ts
Minimal width Form field elements fixed and Form field label orientation enhanced with the direction to flow horizontally or vertically
=> Form fields min-width issue + direction enhancement

.changeset/thick-emus-pretend.md
=> feat(kadena-cli): Added pactjs command changeset

packages/apps/docs/src/docs/build/nft-marmalade/storage.md
Mostly content from Pascal
https://github.com/kadena-community/kadena.js/pull/2300
projects)
=> Update to Arweave storage from a forked repo

.github/actions/end-to-end-tests/action.yaml, package.json, packages/apps/docs/turbo.json, packages/apps/explorer/package.json, packages/apps/explorer/turbo.json, packages/apps/graph-client/turbo.json, packages/apps/marmalade-marketplace/turbo.json, packages/apps/proof-of-us/turbo.json, packages/apps/tools/turbo.json, packages/libs/client-utils/turbo.json, packages/libs/client/turbo.json, packages/libs/hd-wallet/turbo.json, packages/libs/kode-icons/turbo.json, packages/libs/kode-ui/turbo.json, packages/tools/eslint-config/turbo.json, packages/tools/eslint-plugin/turbo.json, packages/tools/kadena-cli/src/utils/createOption.ts, packages/tools/kadena-cli/turbo.json, packages/tools/markdown/turbo.json, pnpm-lock.yaml, turbo.json
This PR updates Turborepo to the latest available version and fixes some minor issues
=> chore: update turbo to latest

.changeset/early-cameras-try.md, packages/apps/explorer/package.json, packages/apps/explorer/src/context/networks-context.tsx, packages/apps/explorer/src/pages/index.tsx, pnpm-lock.yaml
https://app.asana.com/0/1205801361945248/1207779080296572/f
=> chore(explorer): store network in cookie

packages/apps/docs/src/docs/build/dev-with-cli.md, packages/apps/docs/src/docs/reference/cli/cli-account.md
projects)
---
- https://app.asana.com/0/0/1207470622100857
=> Add coin limit info to CLI topics

packages/apps/marmalade-marketplace/src/components/CreateToken/index.tsx, packages/apps/marmalade-marketplace/src/components/MintToken/index.tsx, packages/apps/marmalade-marketplace/src/components/Sale/ConventionalAuction.tsx, packages/apps/marmalade-marketplace/src/components/Sale/DutchAuction.tsx, packages/apps/marmalade-marketplace/src/components/Sale/RegularSale.tsx, packages/apps/marmalade-marketplace/src/pages/sale/[chainId]/[saleId].tsx, packages/libs/client-utils/package.json, packages/libs/client-utils/src/integration-tests/marmalade-conventional-auction.int.test.ts, packages/libs/client-utils/src/integration-tests/marmalade-dutch-auction.int.test.ts, packages/libs/client-utils/src/integration-tests/marmalade-sale.int.test.ts, packages/libs/client-utils/src/marmalade/buy-token.ts, packages/libs/client-utils/src/marmalade/config.ts, packages/libs/client-utils/src/marmalade/helpers.ts, packages/libs/client-utils/src/marmalade/mint-token.ts, packages/libs/client-utils/src/webauthn/get-webauthn-account.ts, packages/libs/client-utils/src/webauthn/get-webauthn-guard.ts, packages/libs/client-utils/src/webauthn/index.ts
- Add `client-utils/webauthn/getWebauthnAccount`
- Change `client-utils/webauthn/getWebauthnGuard` to return the first guard of the devices
- Fix mintToken page 
- Fix createToken page
=> Feat/client utils/webauthn

.changeset/fresh-queens-grow.md, packages/apps/explorer/src/components/account-transfers-table/account-transfers-table.tsx, packages/apps/explorer/src/components/compact-table/compact-table-desktop/field-cell.tsx, packages/apps/explorer/src/components/compact-table/compact-table.tsx, packages/apps/explorer/src/components/compact-table/styles.css.ts, packages/apps/explorer/src/components/loading-skeleton/types.ts, packages/apps/explorer/src/components/routing/useRouter.tsx, packages/apps/explorer/src/components/search/search-results/search-results.tsx
https://app.asana.com/0/1205801361945248/1207810336443347/f
=> fix(explorer): minor fixes

.changeset/witty-melons-pretend.md, packages/apps/explorer/src/components/block-table/block-header/block-header.tsx, packages/apps/explorer/src/components/block-table/block-table.css.ts, packages/apps/explorer/src/components/header/styles.css.ts, packages/apps/explorer/src/components/search/search-component/search-component.css.ts, packages/libs/kode-ui/src/styles/tokens/contract.css.ts, packages/libs/kode-ui/src/styles/tokens/dark.css.ts, packages/libs/kode-ui/src/styles/tokens/light.css.ts, packages/libs/kode-ui/src/styles/tokens/styles.css.ts
https://app.asana.com/0/1205801361945248/1207798334085801/f
=> fix(explorer): transparency of header and blockheader

.changeset/short-items-remain.md, packages/apps/explorer/src/components/account-transfers-table/account-transfers-table.tsx, packages/apps/explorer/src/components/loading-skeleton/loading-data/loading-data-accountquery.ts, packages/apps/explorer/src/components/logo/logo.tsx, packages/apps/explorer/src/components/search/search-component/search-component.css.ts, packages/apps/explorer/src/graphql/queries/account.graph.ts, packages/apps/explorer/src/pages/[networkSlug]/account/[accountName].tsx
https://app.asana.com/0/1205801361945248/1207854090951328/f
=> chore(explorer): remove skelton loader after error

.changeset/warm-tables-retire.md, packages/apps/explorer/src/components/CompactTable/CompactTableDesktop/CompactTableDesktop.tsx, packages/apps/explorer/src/components/Search/SearchResults/SearchResults.tsx, packages/apps/explorer/src/pages/[networkSlug]/account/[accountName].tsx
https://app.asana.com/0/1205801361945248/1207861248265000/f
=> chore(explorer): remove the account balance from the account search result

.changeset/chilly-radios-trade.md, packages/apps/explorer/package.json, packages/apps/explorer/src/components/Analytics/Analytics.tsx, packages/apps/explorer/src/components/CookieConsent/CookieConsent.tsx, packages/apps/explorer/src/components/CookieConsent/styles.css.ts, packages/apps/explorer/src/components/Layout/Layout.tsx, packages/apps/explorer/src/components/Search/SearchComponent/SearchComponent.tsx, packages/apps/explorer/src/components/SelectNetwork/ConfigNetwork.tsx, packages/apps/explorer/src/context/networksContext.tsx, packages/apps/explorer/src/hooks/search/index.ts, packages/apps/explorer/src/pages/_app.tsx, packages/apps/explorer/src/utils/analytics.ts, packages/apps/explorer/tsconfig.json, pnpm-lock.yaml
https://app.asana.com/0/1205801361945248/1207861248331371/f
=> chore(explorer): add analytics

.changeset/shiny-sheep-destroy.md, packages/apps/explorer/src/components/BlockTable/BlockCell/BlockCell.tsx, packages/apps/explorer/src/components/Footer/Footer.tsx, packages/apps/explorer/src/components/Footer/FooterColumn.tsx, packages/apps/explorer/src/components/Footer/FooterLink.tsx, packages/apps/explorer/src/components/GraphqlQueryDialog/GraphqlQueryDialog.tsx, packages/apps/explorer/src/components/SelectNetwork/SelectNetwork.tsx, packages/apps/explorer/src/components/ThemeToggle/ThemeToggle.tsx, packages/apps/explorer/src/utils/analytics.ts
https://app.asana.com/0/1205801361945248/1207861248331388/f
=> chore(explorer): add google analytics for multiple events

packages/apps/marmalade-marketplace/README.md, packages/apps/marmalade-marketplace/src/components/MintToken/index.tsx, packages/apps/marmalade-marketplace/src/components/MintToken/style.css.ts
- Grab tokenId from query params after being redirected from Create Token
=> Mint token improvements

.changeset/hungry-crabs-think.md, packages/libs/kode-ui/src/components/Button/Button.css.ts
=> Button variant and label fixes for different states and breakpoints

.changeset/three-turtles-marry.md, packages/libs/kode-ui/src/components/Form/Form.css.ts, packages/libs/kode-ui/src/components/Form/NumberField/NumberField.tsx, packages/libs/kode-ui/src/components/Form/Select/Select.tsx, packages/libs/kode-ui/src/components/Form/TextField/TextField.tsx, packages/libs/kode-ui/src/components/Form/TextareaField/TextareaField.tsx, packages/libs/kode-ui/src/utils/index.ts, packages/libs/kode-ui/src/utils/useMobile.ts
=> Fix mobile input element typography settings

packages/apps/marmalade-marketplace/src/pages/api/cron.ts
=> Limit the amount of blocks to sync to a maximum of 10

packages/libs/kode-ui/.gitignore, packages/libs/kode-ui/package.json, packages/libs/kode-ui/src/components/Card/Card.tsx, packages/libs/kode-ui/src/entries/patterns.ts, packages/libs/kode-ui/src/patterns/Card/CardContentBlock.tsx, packages/libs/kode-ui/src/patterns/Card/CardFixedContainer.tsx, packages/libs/kode-ui/src/patterns/Card/CardFooterGroup.tsx, packages/libs/kode-ui/src/patterns/Card/CardPattern.css.ts, packages/libs/kode-ui/src/patterns/Card/CardPattern.stories.tsx, packages/libs/kode-ui/src/patterns/Card/index.ts, packages/libs/kode-ui/src/patterns/index.ts, packages/libs/kode-ui/src/storyDecorators/index.ts, packages/libs/kode-ui/src/storyDecorators/withLayerStory.tsx, packages/libs/kode-ui/turbo.json
- Created a new export at `@kadena/kode-ui/patterns` for pattern exports
- Added a Card directory for card layout components with CardFixedContainer, CardContentBlock, and CardFooterGroup
=> Add Card Pattern components

packages/libs/kode-ui/src/components/Tabs/Tabs.css.ts, packages/libs/kode-ui/src/components/Tabs/Tabs.stories.tsx, packages/libs/kode-ui/src/components/Tabs/Tabs.tsx
Updated the styles for the contained tabs
=> Updated styles for contained tabs

.changeset/stupid-cats-occur.md, packages/apps/explorer/src/components/BlockTable/BlockRow/HeightInfo/HeightInfo.tsx, packages/apps/explorer/src/components/BlockTable/BlockRow/HeightInfo/styles.css.ts, packages/apps/explorer/src/components/BlockTable/BlockTable.tsx, packages/apps/explorer/src/components/CompactTable/CompactTable.tsx, packages/apps/explorer/src/components/CompactTable/CompactTableMobile/styles.css.ts, packages/apps/explorer/src/components/CookieConsent/styles.css.ts, packages/apps/explorer/src/components/DataRenderComponent/DataRenderComponentHorizontal/styles.css.ts, packages/apps/explorer/src/components/LoadingSkeleton/style.css.ts, packages/apps/explorer/src/components/Search/SearchComponent/SearchComponent.tsx, packages/apps/explorer/src/components/Search/SearchComponent/searchComponent.css.ts, packages/apps/explorer/src/hooks/__tests__/useIphoneInputFix.test.ts, packages/apps/explorer/src/hooks/useIphoneInputFix.ts, packages/apps/explorer/src/pages/[networkSlug]/account/[accountName].tsx, packages/apps/explorer/src/pages/[networkSlug]/block/[hash].tsx, packages/apps/explorer/src/pages/[networkSlug]/transaction/[requestKey].tsx, packages/apps/explorer/src/pages/_app.tsx
---
- https://app.asana.com/0/0/1208103322518356
=> fix(explorer): ios styling fixes

.changeset/great-bananas-prove.md, packages/apps/explorer/src/components/BlockTable/BlockTable.tsx, packages/apps/explorer/src/components/DataRenderComponent/DataRenderComponentVertical/styles.css.ts, packages/apps/explorer/src/components/Footer/FooterColumn.tsx, packages/apps/explorer/src/components/TransactionComponents/TransactionResultComponent.tsx, packages/apps/explorer/src/components/globalstyles.css.ts, packages/apps/explorer/src/constants/constants.ts, packages/apps/explorer/src/pages/[networkSlug]/transaction/[requestKey].tsx
---
- https://app.asana.com/0/0/1205842872749419
=> feat(explorer): able to finish crosschain transfer

.changeset/silent-ladybugs-dream.md, packages/apps/explorer/src/pages/[networkSlug]/account/[accountName].tsx, packages/apps/explorer/src/pages/[networkSlug]/block/[hash].tsx
---
- https://app.asana.com/0/0/1208132439799227
=> feat(explorer): style the block hash page

.changeset/slow-windows-suffer.md, packages/libs/kode-ui/src/styles/global.css.ts, packages/libs/kode-ui/src/styles/tokens/contract.css.ts, packages/libs/kode-ui/src/styles/tokens/dark.css.ts, packages/libs/kode-ui/src/styles/tokens/light.css.ts, packages/libs/kode-ui/src/styles/vars.css.ts
Updated the primary and secondary fonts to Inter and synced design-system tokens
projects)
=> Update primaryFont and secondaryFont to Inter

.changeset/early-moons-thank.md, .changeset/slow-windows-suffer.md, packages/libs/kode-ui/src/patterns/Card/CardFixedContainer.tsx, packages/libs/kode-ui/src/patterns/Card/CardPattern.css.ts, packages/libs/kode-ui/src/styles/global.css.ts, packages/libs/kode-ui/src/styles/tokens/contract.css.ts, packages/libs/kode-ui/src/styles/tokens/dark.css.ts, packages/libs/kode-ui/src/styles/tokens/light.css.ts, packages/libs/kode-ui/src/styles/vars.css.ts
- Updated the header sizes when multiple `CardContentBlocks` are stacked
- Updated the mobile styles to be full width without a border-radius
projects)
=> Fix: Card Pattern styles

.changeset/late-emus-sell.md, packages/apps/explorer/src/components/EventFilter/utils/__tests__/validation.test.ts, packages/apps/explorer/src/components/EventFilter/utils/validation.ts, packages/apps/explorer/src/hooks/events/utils/__tests__/createArrayOfChains.test.ts, packages/apps/explorer/src/hooks/events/utils/createArrayOfChains.ts
---
- https://app.asana.com/0/0/1208157547619532
=> feat(explorer): filter events chains with range

packages/apps/docs/src/docs/deploy/chainweb/compact-a-database.md
@chessai This is a preliminary rough draft. I haven't been able to try it myself yet (no Ubuntu instance yet and I hit issues trying to use Virtual Box on my personal laptop).
-- Update: I was able to get a Ubuntu instance up, so this should be close.
Related Issue/Asana ticket: https://app.asana.com/0/1204132908184958/1206176093727384
projects)
---
- https://app.asana.com/0/0/1208003575589463
=> Update the compact tool information

.github/workflows/ci.yml
This reverts commit 7b82716fc05abbe33a9dab2ddc187355ac114166.
=> Reapply "chore(monorepo): make sure only lsgunnlsgunn gets auto-approved"

.changeset/cuddly-plants-itch.md, packages/libs/kode-ui/src/components/ContentHeader/ContentHeader.stories.tsx, packages/libs/kode-ui/src/components/ContentHeader/ContentHeader.tsx
=> Feature to add components in the description

packages/apps/docs/src/docs/build/pact/concepts.md
Replacement for https://github.com/kadena-community/kadena.js/pull/1661
projects)
=> Move verifiers and capabilities into a fresh PR

.changeset/ninety-emus-arrive.md, packages/apps/explorer/src/components/SelectNetwork/ConfigNetwork.tsx
---
- https://app.asana.com/0/0/1208270289158325
=> fix(explorer): adding a network 

packages/apps/docs/src/config.yaml, packages/apps/docs/src/docs/reference/kadena-client/built-in-utils.md, packages/apps/docs/src/docs/reference/kadena-client/client-utils.md, packages/apps/docs/src/docs/reference/kadena-client/core-utils.md
Replacing https://github.com/kadena-community/kadena.js/pull/2275 which is failing on preview deployment because of redirect issues with PRs that got merged to main.
@javadkh2 if you can add code samples to this branch, that would be awesome. If you prefer to work in a separate branch, that's fine too. The older PR was just getting stale.
projects)
=> Move updates from failing PR to a fresh PR

packages/apps/docs/src/components/BottomPageSection/BottomPageSection.tsx, packages/apps/docs/src/components/DocsCard/styles.css.ts, packages/apps/docs/src/components/Layout/Full/Full.tsx
Reverts kadena-community/kadena.js#2504
=> Revert "Simplify bottom section, remove second Edit button, change blue to ne…"

.changeset/eighty-dragons-move.md, packages/libs/kode-ui/src/components/Tabs/Tabs.css.ts
---
- https://app.asana.com/0/0/1208367203543849
=> fix(ui): fix the coloor the selected tab border

.changeset/short-glasses-watch.md
=> release(kadena-snap): version bump for re-release

packages/apps/dev-wallet/src/pages/import-wallet/import-wallet.tsx
---
- https://app.asana.com/0/0/1208399472976582
=> fix(dev-wallet): recovery mnemonic field uses type password to not leak auto-fill

packages/apps/dev-wallet/src/App/BetaHeader.tsx, packages/apps/dev-wallet/src/App/app.tsx
---
- https://app.asana.com/0/0/1208304443209155
=> feat(dev-wallet): adds header warning

.changeset/sweet-windows-tell.md, packages/libs/client/src/client/utils/tests/utils.test.ts, packages/libs/client/src/client/utils/utils.ts
=> feat(client): add support for testnet05

packages/apps/dev-wallet/src/App/routes.tsx, packages/apps/dev-wallet/src/modules/db/db.service.tsx, packages/apps/dev-wallet/src/modules/db/indexeddb.ts, packages/apps/dev-wallet/src/modules/key-source/hd-wallet/BIP44.ts, packages/apps/dev-wallet/src/modules/key-source/hd-wallet/chainweaver.ts, packages/apps/dev-wallet/src/modules/key-source/key-source.repository.ts, packages/apps/dev-wallet/src/modules/wallet/wallet.hook.tsx, packages/apps/dev-wallet/src/modules/wallet/wallet.provider.tsx, packages/apps/dev-wallet/src/modules/wallet/wallet.repository.ts, packages/apps/dev-wallet/src/modules/wallet/wallet.service.ts, packages/apps/dev-wallet/src/pages/home/home-page.tsx
=> feat(dev-wallet): sort everything bases on creation time

.changeset/chatty-papayas-hear.md, packages/apps/explorer/src/components/SelectNetwork/ConfigNetwork.tsx
---
- https://app.asana.com/0/0/1208547620916068
=> chore(explorer): fix the editting of networks

.changeset/gold-fireants-swim.md, packages/apps/explorer/src/components/Search/SearchComponent/SearchComponent.tsx, packages/apps/explorer/src/context/searchContext/index.tsx
---
- https://app.asana.com/0/0/1208527412877289
=> fix(explorer): trim the input value of search

.changeset/new-roses-pretend.md, packages/apps/tools/src/components/Global/ModuleExplorer/editor.tsx
=> tools statusbar repositioning

packages/apps/dev-wallet/src/modules/network/network.repository.ts, packages/apps/tools/src/constants/kadena.ts, packages/libs/client/src/client/utils/tests/utils.test.ts, packages/libs/client/src/client/utils/utils.ts
=> feat: testnet05 host url

packages/apps/dev-wallet/src/config.ts, packages/apps/dev-wallet/src/modules/db/db.service.tsx
=> chore(dw): bump db version

.changeset/olive-pigs-rhyme.md, packages/tools/kadena-cli/package.json, packages/tools/kadena-cli/src/commands/tx/utils/txHelpers.ts, packages/tools/kadena-cli/src/services/config/config.service.ts, packages/tools/kadena-cli/src/utils/globalHelpers.ts
=> fix(kadena-cli): malformed json in txsend fixed, now also accepts yml

packages/apps/dev-wallet/src/App/Layout/BreadCrumbs.tsx, packages/apps/dev-wallet/src/App/Layout/Layout.tsx
=> fix(dw): breadcrumbs icon

packages/libs/wallet-sdk/README.md
docs for hd-wallet key signing
=> feat(wallet-sdk): documentation for key gen

packages/apps/dev-wallet/src/modules/wallet/wallet.hook.tsx, packages/apps/dev-wallet/src/pages/account/Components/AliasForm.tsx, packages/apps/dev-wallet/src/pages/account/account.tsx
=> feat(dw): accounts default alias + edit alias form

packages/apps/dev-wallet/src/modules/transaction/transaction.service.ts, packages/apps/dev-wallet/src/pages/signature-builder/signature-builder.tsx, packages/apps/dev-wallet/src/pages/transaction/components/ExpandedTransaction.tsx, packages/apps/dev-wallet/src/pages/transaction/components/Signers.tsx, packages/apps/dev-wallet/src/pages/transaction/components/TxPipeLine.tsx, packages/apps/dev-wallet/src/utils/webAuthn.ts
=> feat(dw): transaction sharing

packages/apps/dev-wallet/src/App/BetaHeader.tsx, packages/apps/dev-wallet/src/App/Layout/Layout.tsx, packages/apps/dev-wallet/src/App/Layout/SideBar.tsx, packages/apps/dev-wallet/src/App/Layout/style.css.ts, packages/apps/dev-wallet/src/Components/AccountItem/AccountItem.tsx, packages/apps/dev-wallet/src/Components/AssetsCard/AssetsCard.tsx, packages/apps/dev-wallet/src/Components/AuthCard/AuthCard.tsx, packages/apps/dev-wallet/src/pages/contacts/Components/ContactForm.tsx, packages/apps/dev-wallet/src/pages/contacts/contacts.tsx, packages/apps/dev-wallet/src/pages/home/home-page.tsx, packages/apps/dev-wallet/src/pages/select-profile/initials.tsx, packages/apps/dev-wallet/src/pages/select-profile/select-profile.css.ts, packages/apps/dev-wallet/src/pages/select-profile/select-profile.tsx, packages/apps/dev-wallet/src/pages/transaction/components/CommandView.tsx, packages/apps/dev-wallet/src/pages/transactions/style.css.ts, packages/apps/dev-wallet/src/pages/unlock-profile/styles.css.ts, packages/apps/dev-wallet/src/pages/unlock-profile/unlock-profile.tsx, packages/apps/dev-wallet/src/utils/get-initials.ts
=> feat(dw): some improvement

packages/apps/docs/src/docs/learn/accounts-keys.md
Title
Fix Grammar in Documentation: Update 'the primary different' -> 'the primary difference'.
Related Issue/Asana Ticket
N/A
Short Description
This pull request corrects minor grammar in the documentation, changing 'of one public' to 'of one or more public.'
Test Scenarios
Visual inspection of the documentation to confirm grammar changes.
=> Minor Grammar Correction In Docs (2)

packages/apps/dev-wallet/src/pages/create-account/create-account.tsx
=> fix(dw): account creation

packages/apps/tools/src/components/Partials/transactions/transfer/sender-details.tsx, packages/apps/tools/src/components/Partials/transactions/utils/balance.ts, packages/apps/tools/src/hooks/use-account-chain-details-query.ts, packages/apps/tools/src/hooks/use-account-details-query.ts
---
- https://app.asana.com/0/0/1208864336730682
=> fix(tools): use type `balance: number | { decimal: string }` in sending funds

packages/libs/client-utils/src/scripts/deploy-faucet/deploy-faucet.ts
=> fix(faucet): deploy script - removed contract code from the logged data

.changeset/polite-bats-call.md, packages/libs/client/src/composePactCommand/composePactCommand.ts
=> feat(client): add default value of  for proof

packages/apps/dev-wallet/src/config.ts, packages/apps/dev-wallet/src/modules/db/db-channel.ts, packages/apps/dev-wallet/src/modules/db/db.service.tsx, packages/apps/dev-wallet/src/modules/db/migration/migrateFrom39to40.ts, packages/apps/dev-wallet/src/modules/db/migration/migration.ts
=> fix(dw): migarte db to 40

packages/libs/hd-wallet/README.md
added updated docs for hd-wallet to align with wallet-sdk
=> hd-wallet  - cleanup docs to match wallet-sdk

packages/apps/dev-wallet/src/pages/networks/Components/NetworkForm.tsx, packages/apps/dev-wallet/src/pages/networks/networks.tsx, packages/apps/dev-wallet/src/pages/settings/settings.tsx
=> feat(dw): enable network toggle

packages/apps/dev-wallet/src/Components/ComboField/ComboField.tsx, packages/apps/dev-wallet/src/Components/NetworkSelector/NetworkSelector.tsx, packages/apps/dev-wallet/src/modules/account/account.service.ts, packages/apps/dev-wallet/src/modules/network/network.service.ts, packages/apps/dev-wallet/src/modules/wallet/wallet.provider.tsx, packages/apps/dev-wallet/src/pages/account/account.tsx, packages/apps/dev-wallet/src/pages/networks/Components/NetworkForm.tsx, packages/apps/dev-wallet/src/pages/networks/networks.tsx, packages/apps/dev-wallet/src/pages/transfer/Components/AccountSearchBox.tsx
search box issue 
disable sync account when offline  
network status
=> fix(dw): search box issue + sync account when offline + network staus

packages/apps/rwa-demo/src/components/BadgeFeezeForm/BadgeFeezeForm.tsx, packages/apps/rwa-demo/src/components/InvestorList/InvestorList.tsx, packages/apps/rwa-demo/src/components/TableFormatters/FormatCheckbox.tsx, packages/apps/rwa-demo/src/components/TransactionsProvider/TransactionsProvider.tsx, packages/apps/rwa-demo/src/hooks/batchFreezeInvestors.ts, packages/apps/rwa-demo/src/services/batchSetAddressFrozen.ts
---
- https://app.asana.com/0/0/1208927009746686
=> feat(rwa): batch freeze unfreeze investors

packages/apps/rwa-demo/src/hooks/getInvestorBalance.ts
---
- https://app.asana.com/0/0/1209022297873724
=> feat(rwa): update the investorbalance by graphql subscription

packages/apps/rwa-demo/src/components/AccountProvider/AccountProvider.tsx, packages/apps/rwa-demo/src/hooks/addInvestor.ts, packages/apps/rwa-demo/src/hooks/batchAddInvestors.ts, packages/apps/rwa-demo/src/hooks/deleteInvestor.ts, packages/apps/rwa-demo/src/hooks/distributeTokens.ts, packages/apps/rwa-demo/src/hooks/getAgentRoles.ts, packages/apps/rwa-demo/src/hooks/removeAgent.ts, packages/apps/rwa-demo/src/hooks/setCompliance.ts, packages/apps/rwa-demo/src/services/addAgent.ts, packages/apps/rwa-demo/src/services/getAgentRoles.ts, packages/apps/rwa-demo/src/services/pact/modelcontract.ts, packages/apps/rwa-demo/src/services/setCompliance.ts
---
- https://app.asana.com/0/0/1209123711287592
=> chore(rwa): change the agent roles for contract

packages/apps/rwa-demo/src/app/(app)/page.tsx, packages/apps/rwa-demo/src/app/(app)/styles.css.ts, packages/apps/rwa-demo/src/components/AssetAction/AssetAction.tsx, packages/apps/rwa-demo/src/components/AssetAction/style.css.ts, packages/apps/rwa-demo/src/components/BatchTransferAsset/BatchTransferAssetAction.tsx, packages/apps/rwa-demo/src/components/BatchTransferAsset/BatchTransferAssetForm.tsx, packages/apps/rwa-demo/src/hooks/batchTransferTokens.ts, packages/apps/rwa-demo/src/hooks/getInvestorBalance.ts, packages/apps/rwa-demo/src/services/batchRegisterIdentity.ts, packages/apps/rwa-demo/src/services/batchSetAddressFrozen.ts, packages/apps/rwa-demo/src/services/batchTransferTokens.ts, packages/apps/rwa-demo/src/services/deleteIdentity.ts, packages/apps/rwa-demo/src/services/distributeTokens.ts, packages/apps/rwa-demo/src/services/editAgent.ts, packages/apps/rwa-demo/src/services/forcedTransferTokens.ts, packages/apps/rwa-demo/src/services/registerIdentity.ts, packages/apps/rwa-demo/src/services/setAddressFrozen.ts, packages/apps/rwa-demo/src/services/togglePartiallyFreezeTokens.ts, packages/apps/rwa-demo/src/services/togglePause.ts, packages/apps/rwa-demo/src/utils/__tests__/getAggregatedAccounts.test.ts, packages/apps/rwa-demo/src/utils/getAggregatedAccounts.ts
---
- https://app.asana.com/0/0/1209088708938530
=> feat(rwa): batch transfer for investor

packages/apps/rwa-demo/package.json, packages/apps/rwa-demo/src/app/(app)/page.tsx, packages/apps/rwa-demo/src/components/AssetProvider/AssetProvider.tsx, packages/apps/rwa-demo/src/components/ComplianceRule/ComplianceRule.tsx, packages/apps/rwa-demo/src/components/Confirmation/Confirmation.tsx, packages/apps/rwa-demo/src/components/Confirmation/style.css.ts, packages/apps/rwa-demo/src/components/DistributionForm/DistributionForm.tsx, packages/apps/rwa-demo/src/components/InvestorBalance/MaxInvestorBalanceCheck.tsx, packages/apps/rwa-demo/src/components/MaxSupplyMessage/MaxSupplyMessage.tsx, packages/apps/rwa-demo/src/components/SetComplianceForm/SetComplianceForm.tsx, packages/apps/rwa-demo/src/components/SupplyCountContractDetails/SupplyCountContractDetails.tsx, packages/apps/rwa-demo/src/components/TransactionsProvider/TransactionsProvider.tsx, packages/apps/rwa-demo/src/hooks/distributeTokens.ts, packages/apps/rwa-demo/src/hooks/getComplianceRules.ts, packages/apps/rwa-demo/src/hooks/setCompliance.ts, packages/apps/rwa-demo/src/services/getComplianceRules.ts, packages/apps/rwa-demo/src/services/isOwner.ts, packages/apps/rwa-demo/src/services/pact/modelcontract.ts, packages/apps/rwa-demo/src/services/setCompliance.ts, packages/apps/rwa-demo/src/services/setComplianceParameters.ts, packages/apps/rwa-demo/src/utils/__tests__/getActiveRulesKeys.test.ts, packages/apps/rwa-demo/src/utils/getActiveRulesKeys.ts, packages/apps/rwa-demo/tsconfig.json
---
- https://app.asana.com/0/0/1209088708938501
- https://app.asana.com/0/0/1209088708938548
- https://app.asana.com/0/0/1208937638168685
=> feat(rwa): fix compliance rules

packages/apps/dev-wallet/src/App/routes.tsx, packages/apps/dev-wallet/src/Components/UnlockPrompt/UnlockPrompt.tsx, packages/apps/dev-wallet/src/modules/security/fallback.service.ts, packages/apps/dev-wallet/src/modules/wallet/wallet.hook.tsx, packages/apps/dev-wallet/src/modules/wallet/wallet.provider.tsx, packages/apps/dev-wallet/src/modules/wallet/wallet.repository.ts, packages/apps/dev-wallet/src/pages/select-profile/select-profile.tsx, packages/apps/dev-wallet/src/pages/settings/keep-password-policy/keep-password-policy.tsx, packages/apps/dev-wallet/src/pages/settings/settings.tsx, packages/apps/dev-wallet/src/pages/transaction/components/TxTile.tsx, packages/apps/dev-wallet/src/pages/unlock-profile/unlock-profile.tsx, packages/apps/dev-wallet/src/service-worker/types.ts, packages/apps/dev-wallet/src/utils/session.ts
=> feat(dw): keep policy

packages/apps/rwa-demo/src/app/(loggedout)/assets/create/page.tsx, packages/apps/rwa-demo/src/components/AccountProvider/AccountProvider.tsx, packages/apps/rwa-demo/src/components/Confirmation/style.css.ts, packages/apps/rwa-demo/src/components/FreezeInvestor/FreezeInvestor.tsx
when not logged in a faulty redirect fix
=> fix(rwa): misc bugfixes

packages/apps/dev-wallet/src/modules/transaction/transaction.service.ts, packages/apps/dev-wallet/src/pages/signature-builder/signature-builder.tsx
=> fix(dw): safe

packages/apps/dev-wallet/src/config.ts, packages/apps/dev-wallet/src/modules/account/account.service.ts, packages/apps/dev-wallet/src/modules/key-source/key-source-manager.ts, packages/apps/dev-wallet/src/pages/account-discovery/account-dsicovery.tsx, packages/apps/dev-wallet/src/pages/keys/Components/Keys.tsx, packages/apps/dev-wallet/src/pages/wallet-recovery/recover-from-mnemonic/recover-from-mnemonic.tsx, packages/apps/dev-wallet/src/pages/wallet-recovery/recover-from-mnemonic/utils.ts
=> fix(dw): mainnet rate limit

packages/apps/rwa-demo/src/app/(app)/assets/page.tsx, packages/apps/rwa-demo/src/components/AccountProvider/utils.ts, packages/apps/rwa-demo/src/components/AssetForm/AssetStepperForm.tsx, packages/apps/rwa-demo/src/hooks/__tests__/addInvestor.test.ts, packages/apps/rwa-demo/src/hooks/__tests__/batchAddInvestors.test.ts, packages/apps/rwa-demo/src/hooks/__tests__/batchFreezeInvestors.test.ts, packages/apps/rwa-demo/src/hooks/__tests__/batchTransferTokens.test.ts, packages/apps/rwa-demo/src/hooks/__tests__/createContract.test.ts, packages/apps/rwa-demo/src/hooks/__tests__/deleteInvestor.test.ts, packages/apps/rwa-demo/src/hooks/__tests__/distributeTokens.test.ts, packages/apps/rwa-demo/src/hooks/__tests__/editAgent.test.ts, packages/apps/rwa-demo/src/hooks/__tests__/forcedTransferTokens.test.ts, packages/apps/rwa-demo/src/hooks/__tests__/freezeInvestor.test.ts, packages/apps/rwa-demo/src/hooks/__tests__/removeAgent.test.ts, packages/apps/rwa-demo/src/hooks/__tests__/setCompliance.test.ts, packages/apps/rwa-demo/src/hooks/addInvestor.ts, packages/apps/rwa-demo/src/hooks/createContract.ts, packages/apps/rwa-demo/src/hooks/deleteInvestor.ts, packages/apps/rwa-demo/src/hooks/distributeTokens.ts, packages/apps/rwa-demo/src/hooks/removeAgent.ts, packages/apps/rwa-demo/src/services/batchRegisterIdentity.ts, packages/apps/rwa-demo/src/services/deleteIdentity.ts, packages/apps/rwa-demo/src/services/editAgent.ts, packages/apps/rwa-demo/src/services/registerIdentity.ts, packages/apps/rwa-demo/src/services/setComplianceParameters.ts
---
- https://app.asana.com/0/0/1209123711287584
=> chore(rwa): add hook unit tests

packages/apps/rwa-demo/src/hooks/getAgentRoles.ts
---
- https://app.asana.com/0/0/1209168000490129
- https://app.asana.com/0/0/1209088708938548
=> fix(rwa): updating roles in realtime

packages/apps/dev-wallet/src/pages/transfer/Steps/TransferForm.tsx, packages/apps/dev-wallet/src/pages/transfer/utils.ts
=> feat(dw): add support for normal xchain

packages/apps/dev-wallet/src/Components/AccountBalanceDistribution/AccountBalanceDistribution.tsx, packages/apps/dev-wallet/src/Components/FundOnTestnet/FundOnTestnet.tsx, packages/apps/dev-wallet/src/pages/account/account.tsx, packages/apps/dev-wallet/src/pages/transfer/Components/AccountSearchBox.tsx, packages/apps/dev-wallet/src/pages/transfer/utils.ts
=> feat(dw): disabling redistribution btn + share w:accounts

packages/apps/dev-wallet/src/modules/account/account.service.ts, packages/apps/dev-wallet/src/modules/db/backup/backup.ts, packages/apps/dev-wallet/src/modules/network/network.repository.ts, packages/apps/dev-wallet/src/pages/account-discovery/account-dsicovery.tsx
=> fix(dw): changed default network to mainnet and fixed save accounts

packages/apps/tools/package.json, packages/apps/tools/src/scripts/graphCron/index.ts, packages/apps/tools/src/scripts/graphCron/messages.ts, pnpm-lock.yaml
This reverts commit d65837036f685ebf08e25ebfb69112608b8da46e.
=> Revert "chore(graphCron): use rich_text"

packages/apps/dev-wallet/src/pages/account-discovery/account-dsicovery.tsx, packages/apps/dev-wallet/src/pages/wallet-recovery/recover-from-mnemonic/recover-from-mnemonic.tsx
=> fix(dw): change recover texts

packages/apps/dev-wallet/src/Components/Accounts/Accounts.tsx, packages/e2e/e2e-base/src/page-objects/chainweaver/chainweaverApp.index.ts, packages/e2e/e2e-dev-wallet/tests/createAccount.spec.ts, packages/e2e/e2e-dev-wallet/tests/network.spec.ts, packages/e2e/e2e-dev-wallet/tests/profile.spec.ts
---
- https://app.asana.com/0/0/1209281002574592
=> chore(e2e): create account in wallet

packages/apps/dev-wallet/src/Components/ConfirmDeletion/ConfirmDeletion.tsx, packages/apps/dev-wallet/src/modules/network/network.repository.ts, packages/apps/dev-wallet/src/modules/wallet/wallet.provider.tsx, packages/apps/dev-wallet/src/pages/account/account.tsx, packages/apps/dev-wallet/src/pages/networks/Components/NetworkForm.tsx, packages/apps/dev-wallet/src/pages/networks/networks.tsx, packages/apps/dev-wallet/src/pages/transaction/Transaction.tsx, packages/apps/dev-wallet/src/pages/transaction/components/TxPipeLine.tsx, packages/apps/dev-wallet/src/pages/transaction/components/TxTile.tsx
=> Fix some bugs + delete network option

packages/apps/dev-wallet/src/e2e.ts, packages/apps/dev-wallet/src/index.ts, packages/apps/dev-wallet/src/modules/db/backup/backup.ts, packages/apps/dev-wallet/src/modules/db/migration/createDB.ts, packages/apps/dev-wallet/src/modules/db/migration/migrateFrom40to41.ts, packages/apps/dev-wallet/src/modules/db/migration/migrateFrom45to46.ts, packages/apps/dev-wallet/src/modules/transaction/transaction.service.ts, packages/apps/dev-wallet/src/modules/wallet/wallet.hook.tsx, packages/apps/dev-wallet/src/pages/account/account.tsx, packages/apps/dev-wallet/src/pages/transaction/components/code-components/CodeView.tsx, packages/apps/dev-wallet/vite.config.ts
=> Fix/cont and backup dp + e2e 

packages/apps/dev-wallet/src/App/routes.tsx, packages/apps/dev-wallet/src/Components/Accounts/Accounts.tsx, packages/apps/dev-wallet/src/Components/Accounts/MultiSigForm.tsx, packages/apps/dev-wallet/src/Components/Accounts/WatchAccountForm.tsx, packages/apps/dev-wallet/src/Components/ComboField/ComboField.tsx, packages/apps/dev-wallet/src/Components/Guard/keyset.tsx, packages/apps/dev-wallet/src/Components/KeySearchBox/KeySearchBox.tsx, packages/apps/dev-wallet/src/Components/KeySetForm/KeySetForm.tsx, packages/apps/dev-wallet/src/pages/create-account/create-account.tsx
=> feat(dw): add create account aside

packages/apps/dev-wallet/src/modules/transaction/transaction.service.ts
=> fix(dw): add pact5 support

packages/apps/dev-wallet/src/pages/signature-builder/signature-builder.tsx
=> fix(dw): update signatures

packages/apps/dev-wallet/src/modules/transaction/transaction.service.ts, packages/apps/graph/src/services/chainweb-node/fungible-account-details.ts, packages/apps/graph/src/services/chainweb-node/non-fungible-account-details.ts, packages/apps/graph/src/utils/errors.ts, packages/apps/tools/src/services/cross-chain-transfer-finish/get-transfer-data.ts, packages/libs/chainweb-node-client/etc/chainweb-node-client.api.md, packages/libs/chainweb-node-client/src/interfaces/PactAPI.ts, packages/libs/client-utils/src/scripts/deploy-faucet/testnet-faucet.pact, packages/libs/client/etc/client.api.md, packages/libs/client/src/index.ts, packages/libs/client/src/utils/getPactErrorCode.ts, packages/libs/client/src/utils/tests/getPactErrorCode.test.ts, packages/tools/kadena-cli/src/commands/account/commands/accountDetails.ts, packages/tools/kadena-cli/src/commands/account/utils/getAccountDetails.ts, packages/tools/kadena-cli/src/utils/chainHelpers.ts
=> fix: get pact error code function

packages/apps/dev-wallet/src/Components/Guard/KeySelector.tsx, packages/apps/dev-wallet/src/Components/Guard/keyset.tsx, packages/apps/dev-wallet/src/modules/transaction/transaction.service.ts, packages/apps/dev-wallet/src/pages/account/account.tsx, packages/apps/dev-wallet/src/pages/transfer/Steps/TransferForm.tsx, packages/apps/dev-wallet/src/service-worker/service-worker.ts, packages/apps/dev-wallet/src/utils/getErrorMessage.ts
=> feat(dw): transfer page imporvment

packages/apps/dev-wallet/src/utils/chainweaver/chainweaver.d.ts, packages/apps/dev-wallet/src/utils/chainweaver/convertFromChainweaver.ts, packages/apps/dev-wallet/src/utils/chainweaver/validateStructure.ts
=> fix(dw): import form legacy chainweaver

.changeset/clean-mice-give.md
=> chore: changeset

packages/apps/rwa-demo/src/components/SetComplianceForm/SetComplianceForm.tsx, packages/apps/rwa-demo/src/hooks/setCompliance.ts, packages/apps/rwa-demo/src/utils/__tests__/setComplianceValue.test.ts, packages/apps/rwa-demo/src/utils/setComplianceValue.ts
---
- https://app.asana.com/0/0/1209454409349878
=> fix(rwa): the showing of the unlimited compliance rules

.changeset/warm-weeks-wash.md, packages/apps/dev-wallet/src/Components/Assets/AddTokenForm.tsx, packages/apps/dev-wallet/src/Components/UnlockPrompt/UnlockPrompt.tsx, packages/apps/dev-wallet/src/pages/create-profile/create-profile.tsx, packages/apps/dev-wallet/src/pages/networks/Components/NetworkForm.tsx, packages/apps/dev-wallet/src/pages/settings/change-password/change-password.tsx, packages/apps/dev-wallet/src/pages/settings/components/ProfileNameColorForm.tsx, packages/apps/dev-wallet/src/pages/signature-builder/signature-builder.tsx, packages/apps/dev-wallet/src/pages/unlock-profile/unlock-profile.tsx
---
- https://app.asana.com/0/0/1209596082425418
=> fix(wallet): autofocus first field in forms

packages/apps/dev-wallet/src/pages/create-profile/create-profile.tsx, packages/apps/dev-wallet/src/pages/settings/components/ProfileNameColorForm.tsx
---
- https://app.asana.com/0/0/1209665917222962
=> fix(wallet): profilename validation

packages/apps/dev-wallet/src/pages/keys/Components/AddSpecificKey.tsx, packages/apps/dev-wallet/src/pages/keys/Components/Keys.tsx
---
- https://app.asana.com/0/0/1210021219498289
=> fix(wallet): just show the 1 selected keyset form

packages/apps/dev-wallet/src/pages/create-profile/create-profile.tsx, packages/apps/dev-wallet/src/pages/create-profile/styles.css.ts
issue:
when I wanted to create an account it would not save the password.
fix:
the password field was not rendered at the moment the form was submitted.
therefor the password was undefined.
this PR just hides the password field
=> fix(wallet) creating new profiles password

packages/apps/dev-wallet/src/pages/transaction/components/Capability.tsx, packages/apps/dev-wallet/src/pages/transaction/components/TxPipeLine/index.tsx
---
- https://app.asana.com/0/0/1210134853140001
- https://app.asana.com/0/0/1210135125970204
=> chore(wallet): spelling mistakes and wording

packages/apps/dev-wallet/src/pages/transfer/Steps/TransferForm/components/ReceiverCard.tsx, packages/apps/dev-wallet/src/pages/transfer/Steps/TransferForm/components/SenderCard.tsx
---
- https://app.asana.com/0/0/1210134851486105
=> fix(wallet): add labels to tx form fields

packages/apps/dev-wallet/src/Components/PasswordField/PasswordField.tsx, packages/apps/dev-wallet/src/pages/create-profile/create-profile.tsx, packages/apps/dev-wallet/src/utils/createDefaultProfileName.ts
---
- https://app.asana.com/0/0/1210135093373349
=> fix(wallet): the default profilename

packages/apps/dev-wallet/src/Components/NetworkSelector/NetworkSelector.tsx, packages/apps/dev-wallet/src/pages/networks/networks.tsx, packages/libs/kode-ui/src/components/Button/Button.css.ts, packages/libs/kode-ui/src/components/Button/Button.stories.tsx, packages/libs/kode-ui/src/components/Button/Button.tsx
---
- https://app.asana.com/0/0/1210134922059436
=> fix(wallet): fix the buttonlabel when not clickable

.github/labeler.yml, packages/apps/wallet-adapter-react-example/src/main.tsx, packages/libs/wallet-adapter-ecko/etc/wallet-adapter-ecko.api.md, packages/libs/wallet-adapter-ecko/src/EckoAdapter.ts, packages/libs/wallet-adapter-ecko/src/__tests__/eckoAdapterFactory.test.ts, packages/libs/wallet-adapter-ecko/src/__tests__/eckoWalletAdapter.test.ts, packages/libs/wallet-adapter-ecko/src/eckoAdapterFactory.ts, packages/libs/wallet-adapter-ecko/src/index.ts
=> fix(wallet-adapter-ecko): update naming to be more consistent

packages/apps/rwa-demo/src/components/Fields/AccountNameField.tsx, packages/apps/rwa-demo/src/components/InvestorBatchForm/InvestorBatchForm.tsx, packages/apps/rwa-demo/src/hooks/__tests__/faucet.test.ts, packages/apps/rwa-demo/src/hooks/addInvestor.ts, packages/apps/rwa-demo/src/hooks/batchAddInvestors.ts, packages/apps/rwa-demo/src/hooks/batchFreezeInvestors.ts, packages/apps/rwa-demo/src/hooks/batchTransferTokens.ts, packages/apps/rwa-demo/src/hooks/deleteInvestor.ts, packages/apps/rwa-demo/src/hooks/distributeTokens.ts, packages/apps/rwa-demo/src/hooks/editAgent.ts, packages/apps/rwa-demo/src/hooks/faucet.ts, packages/apps/rwa-demo/src/hooks/forcedTransferTokens.ts, packages/apps/rwa-demo/src/hooks/freezeInvestor.ts, packages/apps/rwa-demo/src/hooks/removeAgent.ts, packages/apps/rwa-demo/src/hooks/setCompliance.ts, packages/apps/rwa-demo/src/hooks/togglePartiallyFreezeTokens.ts, packages/apps/rwa-demo/src/hooks/togglePause.ts, packages/apps/rwa-demo/src/hooks/transferTokens.ts, packages/apps/rwa-demo/src/hooks/useSubmit2Chain.ts
---
- https://app.asana.com/0/0/1210590686175460
=> chore(rwa): refactor the submit 2 chain hooks

packages/apps/rwa-demo/src/app/api/origin/__tests__/route.test.ts, packages/apps/rwa-demo/src/app/api/origin/route.ts, packages/apps/rwa-demo/src/components/admin/OrganisationInfoForm/OrganisationFormFields.tsx, packages/apps/rwa-demo/src/components/admin/OrganisationInfoForm/OrganisationInfoForm.tsx, packages/apps/rwa-demo/src/components/admin/OrganisationsList/OrganisationsList.tsx, packages/apps/rwa-demo/src/hooks/__tests__/notifications.test.ts, packages/apps/rwa-demo/src/hooks/notifications.ts, packages/apps/rwa-demo/src/providers/OrganisationProvider/OrganisationProvider.tsx, packages/apps/rwa-demo/src/utils/analytics.ts, packages/apps/rwa-demo/src/utils/store/__tests__/rootAdminStore.test.ts, packages/apps/rwa-demo/src/utils/store/rootAdminStore.ts
---
- https://app.asana.com/0/0/1210611745165909
=> feat(rwa): add option to add more organisations

packages/apps/rwa-demo/src/components/TableFormatters/FormatAccount.tsx
---
- https://app.asana.com/0/0/1210648178810357
=> feat(rwa): add owner badge to account lists

packages/apps/dev-wallet/src/pages/transaction/components/ExpandedTransaction/index.tsx, packages/apps/dev-wallet/src/utils/getCopyTxString.ts
---
- https://app.asana.com/0/0/1210641578236005
=> fix(wallet): only use the copyTransactionAs legacy, which works everywhere

packages/apps/dev-wallet/src/pages/transfer/Components/AccountSearchBox.tsx
---
- https://app.asana.com/0/0/1210641578236002
=> fix(wallet): fix the sometimes to long k:address by word-break css

packages/libs/wallet-adapter-zelcore/README.md, packages/libs/wallet-adapter-zelcore/package.json
=> fix(wallet-adapter-zelcore): update readme and version

packages/tools/kadena-cli/README.md
=> Fix link to CLI documentation

packages/apps/explorer/src/components/AccountBalanceDistribution/components/ChainBalance.tsx, packages/apps/explorer/src/pages/[networkSlug]/account/[accountName].tsx
---
- https://app.asana.com/0/0/1210800026458552
- https://app.asana.com/0/0/1210800026458555
=> fix(explorer): small fixes

.changeset/fair-kiwis-visit.md, .changeset/little-llamas-refuse.md, packages/apps/chainweaver-wallet-connect-plugin/src/handlers.ts, packages/apps/dev-wallet/src/modules/communication/communication.provider.tsx, packages/apps/dev-wallet/src/modules/plugins/components/SignRequestDialog.tsx, packages/apps/dev-wallet/src/pages/transaction/sign-request.tsx
Short description: update wallet connect plugin have get accounts contracts field optional and update dev wallet to handle sign request messages from plugins better solving multiple errors.
=> Dev wallet wallet connect fixes

.github/CODEOWNERS
=> chore(codeowners): update codeowners list

packages/apps/dev-wallet/src/App/routes.tsx, packages/libs/kode-ui/src/patterns/FocussedLayout/components/LayoutProvider/FocussedLayoutProvider.tsx, packages/libs/kode-ui/src/patterns/SideBarLayout/components/LayoutProvider/SideBarLayoutProvider.tsx
---
- https://app.asana.com/0/0/1211090210461999
=> fix(wallet): hotfix the migrate account

.changeset/hip-ligers-compete.md, packages/tools/kadena-cli/src/prompts/wallets.ts
=> fix(kadena-cli): fix typo in error message

packages/apps/wallet-adapter-react-example/.env.example, packages/apps/wallet-adapter-react-example/src/main.tsx, packages/apps/wallet-adapter-react-example/tsconfig.json
=> fix(wallet-adapter-example): move key to env

.changeset/brown-dryers-share.md
=> chore: trigerring release for chainweb-node-client

packages/apps/rwa-demo/src/app/api/origin/route.ts, packages/apps/rwa-demo/src/components/admin/OrganisationInfoForm/OrganisationInfoForm.tsx, packages/apps/rwa-demo/src/providers/OrganisationProvider/OrganisationProvider.tsx, packages/apps/rwa-demo/src/utils/__tests__/getOriginKey.test.ts, packages/apps/rwa-demo/src/utils/getOriginKey.ts
---
- https://app.asana.com/0/0/1211559279216794
- https://app.asana.com/0/0/1211559279216790
=> fix(rwa): check on the origin
