packages/tools/pactjs-cli/src/retrieve-contract/index.ts, packages/tools/pactjs-cli/src/retrieve-contract/retrieve-contract.ts
- Fixes broken `-c` in retrieve-contract
- change `network` to `networkMap[network].networkId` in command body. (This doesn't break in `/local` calls, but it should use the networkId.)
=> Fixes -c in retrieve-contract 

common/changes/@kadena/client/feat-remove-cmd-malleable_2022-12-05-12-16.json, packages/libs/client/src/pact.ts, packages/libs/client/src/signing/tests/signWithChainweaver.test.ts, packages/libs/client/src/tests/pact.test.ts
When a transaction gets changed after being finalized, we need to reset the hash and signatures (if applicable) because they do not match the transaction it was calculated/signed for.
Closes #107
---
- https://app.asana.com/0/0/1203499728801195
=> [libs/client] Reset cmd when a transaction gets changed

common/changes/@kadena/pactjs-cli/feat-merge-capabilities_2022-12-22-07-52.json, common/changes/@kadena/pactjs-generator/feat-merge-capabilities_2022-12-21-14-18.json, packages/libs/pactjs-generator/etc/pactjs-generator.api.md, packages/libs/pactjs-generator/src/contract/generation/generator.ts, packages/libs/pactjs-generator/src/contract/generation/tests/generator.test.ts, packages/tools/pactjs-cli/src/contract-generate/index.ts
Merge generated types for capabilities across modules so you can also have access to types for capabilities defined in other modules   
Closes https://github.com/kadena-community/kadena.js/issues/137
=> chore(pactjs-generator): Merge generated capability types

packages/apps/graph-client/src/pages/index.tsx
A new feature that allows users to retrieve recent blocks for a number of rows was released. This PR utilizes that functionality to fill in the some rows in the graph-client with blocks from before the new block subscription started so that there are no missing blocks in the starting rows
=> [apps/graph-client] Add recent blocks to UI

CONTRIBUTING.md, README.md
It was ludicrously hard to find a source of information that listed off all of the libraries (And planned libraries) in KadenaJS along with a description of what each one did.
I finally stumbled on the Contributions markdown file.
I just copied the data from there into the readme. The Readme definitely deserves to have that information. I'm not sure if makes sense in the contributions file.
Add kadena js package list and descriptions to the main README so people can easily see what each piece does and find what they need faster.
=> Update README with KadenaJS Reasoning and Package List/Descriptions

docs/domain/domain-model.gql
Propose changes to #154. Mostly within the realm of chainweb
* add scalar values for different types of hashes that match the respective referenced types
* add time format parameter
* add non-nullable modifiers for chainweb types
* fix schema for adjacent blocks of a `Block`
* clarify some custom scalars by focusing on logical types. Generally, avoid representational types. 
* complete schema for `cut`.
* Clarify the distinction between chainweb and pact realm
=> domain-model with revised chainweb realm

common/changes/@kadena/react-components/feat-design-system-spacing_2023-03-31-09-33.json, packages/libs/react-components/src/components/Stack/Stack.tsx, packages/libs/react-components/src/styles/baseGlobalStyles.ts, packages/libs/react-components/src/styles/stitches.config.ts
We were not able to access design system defined spacing outside of the stack component since it depends on breakpoints. This workaround allows us to assign tokens that change depending on the breakpoint. 
Defined new variables in the global styles that change depending on breakpoints and referenced those variables when defining the theme tokens. This means that they should be accessible as any other space token
=> feat(@kadena/ui): Add design system defined spacing to component library

common/changes/@kadena/react-components/bugfix-storybook-deps_2023-04-03-14-36.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/libs/react-components/package.json
`rushx storybook` in `react-components` fails to start as these dev dependencies are missing.
Added the dev dependencies: 
```
"@storybook/csf": "~0.1.0",
"@storybook/docs-mdx": "~0.1.0",
```
=> Add storybook dev dependencies `csf` and `docs-mdx`

common/changes/@kadena/react-components/feat-docs_textcomponents_2023-04-13-21-20.json, packages/apps/kadena-docs/src/components/Markdoc/Heading/Heading.tsx, packages/apps/kadena-docs/src/components/Markdoc/Paragraph/Paragraph.tsx, packages/apps/kadena-docs/src/components/Typography/BodyText.tsx, packages/apps/kadena-docs/src/components/Typography/Headers.ts, packages/apps/kadena-docs/src/components/Typography/HeadingLevel1.tsx, packages/apps/kadena-docs/src/components/Typography/HeadingLevel2.tsx, packages/apps/kadena-docs/src/components/Typography/HeadingLevel3.tsx, packages/apps/kadena-docs/src/components/Typography/HeadingLevel4.tsx, packages/apps/kadena-docs/src/components/Typography/SubBodyText.tsx, packages/apps/kadena-docs/src/components/Typography/index.ts, packages/apps/kadena-docs/src/components/Typography/types.ts, packages/apps/kadena-docs/src/components/index.ts, packages/apps/kadena-docs/src/markdoc/nodes/heading.markdoc.ts, packages/apps/kadena-docs/src/pages/docs/pact/index.md, packages/libs/react-components/src/components/Typography/Heading.stories.tsx, packages/libs/react-components/src/components/Typography/Heading.tsx, packages/libs/react-components/src/components/Typography/Text.stories.tsx, packages/libs/react-components/src/components/Typography/Text.tsx, packages/libs/react-components/src/components/Typography/styles.ts
Adding typography components to the docs.
This way we dont have to use the props everytime, which is error prone.
Just using the named components should make it easier to see what component / style you need to use
Closes https://app.asana.com/0/1204270938438101/1204388315302169/f
=> [Docs] add texttransform option to typography components

common/changes/@kadena/react-components/feat-button-component_2023-04-18-13-03.json, packages/libs/react-components/src/components/Button/Button.stories.tsx, packages/libs/react-components/src/components/Button/Button.tsx, packages/libs/react-components/src/components/Button/index.ts, packages/libs/react-components/src/components/Button/styles.ts, packages/libs/react-components/src/components/IconButton/IconButton.stories.tsx, packages/libs/react-components/src/components/IconButton/IconButton.tsx, packages/libs/react-components/src/components/IconButton/index.ts, packages/libs/react-components/src/index.ts, packages/libs/react-components/src/styles/baseGlobalStyles.ts, packages/libs/react-components/src/styles/colors/index.ts, packages/libs/react-components/src/styles/colors/neutral.ts, packages/libs/react-components/src/styles/stitches.config.ts
Created a Button component that accepts children and an icon which is aligned to the right 
- Currently it only has one style variant which is `primaryFilled`, but it is setup so that all of the colors can be updated via named local tokens
- The button component can also be used as a link when passed `as='a'` and an href.
- I also added another theme dependant color called `primaryHighContrast` for the interactive states for the button. We can add these to the other colors when they are chosen
- Additionally I added a `neutral` color scale that only includes black and white as place holders for now, but it acts as a placeholder for the full neutral color scale when it is available which allows us to use a token to choose the same color regardless of the active theme
=> feat(@kadena/ui): Add Button Component

common/changes/@kadena/react-components/fix-react-components-build_2023-04-25-17-17.json, packages/libs/react-components/tsconfig.cjs.json, packages/libs/react-components/tsconfig.json
Attempt to fix build issue with react-components
Issue has to do with @types/react confusion - v18 used in react-components but v17 is resolved by typescript somehow
~removing skipLibCheck fixed this locally~ edit: incorrect
=> fix(@kadena/react-components): adding skipLibCheck to fix incorrect @types/react version resolution

.gitignore
Title says it all - `.npmrc` was not in .gitignore, this adds it.
=> Added .npmrc to our .gitignore

.github/workflows/ci.yml, rush.json
Node 14 is no longer supported and is causing build failures. To fix this, I suggest updating to the two latest LTS versions of Node.
=> chore: use node 16 or 18

common/changes/@kadena/pactjs-cli/patch-1_2023-05-08-07-29.json, packages/tools/pactjs-cli/src/contract-generate/generate.ts
contract-generate adds the export type to the index file even if the export is already there.  it happens if we run the script on a file twice. 
it can happen where a user updates the contract and wants to ensure the types are also updated.
=> fix(pactjs-cli) : append the export to index.d.ts if it's not already there

README.md
The readme was a bit hard to read. This PR turns the list into a table so it's a tad easier to grasp everything this monorepo contains. Also the reading flow was a bit weird with links back and forth ("go here" and "go back").
For now I've left the content mostly as-is, just moving stuff around.
=> Make readme a bit more readable

common/changes/@kadena/pactjs-cli/fix-pact-cli-test_2023-05-15-09-00.json, packages/tools/pactjs-cli/src/retrieve-contract/tests/retrieve-contract.test.ts
pactjs-cli unit test is failing on Windows. because Windows use "\" for paths.
used nodejs path util to make paths compatible by OS
=> pactjs-cli unit test, windows compatibility

common/changes/@kadena/client/fix-types_2023-05-23-12-45.json, packages/libs/client/etc/client.api.md, packages/libs/client/src/interfaces/IPactCommand.ts, packages/libs/client/src/pact.ts
- Fixes the type for addCap when building a transaction without generating types for the module first.
- Adds the requestKey to IPactCommand
=> [@kadena/client] Fixes types

packages/tutorials/election-dapp/front-end/src/utils.ts, packages/tutorials/election-dapp/front-end/tsconfig.json, packages/tutorials/election-dapp/pact/election.pact, packages/tutorials/election-dapp/snippets/deploy-testnet.js, packages/tutorials/election-dapp/snippets/list-modules.js
=> Various minor fixes and cleanups for the election dApp tut

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/tools/cookbook/package.json, packages/tools/cookbook/src/accounts/transfer-create-with-chainweaver.ts, packages/tools/cookbook/src/accounts/transfer-create-with-private-key.ts
Adds an example on how to create a `transfer-create` transaction and sign it with a private key.
Usage:
`ts-node transfer-create.js k:{senderPublicKey} k:{receiverPublicKey} {amount}`
=> [@kadena/cookbook] transfer-create using private key

CONTRIBUTING.md
And fixed installation instruction. If the "conventions" section grows we can move it to its own file.
---
- https://app.asana.com/0/0/1204775833304758
=> Update contributing guide, add git/github conventions

common/changes/@kadena/client/feat-public-nonce_2023-06-09-14-24.json, packages/libs/client/src/pact.ts
We added nonce to IPactCommand, but didn't set it in `createCommand()`.
=> Nonce publicly available

docs/decisions/0001-use-adr.md, docs/decisions/_template.md
My feeling is that we have a need and desire to write down reasoning and decisions for all sorts of (architectural) decisions, for example:
- Why are we using monorepos and related tooling?
- What environments and browsers do we want to support for our packages/apps?
- Why and how are we using tools like TypeScript and ESLint etc.?
- How do we want to write cross-OS scripts?
- Let's use `@kadena/client` as entry point for common use cases
- ...
- ...
This is a proposal to start recording such decisions.
An example can be seen in the Remix repository: https://github.com/remix-run/remix/tree/main/decisions. Do you know of others?
---
- https://app.asana.com/0/0/1204735333828872
=> Propose to start using ADRs with an ADR and add a template

packages/apps/kadena-docs/src/components/BottomPageSection/BottomPageSection.tsx, packages/apps/kadena-docs/src/components/BottomPageSection/components/EditPage.tsx, packages/apps/kadena-docs/src/components/Layout/Code/Code.tsx, packages/apps/kadena-docs/src/components/Layout/Full/Full.tsx, packages/apps/kadena-docs/src/components/Layout/components/Main/Main.tsx, packages/apps/kadena-docs/src/scripts/remarkFrontmatterToProps.js, packages/apps/kadena-docs/src/types/Layout.ts
as a user i want to easily navigate from page to page.
the next and previous button will get you to appropriate pages in the navigation.
There is no design implemented yet. just the functionality.
Designs are not ready yet
Closes [[issue link](https://app.asana.com/0/1204649083736950/1204691278957821/f)]
=> [docs] next prev navigation

common/changes/@kadena-dev/eslint-config/fix-remove_proptypesrule_2023-06-16-07-29.json, packages/tools/eslint-config/profile/next.js
=> chore(nextjs): remove the unnecessary proptypes rule from eslint config

packages/apps/kadena-docs/src/data/menu.mjs, packages/apps/kadena-docs/src/pages/docs/code-of-conduct.mdx, packages/apps/kadena-docs/src/pages/docs/contribute/code-of-conduct.mdx
Supersedes #350. I'm not seeing significant missing elements in comparison, except for a generic contact option (see below). So I'll close that one.
This is a copy of the draft at https://docs.google.com/document/d/1SU9OKkobYpq0R5vDK1MeYxiz8RpXxYmaceF3UMtzjXQ
=> Add existing coc

.github/workflows/ci.yml, .github/workflows/release.yml
This disables the release pipeline, which we aren't using and is very red. Can still be ran manually.
Activating the CI pipeline this way shows master is in a good state.
~**NOTE:** Needs work. just realized this may not do much as it runs things based on changes with... `master` 🤦~
=> Run CI pipeline after merges to/in master branch

common/changes/@kadena/chainweb-stream-client/feat-chainweb-stream-receive-heights-event_2023-06-14-15-56.json, packages/libs/chainweb-stream-client/README.md, packages/libs/chainweb-stream-client/etc/chainweb-stream-client.api.md, packages/libs/chainweb-stream-client/src/examples/index.ts, packages/libs/chainweb-stream-client/src/index.ts, packages/libs/chainweb-stream-client/src/types.ts
Implements consumption of the heights event. Needed for the reconnection improvements https://github.com/kadena-community/kadena.js/issues/275#issuecomment-1578856960. Server https://github.com/kadena-io/chainweb-stream-server/pull/5
This changes the .lastHeight client property to track the highest block seen across all chains based on the server's corresponding cw-node. The reconnection property minheight is now sent as .lastHeight - CONFIRMATION_DEPTH - 3 (max chain height span)
Raising against a new base branch, as the upcoming release will require a deduplication module to only emit each event once. This will be raised separately against the same base branch
=> [@kadena/Chainweb-stream-client] Receive heights event, improve reconnection strategy

.github/workflows/ci.yml, .github/workflows/release.yml, common/config/rush/command-line.json, common/config/rush/experiments.json, packages/apps/graph/package.json, packages/apps/kadena-docs/package.json, packages/apps/transfer/package.json, packages/libs/bootstrap-lib/package.json, packages/libs/chainweb-node-client/package.json, packages/libs/chainweb-stream-client/package.json, packages/libs/chainwebjs/package.json, packages/libs/client/package.json, packages/libs/cryptography-utils/package.json, packages/libs/kadena.js/package.json, packages/libs/pactjs-generator/package.json, packages/libs/pactjs-test-project/package.json, packages/libs/pactjs/package.json, packages/libs/react-components/config/rush-project.json, packages/libs/react-components/package.json, packages/libs/react-ui/package.json, packages/libs/types/package.json, packages/tools/cookbook/package.json, packages/tools/create-kadena-app/package.json, packages/tools/eslint-config/package.json, packages/tools/eslint-plugin/package.json, packages/tools/heft-rig/package.json, packages/tools/heft-rig/profiles/default/config/rush-project.json, packages/tools/pactjs-cli/package.json, packages/tools/remark-plugins/package.json, packages/tools/rush-fix-versions/package.json
We're using an interesting feature of Rush, but with default values and slightly confusing scripts here and there. This simplifies/clarifies things a bit, as we're doing `rush build` and `rush test` separately already anyway in many cases.
=> Simplify rush build + test

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/apps/kadena-docs/package.json, packages/libs/react-ui/package.json
we get a lot of errors on the `mini-css-extract-plugin` for vanilla-extract.
This has to do with running the `rush update`.
I want to try if the problems are resolved if we lock the versions of vanilla extract
=> chore(ui): lock version of vanilla extract

.github/workflows/ci.yml
No longer necessary, affected packages also logged in the actual step.
Also fixed formatting step when in `main`.
=> Remove temp CI step

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/apps/kadena-docs/src/pages/_app.tsx, packages/libs/react-ui/.gitignore, packages/libs/react-ui/README.md, packages/libs/react-ui/package.json, packages/libs/react-ui/src/index.ts
When trying to import any VE styling utilities like theme variables or utility classes, consuming applications would error. This is due to do the following issue: https://github.com/vanilla-extract-css/vanilla-extract/issues/850#issuecomment-1493719209
This PR creates separate entry points for components and styles to fix this.
=> [@kadena/react-ui]: Fix export for styling utilities

.gitattributes
=> chore(monorepo): force `rush update` when pnpm-lock.yaml is out of date

packages/apps/docs/src/components/NotFound/styles.ts, packages/libs/react-components/src/styles/stitches.config.ts
- Add spacing variables on components library
- Remove the Section bottom padding because with the default article padding it's becoming more space.
=> fix(kadena-docs): footer spacing

common/changes/@kadena/client/chore-kadena-client-readme_2023-07-06-11-54.json, packages/libs/client/README.md
Was reading up a bit on this readme and found it a bit hard to access.
Also fixed the instructions, as I think it's better to keep dependencies local to the project (as opposed to install them globally).
=> Improve accessibility of the `@kadena/client` readme

packages/libs/react-ui/src/components/Tabs/Tabs.css.ts, packages/libs/react-ui/src/components/Tabs/TabsContainer.tsx
For smaller screens, tab names are going into multiple lines. So, instead of going into multiple lines and having a scrollbar at page level. This change introduces a horizontal scrollbar to `Tabs` for mobile devices when multiple tabs are present and then tab names will fit in a single line. 
**Before**
**After**
=> fix(kadena-react-ui): tabs responsiveness for mobile devices

packages/apps/docs/src/components/Layout/components/Aside/ListItem.tsx, packages/apps/docs/src/components/Markdown/Heading/Heading.tsx, packages/apps/docs/src/components/Markdown/Heading/Heading1.tsx, packages/apps/docs/src/components/Markdown/Heading/Heading2.tsx, packages/apps/docs/src/components/Markdown/Heading/Heading3.tsx, packages/apps/docs/src/scripts/remarkHeadersToProps.mjs, packages/apps/docs/src/types/Layout.ts, packages/apps/docs/src/utils/createSlug.ts, packages/apps/docs/src/utils/tests/createSlug.test.ts
- Updated a createSlug method to pass `index`
- Append `index` values only if string has any special characters at the end. To avoid a use case like `not` and `not?`  to have same link reference
- if string contains only special characters then it replaced with `operator-${index}`
- Update components to pass `index` props
=> fix(kadena-docs): improve slug method for special characters + strings ends with special characters

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/libs/react-ui/.babelrc.json, packages/libs/react-ui/package.json
After merging https://github.com/kadena-community/kadena.js/pull/530 I realised that css files are not resolved correctly. This PR fixes that by adding and configuring Babel module resolver.
=> Add Module resolver to resolve css files with path alias imports

common/changes/@kadena/client/fix-parser-symbols_2023-07-17-12-27.json, packages/libs/pactjs-generator/src/contract/parsing/utils/parser-utilities/str.ts, packages/libs/pactjs-generator/src/contract/parsing/utils/parser-utilities/tests/str.test.ts
fixed str parser to parse pact symbols (`'symbol_name`) as string. 
this will fix the issue with finding module namespace
=> fix(pactjs-generator): parse symbols as string

packages/libs/react-ui/src/components/Icon/IconWrapper.css.ts
the producticons were not rendering correctly in apps, on darkmode
transform hack is needed for Safari (and iOS Chrome)
if not the multipy mixBlendMode will not work
the transform will take the icon out of its render layer and will render the icon correctly
=> fix(react-ui) producticons

common/changes/@kadena/chainweb-stream-client/fix-chainweb-stream-json-parse_2023-07-18-17-21.json, packages/libs/chainweb-stream-client/src/index.ts, packages/libs/chainweb-stream-client/src/sliding-cache.ts, packages/libs/chainweb-stream-client/src/util.ts
JSON.parse was not try/caught before
Introduce a lenient json parsing for heights/data (not fatal) but make it fatal for initial event (need this to validate the config)
=> JSON parse try/catch

common/changes/@kadena/chainweb-stream-client/chore-bump-chainweb-stream-version_2023-07-19-05-44.json, packages/libs/chainweb-stream-client/package.json
Bumping chainweb-stream-client version to 0.0.9 for release
=> bump chainweb-stream-client version

packages/libs/react-ui/src/components/Tooltip/Tooltip.stories.tsx, packages/libs/react-ui/src/components/Tooltip/index.ts, packages/libs/react-ui/src/components/Tooltip/tooltipHandler.ts, packages/libs/react-ui/src/components/index.ts
- Closes ["Bug: Tooltip Storybook story is erroring"]()
- Seems that the error is related to using `forwardRef` and the imports into storybook
- It works alright when importing the `Tooltip` component and `tooltipHandler` method from their source files, rather than the index
=> Bug: Tooltip Storybook story is erroring

packages/libs/react-ui/src/components/Button/Button.tsx
Seems like the icon is primarily used like this.
=> feat: align icon to the right by default

packages/apps/docs/src/utils/createSlug.ts
The issue is with id starting with numbers. For some weird reasons, the ids starting with numbers doesn't work as expected with query selector. 
So, removing numbers and numbers with dots in slug
=> fix(kadena-docs): deep link slugs with numeric values

packages/libs/react-ui/src/components/Button/Button.stories.tsx
In storybook the button can now render the icon twice when the loading prop is true. This will fix that.
=> fix: button rendering in storybook

.github/workflows/ci.yml
Packages depending on modified packages are not covered in the CI run, resulting in occasional issues only detected in the `main` branch where everything is covered.
=> Use `--to` AND `--from` to determine affected packages

packages/libs/react-components/package.json, packages/libs/react-ui/package.json
Since we are not yet publishing `@kadena/react-ui` and we will not publish `@kadena/react-components`, I've set them to `private` on their package.json files
=> chore(@kadena/react-ui): Update component library packages to be private

packages/libs/client/etc/client.api.md, packages/libs/client/src/commandBuilder/commandBuilder.ts, packages/libs/client/src/composePactCommand/utils/addSigner.ts, packages/libs/client/src/index.ts, packages/libs/client/src/interfaces/type-utilities.ts, packages/libs/client/src/signing/ISignFunction.ts
exposing `WithCapability` type utility for more flexible type supports
With the type utility users can make functions like this
```ts
const myTrWrapper = <T extends string>( pactCode:T, withCapability:WithCapability<T>) =>{
return Pact.builder.execution(pactCode)....
}
myTrWrapper(
Pact.modules.coin.transfer(...)
// this also shows the proper types
(withCapability)=>[withCapability("coin.GAS"),withCapability("coin.TRANSFER", ...)]
)
```
=> feat(client): expose WithCapability type helper

packages/apps/docs/package.json
- Currently `format` script in docs are failing because of `format:pkg` script not found
=> chore: fix docs format script

packages/apps/tools/src/components/Common/Layout/partials/Footer/Footer.tsx, packages/libs/react-ui/src/components/NavFooter/Footer.css.ts, packages/libs/react-ui/src/components/NavFooter/Footer.stories.tsx, packages/libs/react-ui/src/components/NavFooter/Footer.test.tsx, packages/libs/react-ui/src/components/NavFooter/Footer.tsx, packages/libs/react-ui/src/components/NavFooter/FooterIconButton.tsx, packages/libs/react-ui/src/components/NavFooter/FooterLink.tsx
Instead of using variants, the footer just applies the darkThemeClass to a wrapping div on the footer to keep it in the dark theme. This can be applied via the `darkMode` prop on `Footer.Root`
=> chore(@kadena/react-ui): Update NavFooter darkmode configuration

packages/libs/react-ui/src/components/Tooltip/Tooltip.css.ts
Set pointer events of tooltip to false so it doesn't flicker when you hover a portion of the tooltip
=> fix(@kadena/react-ui): Fix Tooltip flicker

packages/apps/docs/src/components/BottomPageSection/components/EditPage.tsx, packages/apps/docs/src/components/NotFound/NotFound.tsx, packages/libs/react-ui/src/components/Button/Button.css.ts
We noted that in Docs, after switching from [react-components to react-ui](https://github.com/kadena-community/kadena.js/pull/717), the hover style of a button that's rendered as anchor wasn't correct. This fixes that by correctly setting the button color and font weight.
Current/faulty hover:
New/fixed hover:
=> Fix button style react-ui

packages/apps/docs/src/components/Markdown/Heading/Heading.tsx, packages/apps/docs/src/scripts/importReadme.mjs
This PR fixes an issue with headers with inline code
Example - " ## Header with `features` "
=> fix(docs): header with inline codes

.github/workflows/ci.yml
Didn't seem to work properly, see e.g. https://github.com/kadena-community/kadena.js/pull/751 + https://github.com/kadena-community/kadena.js/actions/runs/5794161673/job/15703214188?pr=751. 
After re-opening the same PR (https://github.com/kadena-community/kadena.js/pull/755) the re-build did work.
=> Disable build caching in ci.yml

.github/workflows/ci.yml, common/changes/@kadena/client/ag-fix-react-ui-build-cache_2023-08-08-11-42.json, packages/libs/client/config/rush-project.json, packages/libs/react-ui/config/rush-project.json
Fixes the build cache for react-ui
The build cache record was missing the `types` directory as the defaults are different than what is configured as output for the `@kadena/react-ui` project. 
See for info: 
https://rushjs.io/pages/maintainer/build_cache/#configuring-project-output-folders
https://rushjs.io/pages/configs/rush-project_json/
=> chore(react-ui): fix build cache

packages/libs/react-ui/src/components/ContentHeader/ContentHeader.css.ts
=> fix(@kadena/react-ui): ContentHeader icon color in dark mode

packages/apps/docs/src/components/Layout/Blog/Blog.tsx, packages/libs/react-ui/src/components/Grid/Grid.css.ts, packages/libs/react-ui/src/components/Grid/Grid.stories.tsx, packages/libs/react-ui/src/components/Grid/GridRoot.tsx
- Updated the grid spacing options to have a `$` prefix like other components
- Updated the styles so that even if the contents are larger than column, they overflow. This means that the grid will always fit within it's parent container regardless of the child's size. We may want to change this in the future, but I think this behavior is better at the moment
=> fix(@kadena/react-ui): Update Grid prop names and overflow bug

packages/apps/docs/src/pages/docs/blogchain/index.tsx
Hides the sidemenu placeholder for the Blogchain section of the docs
=> [docs] Bug: Sidemenu text is showing up on BlogChain

.github/workflows/chromatic.yml
* Swap to On Push events (to ensure Chromatic does not lose track of accepted baselines)
* Automatically accept changes on main (any differences should show up in Branches. This ensures we always have a clean base branch)
See https://www.chromatic.com/docs/github-actions#recommended-configuration-for-build-events
=> Change Chromatic Config

packages/libs/react-ui/src/components/Notification/NotificationContainer.tsx
Using a `p` tag for description causing an issues in docs, like div tags wrapped within p tag. It introduced next js hydration error. 
```
<p>
<div>
notification description
</div>
</p>
```
=> fix(notification): next js hydration error

packages/libs/react-ui/src/components/NavHeader/NavHeader.stories.tsx, packages/libs/react-ui/src/components/NavHeader/NavHeader.tsx, packages/libs/react-ui/src/components/NavHeader/NavHeaderLink.tsx, packages/libs/react-ui/src/components/NavHeader/NavHeaderNavigation.tsx, packages/libs/react-ui/src/components/NavHeader/index.ts, packages/libs/react-ui/src/components/NavHeader/useGlow.ts, packages/libs/react-ui/src/components/index.ts, packages/libs/react-ui/src/index.ts
Through many changes to the implementation of NavHeader we ended up with a less than ideal version of it.
This PR will fix these issues and also some other things that were forgotten in the original implementation <sup>1</sup>
**Fixes**
- allow consumer to be flexible with the children of `<NavHeader.Navigation />` so that we can properly support NextJS Link elements and anything else.
- allow consumer to set which link is active on load (`activeLink` prop on `<NavHeader.Navigation />`).
**<sup>1</sup> other things this PR adds:**
- we forgot to export the NavHeader from the react-ui components index barrel file.
- support custom onclick handler for children of `<NavHeader.Navigation />`.
=> Refactor/change NavHeader component

packages/apps/tools/src/components/Common/DrawerToolbar/index.tsx
=> [@kadena/tools] Implement initial openItem in Drawer Toolbar

common/changes/@kadena/client/feat-addSignatures_2023-08-16-14-23.json, packages/libs/client/etc/client.api.md, packages/libs/client/src/signing/chainweaver/signWithChainweaver.ts, packages/libs/client/src/signing/index.ts, packages/libs/client/src/signing/utils/addSignatures.ts, packages/libs/client/src/signing/utils/tests/addSignature.test.ts, packages/libs/client/src/signing/walletconnect/quicksignWithWalletConnect.ts
Made addSignatures public (again) to make signing in other ways than supported with @kadena/client easier.
Closes: #781
=> [client] Make addSignatures public

packages/apps/tools/src/components/Common/Layout/partials/Header/Header.tsx, packages/libs/react-ui/src/components/NavHeader/NavHeaderNavigation.tsx
**History:** initially `activeLink` was added as a prop on the `NavHeader.Navigation` to set the initially active navigation item.
**Update:** this PR will extend that functionality to actively listen to changes to the prop and update the navigation accordingly.
_This ensures that, for example, when passing the `activeLink` prop (controlled version of the NavHeader) and using the browser navigation buttons to go back or forward in history, the state will update and highlight the correct navigation item._
https://github.com/kadena-community/kadena.js/assets/79908211/976bebe8-ac02-4cbc-9544-3ac4a549c4e7
=> NavHeader feat: actively listen to activeLink changes

packages/libs/react-ui/CONTRIBUTING.md
Adding unspoken conventions used within the component library
---
- https://app.asana.com/0/0/1205217537838854
=> chore(@kadena/react-ui): Add CONTRIBUTING.md

packages/libs/react-ui/CONTRIBUTING.md, packages/libs/react-ui/src/components/Accordion/Accordion.tsx, packages/libs/react-ui/src/components/Accordion/AccordionSection.tsx, packages/libs/react-ui/src/components/MaskedValue/MaskedValue.tsx, packages/libs/react-ui/src/components/Modal/Modal.tsx, packages/libs/react-ui/src/components/Modal/ModalProvider.tsx, packages/libs/react-ui/src/components/NavHeader/NavHeaderNavigation.tsx, packages/libs/react-ui/src/components/NavHeader/useGlow.ts, packages/libs/react-ui/src/components/Pagination/PageNav.tsx, packages/libs/react-ui/src/components/Pagination/Pagination.tsx, packages/libs/react-ui/src/components/Tabs/TabsContainer.tsx, packages/libs/react-ui/src/components/Tree/Tree.tsx, packages/libs/react-ui/src/components/Tree/TreeItems.tsx
This adds "use client" to the top of all client components.
Looked into a couple options: 
- export client components via a separate export - this adds more complexity for users and it doesn't offer much except clear separation between server and client components
- exporting all components via the default export and also exporting only the server components via a `rsc` export. This is how some other packages are handling this, but I don't think the benefits are applicable in our component library
The approach chosen is to export all components together. This works becuase:
- Server components and client components can be used in server components
- Server components can't be used within client components, but if the consuming component is a client component it should define "use client" …
=> fix(@kadena/react-ui): Updating client components

packages/apps/docs/src/components/Layout/Landing/Landing.tsx, packages/apps/docs/src/pages/_app.tsx, packages/apps/docs/src/pages/docs/blogchain/index.tsx, packages/apps/docs/src/pages/docs/kadena/index.tsx, packages/apps/docs/src/pages/index.tsx, packages/apps/docs/src/styles/index.css.ts
This PR addresses couple of issues!
- UI alignment issues of the browse section spacing
- ~Before unload causing an issue when user manually reload the page, because of event is undefined at that time. So, added an extra check for it~ it's been take care of in general tracking PR
=> fix(docs): ui alignment fixes

packages/apps/tools/src/pages/transactions/cross-chain-transfer-finisher/index.tsx, packages/libs/react-ui/src/components/Input/Input.css.ts, packages/libs/react-ui/src/components/Input/Input.stories.tsx, packages/libs/react-ui/src/components/Input/Input.tsx, packages/libs/react-ui/src/components/InputWrapper/InputWrapper.stories.tsx, packages/libs/react-ui/src/components/InputWrapper/InputWrapper.tsx, packages/libs/react-ui/src/components/TextField/TextField.stories.tsx, packages/libs/react-ui/src/components/TextField/TextField.tsx
The `leadingTextWidth` prop didn't apply the provided width to the actual input when providing it via inputProps - it needed to be applied to the wrapper instead.
- Moved the classname that applies with width to the container around the text rather than the text itself
- Removed the `leadingTextWidth` prop from the inputProps in `TextField` to prevent confusion
- Removed the default `leadingTextWidth` value from `InputWrapper` so that the behavior is more predictable
- Added `leadingTextWidth` to the `TextField` story
- Added descriptions to the following stories: `InputWrapper`, `TextField`, `Input`
=> fix(@kadena/react-ui): Fixed leadingTextWidth in TextField Component + Added Story descriptions

common/changes/@kadena/client/chore-ag-update-changelog-for-1.0.0_2023-08-22-14-00.json, packages/libs/client/CHANGELOG.json, packages/libs/client/CHANGELOG.md
When we worked on version 1.0.0 we added changelog information using `rush change`.
This has lead to a too granular list of changes. To make it more relevant for
the consumer of the library, we decided to update the changelog with only a limited
set of entries
=> chore(client): update changelog

packages/libs/react-ui/src/components/Input/Input.css.ts, packages/libs/react-ui/src/components/Input/Input.stories.tsx, packages/libs/react-ui/src/components/Input/Input.tsx, packages/libs/react-ui/src/components/Select/Option.tsx, packages/libs/react-ui/src/components/Select/Select.css.ts, packages/libs/react-ui/src/components/Select/Select.stories.tsx, packages/libs/react-ui/src/components/Select/Select.tsx, packages/libs/react-ui/src/components/Tooltip/Tooltip.css.ts, packages/libs/react-ui/tsconfig.json
[Asana Link](https://app.asana.com/0/1204958723576385/1205164815746147/f)
**What changed?**
- Updated Select styling to match design and support dark and light theme
- Tweaked the size of the native HTML select element that we render to ensure you can click anywhere on the actual Select component to see its options (previously required to click in the center of our visual component)
- Added disabled styling (missing exact design, [also missing in e.g. Input component](https://app.asana.com/0/1205288273408141/1205332525545630/f)?)
- Add variant prop to allow switching between default form select and one with a solid border and transparent background
- Set Tooltip z-index as a temporary fix to ensure it's above form elements (created …
=> Update Select component

packages/libs/react-ui/src/components/Pagination/Pagination.stories.tsx, packages/libs/react-ui/src/components/Pagination/Pagination.tsx
=> [@react-ui] Add initialSelectedPage to Pagination Component

.changeset/neat-kiwis-own.md, common/changes/@kadena/client/feat-signWithEckoWallet_2023-08-08-11-29.json, packages/libs/client/etc/client.api.md, packages/libs/client/src/interfaces/ISigningRequest.ts, packages/libs/client/src/signing/ISignFunction.ts, packages/libs/client/src/signing/eckoWallet/eckoCommon.ts, packages/libs/client/src/signing/eckoWallet/eckoTypes.ts, packages/libs/client/src/signing/eckoWallet/quicksignWithEckoWallet.ts, packages/libs/client/src/signing/eckoWallet/signWithEckoWallet.ts, packages/libs/client/src/signing/eckoWallet/tests/eckoCommon.test.ts, packages/libs/client/src/signing/eckoWallet/tests/quicksignWithEckoWallet.test.ts, packages/libs/client/src/signing/eckoWallet/tests/signWithEckoWallet.test.ts, packages/libs/client/src/signing/index.ts, packages/libs/client/src/signing/utils/pactCommandToSigningRequest.ts, packages/libs/client/src/signing/walletconnect/signWithWalletConnect.ts, packages/libs/client/src/signing/walletconnect/walletConnectTypes.ts, packages/libs/client/src/utils/tests/createTransaction.test.ts
Adds two functions to sign a transaction with the [Ecko Wallet API](https://docs.ecko.finance/eckodex/getting-started/eckowallet/eckowallet-api).
Usage, where `unsignedTransaction` is a `IPactCommand`:
```
const signWithEckoWallet = createEckoWalletSign();
await signWithEckoWallet(unsignedTransaction);
```
```
const quicksignWithEckoWallet = createEckoWalletQuicksign();
await quicksignWithEckoWallet(unsignedTransaction);
```
On both `signWithEckoWallet` and `quicksignWithEckoWallet` there are several helpers available:
```
const isInstalled = signWithEckoWallet.isInstalled();
const isConnected = await signWithEckoWallet.isConnected();
const accountInfo = await getAccountInfo();
await signWithEckoWallet.connect();
```
`connect()` is also automatically called when signing for a transaction
=> [client] Adds signWithEckoWallet and quicksignWithEckoWallet functions

.github/workflows/ci.yml
Turbo knows what tasks depend on each other. Using this
we can optimize all tasks that we need in ci and execute
them as one task
=> chore(build): use turbo to execute all ci tasks

.github/workflows/ci-changelog.yml
Changesets recommends to [ignore](https://github.com/changesets/changesets/blob/main/docs/intro-to-using-changesets.md#not-every-change-requires-a-changeset) pull requests that should not bump any versions, but we are only human so might forget without knowing whether this was on purpose or forgotten.
This PR adds a tiny workflow to ensure we add a changeset file, even if the bump is "none".
=> Add workflow to verify changelog has been added to PRs

packages/apps/tools/src/components/Common/Layout/partials/Header/Header.tsx, packages/libs/react-ui/src/components/Select/Select.stories.tsx, packages/libs/react-ui/src/components/Select/Select.test.tsx, packages/libs/react-ui/src/components/Select/Select.tsx
When the Select component was being used in the dev wallet, it wasn't working with react-hook-form. This PR adjusts props a little to require an `id` like the input and be compatible with react-hook-form. Tested this in the dev-wallet
=> fix(@kadena/react-ui): Update Select props to align with Input props and tested with external lib

packages/apps/docs/.gitignore, packages/apps/docs/package.json, packages/apps/docs/src/pages/api/blog.ts, packages/apps/docs/src/pages/api/semanticsearch.ts, packages/apps/docs/src/scripts/getdocstree.mjs, packages/apps/docs/src/utils/getMostPopularPages.ts, packages/apps/docs/src/utils/staticGeneration/getData.mjs, packages/apps/docs/turbo.json
Not 100% sure this fixes things, but at least it's more clear what is generated and what not. Maybe it was just the `searchIndex.json` entry that was no longer there.
=> Move generated files to their own dir (docs)

.changeset/sharp-llamas-push.md, packages/tools/pactjs-cli/bin/pactjs.js, packages/tools/pactjs-cli/src/index.ts
Add missing shebang to the executable file. that will fix the followoing issue
```bash
bin/pactjs: line 1: syntax error near unexpected token `'../lib/index.js''
```
=> Fix(pactjs-cli) : add missing shebang to the executable file

.github/workflows/chromatic-docs.yml, .github/workflows/chromatic-react-ui.yml, .github/workflows/ci-changelog.yml, .github/workflows/ci.yml, .github/workflows/docs-chores.yml, .github/workflows/release.yml
Even though it's now collapsed behind the ► in CI (see screenshot), it's still good to avoid that progress percentage updater in case you're looking at a live run.
**Before:**
**After:**
=> Upgraded all instances of `actions/checkout` to v4 and added `progress: false`

.changeset/honest-months-hang.md, packages/apps/tools/src/components/Common/Layout/partials/Header/Header.tsx, packages/libs/react-ui/src/components/NavFooter/NavFooter.css.ts, packages/libs/react-ui/src/components/NavFooter/NavFooter.stories.tsx, packages/libs/react-ui/src/components/NavFooter/NavFooterLink.tsx, packages/libs/react-ui/src/components/NavHeader/NavHeader.stories.tsx, packages/libs/react-ui/src/components/NavHeader/NavHeaderLink.tsx, packages/libs/react-ui/src/components/NavHeader/NavHeaderNavigation.tsx, packages/libs/react-ui/src/components/NavHeader/index.ts
Updated the following to accept an as child prop so that they can be used with next/link
- NavHeader.Link
- NavFooter.Link
=> chore(@kadena/react-ui): Update nav links to use asChild convention

.changeset/dry-files-wonder.md, packages/tools/kda-cli/README.md, packages/tools/kda-cli/bin/kda.js, packages/tools/kda-cli/package.json, packages/tools/lint-package/src/rules/package-json/scripts.ts
Since this is now part of our linter scripts, we should see something like this:
```
❯ pnpm lint -F @kadena/pactjs-cli
...
@kadena/pactjs-cli:lint: . lint:pkg$ lint-package
@kadena/pactjs-cli:lint: . lint:src$ eslint package.json src --ext .js,.ts --fix
@kadena/pactjs-cli:lint: . lint:pkg: /Users/lars/p/kadena/kadena.js/packages/tools/pactjs-cli/config/api-extractor.json
@kadena/pactjs-cli:lint: . lint:pkg:         warning   API Extractor is enabled, "types" in package.json should be "dist/pactjs-cli.d.ts"
@kadena/pactjs-cli:lint: . lint:pkg: /Users/lars/p/kadena/kadena.js/packages/tools/pactjs-cli/package.json
@kadena/pactjs-cli:lint: . lint:pkg:         error     Missing or incorrect shebang in executable bin/pactjs.js
...
ERROR  run failed: command  exited (1)
```
The CI should halt. …
=> Add check for `bin` shebang and `[pre|post]install` scripts

.changeset/wild-books-shop.md, packages/apps/docs/src/pages/docs/pact/vscode/index.md
Added docs page for the Pact Visual Studio Code extension.
=> feat(docs): pact-vscode documentation

.changeset/fresh-cows-sin.md, packages/tools/cookbook/src/accounts/create-account.ts, packages/tools/cookbook/src/accounts/details.ts, packages/tools/cookbook/src/accounts/get-balance.ts, packages/tools/cookbook/src/accounts/transfer-create-with-chainweaver.ts, packages/tools/cookbook/src/accounts/transfer-create-with-private-key.ts
A few minor changes were added in one of the later versions of the client. This PR fixes the examples that we have in the cookbook for this new version.
=> Fixes multiple cookbook files that used an old syntax for @kadena/client

.changeset/gold-stingrays-camp.md, packages/libs/client/etc/client.api.md, packages/libs/client/src/signing/index.ts, packages/libs/client/src/signing/keypair/createSignWithKeypair.ts, packages/libs/client/src/signing/keypair/tests/signWithKeypair.test.ts, packages/libs/client/src/signing/utils/addSignatures.ts, pnpm-lock.yaml
- feat(client): adds `createSignWithKeypair` and allows `signWithKeypair`
This new function allows you to sign with:
- one keypair, one transaction
- one keypair, multiple transactions
- multiple keypairs, one transaction
- multiple keypairs, multiple transactions, multiple times
An example of the most comprehensive variant:
```typescript
const signWithKeystore = createSignWithKeypair([keyPair, keyPair2]);
const [signedTx1, signedTx2] = await signWithKeystore([tx1, tx2]);
const signedTx3 = await signWithKeystore(tx3);
```
=> [@kadena/client] add `signWithKeypair` functionality

.changeset/famous-llamas-relate.md, packages/libs/client-examples/src/example-contract/devnet-coin-get-balance.ts
Added an example that gets the balance of the coin token on devnet. The example purposely does not use the utils files for ease of understanding and simplicity reasons.
=> Added devnet get balance example

.changeset/little-flowers-return.md, packages/libs/pactjs/package.json, packages/libs/pactjs/src/PactNumber.ts, packages/libs/pactjs/src/tests/PactNumber.test.ts, pnpm-lock.yaml
Fixed PactNumber to prevent the creation of scientific notation for large numbers.
This PR will address the issues https://github.com/kadena-community/kadena.js/issues/519
=> Fixed PactNumber to prevent the creation of scientific notation for large numbers

.changeset/small-singers-brush.md, .github/workflows/release.yml, packages/libs/chainweb-node-client/package.json, packages/libs/chainweb-stream-client/package.json, packages/libs/chainwebjs/package.json, packages/libs/client/package.json, packages/libs/cryptography-utils/package.json, packages/libs/pactjs-generator/package.json, packages/libs/pactjs/package.json, packages/libs/types/package.json
Adds the badge in the npm registry, so consumers know where the package was built and by whom. See the resources below for more details.
Example package: https://www.npmjs.com/package/sigstore (the green checkmark next to the version, linking to the bottom of the page with more details/links).
Resources:
- https://github.blog/2023-04-19-introducing-npm-package-provenance/
- https://github.blog/changelog/2023-09-26-npm-provenance-general-availability/
- https://docs.npmjs.com/generating-provenance-statements
=> Generate provenance statement during npm publish

.changeset/nine-fireants-wonder.md, packages/apps/docs/src/components/BottomPageSection/components/Subscribe.tsx, packages/apps/docs/src/components/Markdown/MDNotification/MDNotification.tsx, packages/apps/docs/src/components/Search/components/SearchResults.tsx, packages/apps/graph-client/src/pages/event/[key].tsx, packages/apps/graph-client/src/pages/transaction/[key].tsx, packages/apps/tools/src/components/Global/FormStatusNotification/index.tsx, packages/apps/tools/src/pages/faucet/existing/index.tsx, packages/apps/tools/src/pages/transactions/cross-chain-transfer-tracker/index.tsx, packages/libs/react-ui/src/components/Notification/Notification.css.ts, packages/libs/react-ui/src/components/Notification/Notification.stories.tsx, packages/libs/react-ui/src/components/Notification/NotificationContainer.tsx
- Introduced the variant as `standard` and `outlined`. But I'm open for discussion here whether we wanna go with outline as a boolean prop. 
- Added inline boolean prop to make the inline notification component for medium and larger screens. 
If we're agreeing to the implementation then I'll update all app/libs which are already consuming notification component
~TODO:~
=> feat(ui): implement non-outlined and inline style notification component

.changeset/three-shrimps-give.md, packages/libs/react-ui/src/components/Notification/Notification.css.ts, packages/libs/react-ui/src/components/Notification/NotificationContainer.tsx
https://www.figma.com/file/TS5LF7mCIh3fcl27Jgmqx9/%3Ckda-notification-%2F%3E?type=design&node-id=945-1052&mode=design&t=4WR0njYHNmzPIGTu-0 
For larger screens we don't want the content also to be fluid, instead of want to set the maxWidth for the content wrapper
=> fix(react-ui): add content wrapper and set max width for notification component

packages/apps/tools/locales/en/common.json, packages/apps/tools/src/components/Common/WalletConnectButton/index.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/SidePanel/index.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/SidePanel/outline.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/SidePanel/results.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/SidePanel/styles.css.ts, packages/apps/tools/src/components/Global/ModuleExplorer/SidePanel/utils.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/editor.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/index.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/types.ts, packages/apps/tools/src/components/Global/ModuleExplorer/utils.ts, packages/apps/tools/src/components/Global/ResourceLinks/index.tsx, packages/apps/tools/src/pages/transactions/module-explorer/index.tsx, packages/apps/tools/src/services/utils/transform.ts
---
- https://app.asana.com/0/0/1205488683630283
=> Feat/module explorer redesign pt. II

.changeset/lemon-socks-sleep.md, packages/libs/client/src/composePactCommand/utils/payload.ts
Fixed the issue with continuation to ensure that the proof is a string before utilizing string methods.
This will address the issue https://github.com/kadena-community/kadena.js/issues/935
=> fix(client): check continuation proof type before using string methods

.changeset/thirty-pandas-talk.md, packages/apps/graph/README.md, packages/apps/graph/src/scripts/devnet/index.ts
Due to awaiting the result of previous transactions, there's already an in-built timeout. For that reason, we are reducing the default timeout to 100ms
---
- https://app.asana.com/0/0/1205746428272055
=> [@kadena/graph] Change default timeout interval to 100ms

.changeset/tricky-fishes-sit.md, packages/libs/cryptography-utils/jest.config.js, packages/libs/cryptography-utils/package.json, packages/libs/cryptography-utils/src/tests/genKeyPair.test.ts, packages/libs/cryptography-utils/tsconfig.json, packages/libs/cryptography-utils/vitest.config.ts, packages/libs/kadena.js/jest.config.js, packages/libs/kadena.js/package.json, packages/libs/kadena.js/tsconfig.json, packages/libs/kadena.js/vitest.config.ts, pnpm-lock.yaml
This PR migrates 2 packages from Jest to Vitest:
- kadena.js
- cryptography-utils
=> Migrate kadena.js, cryptography-utils from jest to vitest

.changeset/three-planets-laugh.md, .syncpackrc.js, packages/apps/docs/package.json, packages/libs/cryptography-utils/README.md, packages/tools/e2e-tests/package.json, packages/tools/markdown/package.json, packages/tools/markdown/src/index.ts, pnpm-lock.yaml
Fixes the error from the `@kadena-dev/markdown` plugin:
=> Update some dependencies + fix local `pnpm turbo format`

.changeset/cyan-countries-joke.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/01-getting-started.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/02-running-devnet.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/03-admin-account.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/04-namespaces.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/05-keysets.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/06-smart-contract.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/07-nominate-candidates.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/08-voting.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/09-gas-station.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/index.md
There were many small errors, like spelling, grammar, broken sentences, copy-paste errors, etc. that needed to be fixed to make the tutorial more professional.
=> chore(docs): revision election dApp tutorial

.changeset/modern-clocks-look.md, common/changes/@kadena/chainweb-stream-client/chore-chainweb-stream-client-change-default-export_2023-07-19-12-19.json, packages/libs/chainweb-stream-client/README.md, packages/libs/chainweb-stream-client/etc/chainweb-stream-client.api.md, packages/libs/chainweb-stream-client/package.json, packages/libs/chainweb-stream-client/src/examples/index.ts, packages/libs/chainweb-stream-client/src/index.ts
Default export didn't work with out CJS-targeted output
Also broke the example in the README
=> @kadena/chainweb-stream-client - Changed default export at index to named export

.changeset/three-toys-reply.md, packages/apps/tools/next.config.js, packages/apps/tools/package.json, packages/libs/chainweb-node-client/package.json, packages/libs/chainweb-node-client/src/tests/listen.test.ts, packages/libs/chainweb-node-client/src/tests/local.test.ts, packages/libs/chainweb-node-client/src/tests/poll.test.ts, packages/libs/chainweb-node-client/src/tests/send.test.ts, packages/libs/chainweb-node-client/src/tests/spv.test.ts, packages/libs/chainwebjs/package.json, packages/libs/chainwebjs/src/tests/blocks.test.ts, packages/libs/chainwebjs/src/tests/cuts.test.ts, packages/libs/chainwebjs/src/tests/events.test.ts, packages/libs/chainwebjs/src/tests/headers.test.ts, packages/libs/chainwebjs/src/tests/transactions.test.ts, packages/libs/client/package.json, packages/libs/client/src/client/api/tests/runPact.test.ts, packages/libs/client/src/client/api/tests/spv.test.ts, packages/libs/client/src/client/api/tests/status.test.ts, packages/libs/client/src/client/tests/client.test.ts, packages/libs/client/src/signing/chainweaver/tests/signWithChainweaver.test.ts, packages/libs/react-components/package.json, packages/libs/react-ui/package.json, packages/tools/eslint-config/profile/lib.js, packages/tools/pactjs-cli/package.json, packages/tools/pactjs-cli/src/retrieve-contract/tests/retrieve-contract.test.ts, packages/tools/pactjs-cli/src/utils/tests/callLocal.test.ts, packages/tools/pactjs-cli/src/utils/tests/retrieveContractFromChain.test.ts, pnpm-lock.yaml
Coincidentally, MSW v2 was released the day we've merged all the tests to Vitest + MSW v1.
So here is part 2, v2. More details
- https://mswjs.io/blog/introducing-msw-2.0/
- https://mswjs.io/docs/migrations/1.x-to-2.x
The other changes were unfortunately necessary due to some dependency conflicts. My advice here: get rid of Webpack and Babel whenever possible. Switch to SWC in Next.js (not sure why Nxt.js keeps holding on to building with Webpack).
=> Migrate from MSW 1.3.2 → 2.0.0

.changeset/hungry-knives-refuse.md, package.json, packages/apps/tools/package.json, packages/apps/tools/vitest.config.ts, packages/libs/bootstrap-lib/package.json, packages/libs/bootstrap-lib/vitest.config.ts, packages/libs/chainweb-node-client/package.json, packages/libs/chainweb-node-client/vitest.config.ts, packages/libs/chainweb-stream-client/package.json, packages/libs/chainweb-stream-client/vitest.config.ts, packages/libs/chainwebjs/package.json, packages/libs/chainwebjs/vitest.config.ts, packages/libs/client-utils/package.json, packages/libs/client/package.json, packages/libs/cryptography-utils/package.json, packages/libs/cryptography-utils/vitest.config.ts, packages/libs/kadena.js/package.json, packages/libs/kadena.js/vitest.config.ts, packages/libs/pactjs-generator/package.json, packages/libs/pactjs-generator/vitest.config.ts, packages/libs/pactjs/package.json, packages/libs/pactjs/vitest.config.ts, packages/libs/react-ui/package.json, packages/libs/react-ui/vitest.config.ts, packages/tools/kda-cli/package.json, packages/tools/kda-cli/vitest.config.ts, packages/tools/pactjs-cli/package.json, packages/tools/shared-config/package.json, packages/tools/shared-config/vitest.config.js, pnpm-lock.yaml
Two interesting settings perhaps to keep in mind, copy-pasted from the base config:
```ts
module.exports = defineConfig({
test: {
coverage: {
enabled: false, // It's enabled in CI (root package.json)
thresholdAutoUpdate: false, // Should be enabled? Too precise though, annoying in CI if missed by 0.01%
},
},
});
```
=> Re-add coverage + initial thresholds

.changeset/kind-students-promise.md, packages/tools/pactjs-cli/src/contract-generate/generate.ts, packages/tools/pactjs-cli/src/contract-generate/index.ts
Add the **--parse-tree-path** option to **pactjs contract-generate** in order to store the parse tree on disk
```bash
pactjs contract-generate --parse-tree-path ./tree.json  --contract coin --api https://api.chainweb.com/chainweb/0.0/mainnet01/chain/0/pact;
```
=> feat(pactjs-cli): add option to store parse tree on disc

.changeset/slow-schools-compete.md, packages/libs/react-ui/.storybook/preview.ts, packages/libs/react-ui/src/index.ts, packages/libs/react-ui/src/styles/global.css.ts
The KodeMono font wasn't working becuase it was being loaded in a css file. This moves it to the component index file so that when someone imports a component, the font will be applied
=> fix(@kadena/react-ui): Fix KodeMono font

.changeset/pretty-balloons-love.md, packages/libs/client-utils/src/coin/create-account.ts, packages/libs/client-utils/src/coin/rotate.ts, packages/libs/client-utils/src/coin/transfer-create.ts, packages/libs/client-utils/src/coin/transfer-crosschain.ts, packages/libs/client/src/composePactCommand/README.md, packages/libs/client/src/composePactCommand/utils/addData.ts, packages/libs/client/src/composePactCommand/utils/tests/addKeyset.test.ts, packages/libs/client/src/createTransactionBuilder/createTransactionBuilder.ts
Set the type to correct values "keys-all" | "keys-any" | "keys-2"
=> Fix client predicate type

.changeset/five-rockets-beg.md, packages/libs/react-ui/src/components/Layout/Box/Box.stories.tsx, packages/libs/react-ui/src/components/Layout/Box/Box.tsx, packages/libs/react-ui/src/components/Layout/Grid/Grid.stories.tsx, packages/libs/react-ui/src/components/Layout/Grid/GridRoot.tsx, packages/libs/react-ui/src/components/Layout/Stack/Stack.stories.tsx, packages/libs/react-ui/src/components/Layout/Stack/Stack.tsx
Added `overflow` as a prop to the box, stack, and grid components
=> chore(@kadena/react-ui): Add overflow as a prop to layout components

.changeset/spotty-suits-explode.md, packages/apps/docs/src/pages/build/guides/election-dapp-tutorial/09-gas-station.md
There is a cleaner way to implement `defun create-gas-payer-guard:guard` from the `gas-payer-v1` interface.
=> feat(docs): refactor voting dapp tutorial gas station implementation

.changeset/quick-islands-care.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/Query/account.ts, packages/apps/graph/src/graph/Query/chainAccount.ts, packages/apps/graph/src/graph/objects/ChainModuleAccount.ts, packages/apps/graph/src/graph/objects/ModuleAccount.ts, packages/apps/graph/src/graph/types/graphql-types.ts, packages/apps/graph/src/services/account-service.ts, packages/apps/graph/src/utils/chains.ts
- Use an ObjectRef instead of a SchemaType to define the Node.
- Add an `id` option to build the unique identifier. Pothos will base64 encode it for you. Do not use parse as there is a bug in the pothos relay plugin which can cause the return of duplicate/incorrect data.
- Add an `isTypeOf` function that checks if the incoming object is actually the type that is being described.
- Add a `loadOne` function to support the `node` and `nodes` query. You don't need to add `loadMany` to support `nodes`, only if specific logic is required that differs from a loadOne.
=> [@kadena/graph] More GraphQL types extend Node, and use of Promise optimizations

.changeset/slow-scissors-provide.md, packages/apps/graph/package.json, packages/apps/graph/src/devnet/simulation/simulate.ts
=> [@kadena/graph] Simulate script error and inclusion of build in start script (Fix)

.changeset/sweet-cougars-invite.md, .github/workflows/ci.yml, packages/libs/react-ui/src/components/Card/Card.css.ts, packages/libs/react-ui/src/components/Card/Card.stories.tsx, packages/libs/react-ui/src/components/Card/Card.test.tsx, packages/libs/react-ui/src/components/Card/Card.tsx
- Removed the `stacked` prop as it wasn't being used at all and can be easily achieved by using the `Divider` within the `Card` component
- Updated the disabled state to look closer to existing designs
=> fix(@kadena/react-ui): Update Card Component

.changeset/nice-panthers-provide.md, packages/apps/docs/README.md
In setting up my own local development environment for the `docs` application, I needed to do a little more than captured in the original ReadMe (Asana task https://app.asana.com/0/1205619636589593/1205727631325168).
I edited the content based on my experience (and Albert's help sorting out my environment) so far. This PR doesn't cover the actual contribution process or anything about how to make changes to the information architecture.
Asana task: https://app.asana.com/0/1205619636589593/1205997198575555
`pnpm test` fails for me:
```
@kadena/chainwebjs#test: command (/Users/lisagunn/KADENA/kadena.js/packages/libs/chainwebjs) pnpm run test run --coverage exited (-1)
Tasks:    33 successful, 41 total
Cached:    0 cached, 41 total
Time:    1m40.553s 
Failed:    @kadena/chainwebjs#test
ERROR …
```
=> [docs] Update the instructions for getting the docs web server running locally in its current state

.changeset/forty-pumas-study.md, packages/apps/docs/package.json, packages/apps/docs/src/components/Search/components/SearchResults.tsx
bugfix for the initial search. when there is no tabname saved in localstorage the search did not trigger
=> [DOCS]fix: initial search

.changeset/curly-terms-obey.md, packages/apps/docs/src/pages/index.tsx
Changed the "Introduction" heading to be less generic, modified the description.
Changed the heading for tutorials to be more descriptive.
Made a couple of typo fixes.
Consolidated the two rows of "General" topics into one section.
Changed the titles for the lower set of links.
=> [docs] Change some text and layout on the top-level docs home page

.changeset/tough-rabbits-poke.md, packages/tools/kadena-cli/src/config/commands/configInit.ts, packages/tools/kadena-cli/src/constants/devnets.ts, packages/tools/kadena-cli/src/devnet/commands/devnetCreate.ts, packages/tools/kadena-cli/src/devnet/commands/devnetDelete.ts, packages/tools/kadena-cli/src/devnet/commands/devnetList.ts, packages/tools/kadena-cli/src/devnet/commands/devnetManage.ts, packages/tools/kadena-cli/src/devnet/commands/devnetRun.ts, packages/tools/kadena-cli/src/devnet/commands/devnetStop.ts, packages/tools/kadena-cli/src/devnet/commands/devnetUpdate.ts, packages/tools/kadena-cli/src/devnet/commands/start.ts, packages/tools/kadena-cli/src/devnet/index.ts, packages/tools/kadena-cli/src/devnet/init.ts, packages/tools/kadena-cli/src/devnet/utils/devnetDisplay.ts, packages/tools/kadena-cli/src/devnet/utils/devnetHelpers.ts, packages/tools/kadena-cli/src/devnet/utils/docker.ts, packages/tools/kadena-cli/src/prompts/devnet.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts, packages/tools/kadena-cli/src/utils/helpers.ts
=> feat(kadena-cli): add devnet commands to kadena-cli

.changeset/gentle-plants-judge.md, packages/tools/scripts/generate-packages-json.ts
Whenever the release workflow is triggered one of two things can happen:
1. A Pull Request `[CI] Release ` is created, waiting to be merged.
2. All pending packages are published to the NPM registry.
This PR solves an issue in the first case. When creating the PR the workflow automatically also formats the root of the monorepo and bumps versions in the `packages.json`.  This currently leads to an issue where the build for the aforementioned pull request fails because it does not adhere to linting standards.  These standards require all JSON files to end with an empty line.
This PR adds an empty line at the end of the packages.json when bumping the versions.
=> Add a new line in packages.json

.changeset/nine-toys-remain.md, packages/libs/client/src/composePactCommand/utils/payload.ts, packages/libs/client/src/createTransactionBuilder/createTransactionBuilder.ts, packages/libs/client/src/interfaces/type-utilities.ts
Using Pact.module is the recommended way for creating pact code, however using just a string is valid as well and in some scenarios is more convenient.
execution already accepts pure strings but with this update execution function can also extract capability types from the pure string codes - of course you still need to install the contract type.
```TS
const transaction = Pact.builder
.execution(
`(coin.transfer ${sender} ${receiver} ${amount})`
)
.addSigner(keyFromAccount(sender), (withCapability) => [
withCapability('coin.GAS'),
// this type infers from the string code
withCapability('coin.TRANSFER', sender, receiver, amount),
])
.setMeta({ chainId: '0', senderAccount: sender })
.setNetworkId(NETWORK_ID)
.createTransaction();
```   
this can be used with Pact.modules
```TS
const …
```
=> feat(client): extract capability type from string codes

.changeset/lovely-lies-battle.md, packages/apps/graph/.npmrc, packages/apps/graph/package.json, packages/apps/graph/src/devnet/crosschain-transfer.ts, packages/apps/graph/src/index.ts, packages/apps/graph/tsconfig.json
- Added a bin reference to dist, making it possible to for example run `npx kadena-graph` to start the graphql server.
- Changed the package.json to a releasable format.
- Fixed module aliases for the built version.
=> [@kadena/graph] Made graph a releasable package

.changeset/tidy-trains-fly.md, packages/apps/graph/.env.example, packages/apps/graph/src/graph/builder.ts, packages/apps/graph/src/index.ts, packages/apps/graph/src/plugins/extensions.ts, packages/apps/graph/src/utils/dotenv.ts
With the help of @hayes: https://github.com/hayes/pothos/issues/1094
Query:
```graphql
query ($hash: String!) {
block(hash: $hash) {    
id
chainId
creationTime
epoch
hash
height
payloadHash
powHash
predicate
minerAccount {
guard {
keys
predicate
}
}
}
}
```
Result when `TRACING_EXPOSED` and `COMPLEXITY_EXPOSED` are set to `true`:
```
{
"data": {
"block": {
"chainId": 5,
"creationTime": "2023-11-09T14:13:29.176Z",
"epoch": "2023-11-09T14:06:00.656Z",
"hash": "WzpZ6ElQKcSpb_Xuhrm_6wSG5jT7zWLMWhmckKUQgH0",
"height": 6444,
"payloadHash": "U4FUAkmPk5J6TvGfZYycxrCrVd2YHtEVSaFqDg4qiAw",
"powHash": "cfe99c5912299b5715c7e0c0a585b228b7297f4397cd132239fe51b89b84fe1e",
"predicate": "keys-all",
"id": "QmxvY2s6V3pwWjZFbFFLY1NwYl9YdWhybV82d1NHNWpUN3pXTE1XaG1ja0tVUWdIMA==",
"minerAccount": {
"guard": { …
```
=> [@kadena/graph] Exposed tracing to extensions

.changeset/itchy-spoons-reflect.md, packages/libs/react-ui/src/components/Button/NewButton.css.ts, packages/libs/react-ui/src/components/Button/NewButton.spec.tsx, packages/libs/react-ui/src/components/Button/NewButton.stories.tsx, packages/libs/react-ui/src/components/Button/NewButton.tsx, packages/libs/react-ui/src/components/ProgressCircle/ProgressCircle.spec.tsx, packages/libs/react-ui/src/components/ProgressCircle/ProgressCircle.stories.tsx, packages/libs/react-ui/src/components/ProgressCircle/ProgressCircle.tsx, packages/libs/react-ui/src/components/ProgressCircle/index.ts, packages/libs/react-ui/src/styles/atoms.css.ts, packages/libs/react-ui/src/styles/tokens/contract.css.ts, packages/libs/react-ui/src/styles/tokens/dark.css.ts, packages/libs/react-ui/src/styles/tokens/light.css.ts, packages/libs/react-ui/src/utils/testId.ts
1. Use react aria which come with one major change is `onPress` instead of `onClick` read more about why https://react-spectrum.adobe.com/blog/building-a-button-part-1.html. we added `onClick` to allow easy migration but it is deprecated and we should not use it for new code.
2. Unify the `IconButton` and `Button` components using `<Button icon={<SomeIcon/>} />` instead of `IconButton`.
3. Change some props names to be consistent with react-aria naming `compact` -> `isCompact`.
4. `Button` is not a polymorphic component anymore we will have a separate link component.
5. `iconAlign` is replaced by specific icon renders props `startIcon` and `endIcon`, and `icon` is repurposed for icon-only buttons aka `IconButton`.
6. Use `recipe` instead of individual `styleVariants`. 
7. `color` and …
=> New aria complete button without new tokens

.changeset/proud-chairs-run.md, packages/tools/pactjs-cli/src/contract-generate/index.ts, packages/tools/pactjs-cli/src/contract-generate/tests/index.test.ts, packages/tools/pactjs-cli/src/contract-generate/utils.ts, packages/tools/pactjs-cli/src/utils/retrieveContractFromChain.ts
NetworkId and chainId will be extracted from the url params and added to the tx.
=> fix(pactjs-cli): fixed incorrect network by extracting data from api field

.github/workflows/ci.yml
This PR also triggers CI to run on main. We've seen various scenario's where main is broken and we notice quite late. This at least informs us when this occurs.
=> [chore] update CI to also run on main

.changeset/flat-carrots-prove.md, packages/apps/graph/package.json, packages/apps/graph/src/devnet/deployment/index.ts, packages/apps/graph/src/devnet/deployment/marmalade/README.md, packages/apps/graph/src/devnet/deployment/marmalade/deploy.ts, packages/apps/graph/src/devnet/deployment/marmalade/namespace.ts, packages/apps/graph/src/devnet/simulation/index.ts
We can pass a chain argument in the cli now, when calling `pnpm deploy:marmalade`
=> [@kadena/graph] Allow marmalade deployment on multiple chains (Feat)

.changeset/mighty-colts-help.md, packages/apps/graph-client/src/components/events-table/events-table.tsx, packages/apps/graph-client/src/components/extended-transactions-table/extended-transactions-table.tsx, packages/apps/graph-client/src/graphql/queries.graph.ts, packages/apps/graph-client/src/graphql/subscriptions.graph.ts, packages/apps/graph-client/src/pages/account/transactions/[fungible]/[account].tsx, packages/apps/graph-client/src/pages/event/[key].tsx, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/index.ts, packages/apps/graph/src/graph/objects/event.ts, packages/apps/graph/src/graph/query/events.ts, packages/apps/graph/src/graph/query/transactions.ts, packages/apps/graph/src/graph/query/transfers.ts, packages/apps/graph/src/graph/subscription/event.ts, packages/apps/graph/src/services/complexity.ts
In this PR:
- `event` and `events` queries added.
- Page in the graph client added for the events.
- `transfer` and `transaction` queries added for single record retrieval.
=> [@kadena/graph] Event queries added

.changeset/funny-ants-sort.md, packages/apps/graph/src/devnet/simulation/coin/crosschain-transfer.ts, packages/apps/graph/src/graph/objects/transfer.ts
For this, I tested a couple of scenarios:
- One using Prisma's query methods and ensuring type safety; this is the one included in the PR
- The other way was by using a single query, which although it removed complexity, added some other downsides because it made use of `$queryRaw`. These downsides had to do with the manual mapping of fields, which are not automatically mapped to our defined Prisma models, and no type safety. 
I ended up doing some tracing tests as well and saw that although the current complexity is 2 (higher than the single query way), it does take less time.
**TLDR: Reduced complexity from 4 -> 2. It was possible to bring it down to 1 but it had no real improvement**
Note: also fixed a small encountered issue in cross-chain transfers (simulation)
=> [@kadena/graph] Reduce complexity of cross-chain counterpart lookup in Transfers (Feat)

.changeset/dirty-bats-learn.md, packages/libs/react-ui/src/components/Breadcrumbs/Breadcrumbs.css.ts, packages/libs/react-ui/src/components/Breadcrumbs/Breadcrumbs.stories.tsx, packages/libs/react-ui/src/components/Breadcrumbs/Breadcrumbs.test.tsx, packages/libs/react-ui/src/components/Breadcrumbs/Breadcrumbs.tsx, packages/libs/react-ui/src/components/Breadcrumbs/BreadcrumbsItem.tsx, packages/libs/react-ui/src/components/Breadcrumbs/index.tsx
Updated the Breadcrumbs component to use `useBreadcrumbs` from react-aria.
=> chore(@kadena/react-ui): Use react-aria in Breadcrumbs component

.github/CODEOWNERS
In This PR I've added additional codeowners for all packages that I am either the sole codeowner or one of two. This is to prevent that in my absence other colleages are unable to release work related to these packages.
=> Add additional codeowners to prevent blocking colleagues in my absence.

.changeset/khaki-wolves-teach.md, packages/libs/client-utils/src/nodejs/index.ts, packages/libs/client-utils/src/nodejs/test/yaml-converter.test.ts, packages/libs/client-utils/src/nodejs/yaml-converter.ts
Add the `createPactCommandFromStringTemplate` and `getPartsAndHoles` method to `@kadena/client-utils/nodejs`
This allows finding holes in templates to data can be collected, and subsequently parsing the template with data into a transaction directly from strings, removing the need for filesystem usage.
=> [client-utils]feat: add template parsing from string to yaml converter

.changeset/tender-schools-sip.md, packages/libs/client-utils/src/example-contract/use-coin.ts, packages/libs/client/etc/client.api.md, packages/libs/client/src/signing/chainweaver/signWithChainweaver.ts, packages/libs/client/src/signing/chainweaver/tests/signWithChainweaver.test.ts
Adds support for adding a custom url for `signWithChainweaver`. 
Closes #1232
=> feat: adds support for a custom Chainweaver url for signWithChainweaver

.changeset/strange-birds-buy.md, packages/apps/graph/src/graph/objects/block.ts, packages/apps/graph/src/graph/objects/event.ts, packages/apps/graph/src/graph/objects/miner-key.ts, packages/apps/graph/src/graph/objects/signer.ts, packages/apps/graph/src/graph/objects/transaction.ts, packages/apps/graph/src/graph/objects/transfer.ts, packages/apps/graph/src/graph/subscription/events.ts, packages/apps/graph/src/graph/subscription/transaction.ts, packages/apps/graph/src/services/tracing/trace-analyser.ts, packages/apps/graph/src/services/tracing/trace-service.ts
With this change, Prisma only queries the fields that were requested from the GraphQL query.
With the help of @hayes: https://github.com/hayes/pothos/issues/1131
=> [@kadena/graph] Performance improvements for Prisma queries

.changeset/pink-lobsters-retire.md, packages/libs/pactjs-generator/src/contract/parsing/pactParser.ts, packages/libs/pactjs-generator/src/contract/parsing/utils/pactGrammar.ts, packages/libs/pactjs-generator/src/contract/parsing/utils/tests/pactGrammar.test.ts
Add events to the parse tree. 
this could happen for defun and defpact
=> feat(pactjs-generator): add emit-event to the parse tree

.changeset/serious-rocks-reply.md, packages/libs/react-ui/src/components/Form/Combobox/Combobox.stories.tsx, packages/libs/react-ui/src/components/Form/Combobox/Combobox.tsx, packages/libs/react-ui/src/components/Form/Select/Select.css.ts, packages/libs/react-ui/src/components/Form/Select/Select.stories.tsx, packages/libs/react-ui/src/components/Form/Select/SelectButton.tsx
- Added some padding between the icons in the select component
- Added `startIcon` to the combobox
=> chore(@kadena/react-ui): Update select spacing and added "startIcon" to combobox

.changeset/stupid-falcons-notice.md, packages/libs/react-ui/src/components/Table/TBody.tsx, packages/libs/react-ui/src/components/Table/THead.tsx, packages/libs/react-ui/src/components/Table/Table.tsx, packages/libs/react-ui/src/components/Table/Td.tsx, packages/libs/react-ui/src/components/Table/Th.tsx, packages/libs/react-ui/src/components/Table/Tr.tsx
This is so that the graph client can make compact tables.
It's a quick fix until the Table component is completely refactored.
=> [@kadena/react-ui] Classnames to table components

.changeset/funny-moles-deliver.md, packages/tools/create-kadena-app/package.json, pnpm-lock.yaml
`"preinstall": "npx only-allow pnpm"` shouldn't be available. This makes it only to allow from `pnpm`
=> fix(create-kadena-app): remove pnpm only installation step

packages/apps/tools/src/pages/transactions/cross-chain-transfer-tracker/index.tsx
Using the Link (client-side rendering) causes some issues for us (see attached ticket). This is a quick fix. Later we will refactor the target page code and the Link can and will be used again
---
- https://app.asana.com/0/0/1206487450523399
=> Fix Tracker -> Finisher routing issue

.github/workflows/ci.yml
We have enabled branch protection to require certain checks to pass before being allowed to merge to main. Unfortunately these settings are hidden away behind administrative permissions for the repository making them tedious to maintain. Especlally now that we're adding various tests as matrix builds, having to add them individually to branch protection is cumbersome. 
After some research, it seems I am not the only one that is frustrated with how GitHub Actions implements these features. I made these checks for a reason, why the heck would they not be required?
The solution appears to be a GitHub action called [Alls-Green](https://github.com/re-actors/alls-green). With this Action we can add 1 additional check for CI (and make _that_ required) which iterates over all other jobs in the …
=> feat: Add CI gate to enforce all status checks pass

packages/libs/react-ui/src/components/Form/Select/Select.test.tsx
This PR increases the timeout for a few slow tests, while this solution is far from ideal it is currently blocking other PR's and there is insufficient time to further investigate.
It seems there are various scenario's in which Vitest performs _much_ slower compared to Jest or other alternatives. This primiarly seems to be related to isolation of test cases and how other dependencies are imported in tests (or components under test).
See https://dev.to/thejaredwilcurt/improving-vitest-performance-42c6
We should follow up with further investigation
=> temp: Increase timeout

.changeset/cuddly-dogs-turn.md, packages/tools/kadena-cli/src/account/commands/accountAddFromWallet.ts, packages/tools/kadena-cli/src/account/commands/accountAddManual.ts, packages/tools/kadena-cli/src/account/utils/accountHelpers.ts, packages/tools/kadena-cli/src/account/utils/createAccountConfigFile.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts
account commands with `--quiet` flag needs few defaults and additional check. Fixing those as part of this PR.
=> fix(account): add default values when user use --quiet option

packages/tools/kadena-cli/src/networks/commands/networkCreate.ts, packages/tools/kadena-cli/src/networks/utils/networkHelpers.ts, packages/tools/kadena-cli/src/prompts/generic.ts, packages/tools/kadena-cli/src/prompts/network.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts, packages/tools/kadena-cli/src/utils/helpers.ts
`networks create` command failing in `main`
- Also made `networkId` and `networkHost` are required fields. Without networkId and host it's not really makes sense to have a network
- Added zod schema parsing before writing into a network file.
=> fix(networks): create command

packages/tools/kadena-cli/src/account/commands/accountDetails.ts, packages/tools/kadena-cli/src/account/utils/__tests__/accountDetails.test.ts, packages/tools/kadena-cli/src/keys/commands/keysDecrypt.ts, packages/tools/kadena-cli/src/keys/commands/keysPlainGenerate.ts, packages/tools/kadena-cli/src/keys/utils/keysDisplay.ts, packages/tools/kadena-cli/src/networks/commands/networkDelete.ts, packages/tools/kadena-cli/src/networks/commands/networkManage.ts, packages/tools/kadena-cli/src/prompts/network.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts
- Improved error message for account details not found in chain
- instead of network name, `undefined` is shown in the network delete confirmation prompt
- Fix keys gen-plain --key-alias="alpha22" --key-amount="5" 
the file name shown in the console and the key's generated are not same 
- keys gen-plain --quiet   => `keyAlias`  and `key message` set required field
- Updated Wallet `verify password` option to `-vp` . `-p` already used by password
- Make network select option as required field as part of network manage and delete command
=> fix(cli): minor bugs + improvements

packages/apps/docs/src/components/Layout/basestyles.css.ts
By default, we can swipe right/left to move next/prev page history using fingers gesture. This is not working as part of docs website. This PR fixes it. 
https://app.asana.com/0/1205619636589593/1206579624288339/f
=> fix(docs): allow swipe prev/next browser history

.changeset/happy-crabs-suffer.md, packages/apps/graph-client/src/graphql/fields/block.graph.ts, packages/apps/graph-client/src/graphql/queries.graph.ts, packages/apps/graph-client/src/pages/block/overview/[hash].tsx, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/objects/block.ts
- Removed Block.parentHash
- Removed Block.predicate: String, predicate can be accessed through MinerAccount
- Added Block.events property to access all events from block
- Added Events to block view in graph-client
https://app.asana.com/0/1205801361945248/1206591792021826
=> [@kadena/graph] Added Events to Block and removed obsolete Block fields

.changeset/cool-laws-punch.md, packages/apps/graph/README.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/objects/event.ts, packages/apps/graph/src/graph/query/events.ts, packages/apps/graph/src/graph/subscription/events.ts, packages/apps/graph/src/utils/errors.ts, packages/apps/graph/src/utils/prisma-json-columns.ts
Some columns in the database are of type `jsonb`. To query these columns, you can supply a stringified JSON object that matches the [JSON object property filters](https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/working-with-json-fields#filter-on-object-property) from Prisma.
An example of such a filter parameter value could be: `events(parametersFilter: "{\"array_starts_with\": \"k:abcdefg\"}")`, in which case, the `parameters` column is a `jsonb` type column which is filtered to only include rows where the value contains an array that has the string `k:abcdefg` on index 0.
Queries that allow such filters:
- `parametersFilter` on the `events` query and `events` subscription.
---
- …
=> [@kadena/graph] Added more filters to Events query and subscription

packages/tools/kadena-cli/src/account/commands/accountDetails.ts, packages/tools/kadena-cli/src/account/commands/accountFund.ts, packages/tools/kadena-cli/src/account/utils/__tests__/accountDetails.test.ts, packages/tools/kadena-cli/src/account/utils/accountHelpers.ts, packages/tools/kadena-cli/src/prompts/account.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts
For `account details` command, allow users to enter account name manually
https://app.asana.com/0/1205969628270714/1206634146772867/f
=> feat(account): allow manual input for account details

packages/apps/tools/src/pages/faucet/new/index.tsx
=> [@tools-website] Fix: account name is reset on submitting form on Faucet

.changeset/fast-humans-admire.md, .changeset/many-crabs-smash.md, packages/libs/client-utils/etc/client-utils-coin.api.md, packages/libs/client/src/tests/utils.test.ts, packages/libs/client/src/utils/pact-helpers.ts, packages/libs/client/src/utils/parseAsPactValue.ts, packages/libs/client/src/utils/tests/createTransaction.test.ts, packages/libs/client/src/utils/tests/parseAsPactValue.test.ts, packages/libs/types/etc/types.api.md, packages/libs/types/src/PactValue.ts
This PR fixes the issue with generating pact expression when the arguments are arrays or objects
=> fix(client): parse as pact value for objects and arrays

packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/account/accountOptions.ts, packages/tools/kadena-cli/src/account/commands/accountDelete.ts, packages/tools/kadena-cli/src/account/commands/accountFund.ts, packages/tools/kadena-cli/src/account/commands/accountList.ts, packages/tools/kadena-cli/src/account/commands/accountResolveAddressToName.ts, packages/tools/kadena-cli/src/account/commands/accountResolveNameToAddress.ts, packages/tools/kadena-cli/src/account/index.ts, packages/tools/kadena-cli/src/account/utils/accountHelpers.ts, packages/tools/kadena-cli/src/prompts/account.ts
https://app.asana.com/0/1205969628270714/1206634146772872/f
`kadena account delete` sub command 
User can select multiple accounts from the list of aliases
Example commands:
Single alias
`kadena account delete --account-alias="devnet_account" --confirm`
All alias 
`kadena account delete --account-alias="all" --confirm`
~Multiple aliases:~
~`kadena account delete --account-alias="devnet_account,testnet_account" --confirm`~
removed multiple aliases to align with other commands delete option
=> feat(account): implement account delete sub command

packages/tools/kadena-cli/src/account/accountOptions.ts, packages/tools/kadena-cli/src/account/commands/accountDelete.ts, packages/tools/kadena-cli/src/account/commands/accountDetails.ts, packages/tools/kadena-cli/src/account/commands/accountFund.ts, packages/tools/kadena-cli/src/account/commands/accountList.ts, packages/tools/kadena-cli/src/account/utils/accountHelpers.ts, packages/tools/kadena-cli/src/constants/account.ts, packages/tools/kadena-cli/src/prompts/account.ts
- Removed the directory not exists error from `getAllAccounts` helper method and moved to specific actions. Because this was making an prompt to thrown an error.
- Made account details output as tabular data
=> refactor(cli): move errors from helper to action

packages/tools/kadena-cli/src/prompts/network.ts, packages/tools/kadena-cli/src/prompts/tx.ts, packages/tools/kadena-cli/src/tx/commands/txList.ts, packages/tools/kadena-cli/src/tx/utils/txHelpers.ts
- Ensure networks configuration for non-existent networks directory or networks directory empty
- List only unsigned transactions on - `tx sign`
=> fix(cli): networks empty + tx list on unsigned

.changeset/nasty-onions-think.md, packages/apps/graph/src/graph/builder.ts, packages/apps/graph/src/graph/objects/transaction.ts, packages/apps/graph/src/index.ts, packages/apps/graph/src/services/chainweb-node/account-details.ts, packages/apps/graph/src/services/chainweb-node/estimate-gas-limit.ts, packages/apps/graph/src/services/chainweb-node/raw-query.ts, packages/apps/graph/src/services/systems-check.ts, packages/apps/graph/src/utils/get-network-id.ts, packages/apps/graph/src/utils/network.ts
The goal is to dynamically get the `networkId` from `/info` instead of `.env` variable.
**Note**: The simulation and deployment scripts are eventually going to be removed so until then I'll leave the `dotenv.NETWORK_ID`. 
In any case, I have implemented the changes so that only simulation and deployment scripts are dependent on this
---
- https://app.asana.com/0/0/1206753124451137
=> [@kadena/graph] Dynamic Network Id (Feat)

.github/CODEOWNERS
Empty entry for `apps/docs` so anyone can approve
=> chore(monorepo): removed codeowners for `docs` so anyone can approve

packages/libs/client-utils/etc/client-utils-core.api.md, packages/libs/client-utils/src/core/cross-chain.ts, packages/libs/client-utils/src/core/estimate-gas.ts, packages/libs/client-utils/src/core/global-config.ts, packages/libs/client-utils/src/core/index.ts, packages/libs/client-utils/src/core/preflight.ts, packages/libs/client-utils/src/core/query-all-chains.ts, packages/libs/client-utils/src/core/read-dirty.ts, packages/libs/client-utils/src/core/submit-and-listen.ts, packages/libs/client-utils/src/core/test/cross-chain-client.test.ts, packages/libs/client-utils/src/core/test/preflight-client.test.ts, packages/libs/client-utils/src/core/test/submit-client.test.ts, packages/libs/client-utils/src/core/utils/helpers.ts, packages/libs/client-utils/src/core/utils/test/helpers.test.ts
Introducing setGlobalConfig for clien-utils functions. 
the function accepts this interface.
```TS
interface IClientConfig {
host: string | ((options: INetworkOptions) => string);
defaults: Partial<IPactCommand>;
sign: ISignFunction;
}
```
by having this you just set this option once and then all helpers use this as the default configuration, of course each helper can still override them by passing the object implicitly.
=> feat(client-utils): global config

packages/tools/kadena-cli/src/account/commands/accountFund.ts, packages/tools/kadena-cli/src/account/utils/__tests__/createAndTransferFunds.test.ts, packages/tools/kadena-cli/src/account/utils/__tests__/fund.test.ts, packages/tools/kadena-cli/src/account/utils/__tests__/transferFund.test.ts, packages/tools/kadena-cli/src/account/utils/createAndTransferFunds.ts, packages/tools/kadena-cli/src/account/utils/fund.ts, packages/tools/kadena-cli/src/account/utils/transferFund.ts, packages/tools/kadena-cli/src/tx/commands/txSend.ts
- Print request key and explorer url
- Improve help text after funding an account
- Before sending transactions to chain validate using `local` (for account fund and tx send commands)
---
- https://app.asana.com/0/0/1206794459798420
- https://app.asana.com/0/0/1206794459798425
=> fix(account): fund command additional feedback for sending transactions + check

packages/tools/kadena-cli/src/prompts/tx.ts, packages/tools/kadena-cli/src/tx/commands/txList.ts, packages/tools/kadena-cli/src/tx/txOptions.ts, packages/tools/kadena-cli/src/tx/utils/txDisplayHelper.ts, packages/tools/kadena-cli/src/tx/utils/txHelpers.ts
- Removed the temporary fix of using `all` param
- Improved the `tx list` display instead of relying on filename extension using the transaction signed key
https://app.asana.com/0/1205969628270714/1206751469972661/f
=> refactor: get signed/unsigned transactions list

packages/tools/kadena-cli/src/account/commands/accountCreate.ts
This PR fixes a small typo in one of the responses provided by Kadena CLI.
=> fix: add missing space to log message

packages/apps/tools/src/hooks/use-is-ledger-lib-supported.ts
Fixes the infinite rerender when switching from the Transfer page to the Faucet page (using the lefthand side menu)
=> Run Ledger support hook only once, on mount

turbo.json
This PR disables caching for e2e tests. There is currently an issue with caching that we do not have a clear cut solution for yet to prevent false positives, we're disabling caching of e2e tests for now.
=> fix: disable caching for e2e tests to prevent false positives

.changeset/big-ears-burn.md, packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/constants/config.ts, packages/tools/kadena-cli/src/constants/networks.ts, packages/tools/kadena-cli/src/networks/commands/networkDefault.ts, packages/tools/kadena-cli/src/networks/commands/networkDelete.ts, packages/tools/kadena-cli/src/networks/index.ts, packages/tools/kadena-cli/src/networks/networkOptions.ts, packages/tools/kadena-cli/src/networks/utils/networkDisplay.ts, packages/tools/kadena-cli/src/networks/utils/networkHelpers.ts, packages/tools/kadena-cli/src/prompts/network.ts, packages/tools/kadena-cli/src/utils/createCommand.ts, packages/tools/kadena-cli/src/utils/createOption.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts, packages/tools/kadena-cli/src/utils/helpers.ts
- https://app.asana.com/0/0/1206807019750943
`kadena network set-default` command
- It sets default network in a specific file `.kadena/defaults/networks/__default__.yaml` 
- When user list the network they could able to see which is the default network
- When user deletes the network if it's a default network it will prompted with a warning including it will be deleted from defaults
- Whenever account gets prompted it shows the default network at the top of the list
------------------
When the `--quiet` flag is used:
- If a default network is set and no network argument is provided, the default network should be used without errors.
- If no default network is set and no network argument is provided, an …
=> feat(network): implement network set-default command

packages/apps/docs/src/docs/chainweb/compact-a-database.md
- Adds a disclaimer about Compaction stability
- Delete trailing whitespace
- Make some wording more natural
- Change recommended target-blockheight to 4.6million
- Note that target-blockheight will become unavailable in the future
=> add disclaimer about compaction stability

.changeset/purple-jars-melt.md, packages/libs/chainweb-node-client/etc/chainweb-node-client.api.md, packages/libs/chainweb-node-client/src/poll.ts, packages/libs/client-examples/src/example-contract/simple-transfer.ts, packages/libs/client-examples/src/example-contract/util/client.ts, packages/libs/client/etc/client.api.md, packages/libs/client/src/client/api/status.ts, packages/libs/client/src/client/client.ts, packages/libs/client/src/client/interfaces/interfaces.ts, packages/libs/client/src/client/tests/client.test.ts
`/poll` endpoint accepts `confirmationDepth` and returns the result if the request meets that length. It means waiting for a certain amount of blocks, then returning the result of the request. It's useful when you need to make sure the data is persisted permanently on the blockchain.
In this PR, we will add the support in the client library.
You can pass it to the `createClient` function to use it as the value on applicable functions.
```
const client = createClient("http://host-url", { confirmationDepth: 5 })
```
You can also pass it with poll options for the `pollStatus` function (which overrides the one you passed to the `createClient`).
```
const result = pollStatus(request, { confirmationDepth: 5 })
```
=> Feat/add confirmation depth to pollStatus

packages/tools/kadena-cli/src/account/commands/accountAddManual.ts, packages/tools/kadena-cli/src/account/commands/accountCreate.ts, packages/tools/kadena-cli/src/account/utils/accountHelpers.ts, packages/tools/kadena-cli/src/constants/account.ts, packages/tools/kadena-cli/src/prompts/account.ts
As part of account creation if the account is `k:account` and only one publicKeys are passed then the predicate should always be `keys-all`. When user tries to create an account with different predicates like `keys-any` or `key-2` then anyway we get the error from chain as a `Single-key account protocol violation` . 
As part of this PR, when account is k account and only one public keys are selected we make sure to display only `keys-all`  as part of predicate prompt.
---
- https://app.asana.com/0/0/1206767453052195
=> fix(account): restrict k-account + one public key predicate

packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/account/commands/accountDetails.ts, packages/tools/kadena-cli/src/account/utils/__tests__/accountDetails.test.ts, packages/tools/kadena-cli/src/networks/commands/networkDefault.ts, packages/tools/kadena-cli/src/networks/networkOptions.ts
- Add fungible flag in the readme docs for account details and fund command - https://app.asana.com/0/0/1206807019750931/1206951762878090/f
- Improve error message for account not found https://app.asana.com/0/0/1206807019750931/1206957916687828/f
- Update network default confirmation flag from `--networkDefaultConfirmation` to `--confirm` https://app.asana.com/0/0/1206807019750943/1206951762878094/f
=> fix(cli): test feedback on network set-default and account details command

.changeset/friendly-fireants-exist.md, packages/apps/graph/src/graph/objects/non-fungible-account.ts, packages/apps/graph/src/graph/objects/non-fungible-chain-account.ts
After discussing with Jermaine we reached some conclusions:
- By changing the `moduleName` to match `marmalade-v2` instead of `marmalade-v2.ledger` we include the policy-manager and concrete policies-related transactions: with this change we do get 90% of all the marmalade traffic
- There is no deterministic way to get all the transactions related to non-fungibles: a token creator can add his own policy with custom events we don't know about 
---
- https://app.asana.com/0/0/1206939031903713
=> [@kadena/graph] Alter condition to get non-fungible related transactions (Feat)

packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/tx/commands/txStatus.ts
`tx status` by default it uses the `getStatus` method to fetch the data. If the transaction not found returns an error message with an hint for the user to try it out with `poll` flag. 
If user uses the `--poll` option then it uses the `pollStatus` method to fetch the data to keep polling for a minute. If the request not found in a minute then request gets timedout. 
---
- https://app.asana.com/0/0/1206932423881496
- https://app.asana.com/0/0/1206930586643761
=> fix(tx-status): add poll option 

packages/tools/kadena-cli/src/prompts/keys.ts, packages/tools/kadena-cli/src/services/wallet/wallet.service.ts, packages/tools/kadena-cli/src/utils/globalOptions.ts, packages/tools/kadena-cli/src/utils/helpers.ts, packages/tools/kadena-cli/src/wallets/commands/walletImport.ts, packages/tools/kadena-cli/src/wallets/walletOptions.ts
=> feat(kadena-cli): convert wallet import mnemonic to prompt or file input

packages/tools/kadena-cli/src/prompts/tx.ts, packages/tools/kadena-cli/src/tx/commands/txSend.ts, packages/tools/kadena-cli/src/tx/utils/txHelpers.ts
[x] Automatically select network (id) when sending or fallback to prompt
[x] Added logging so its more clear what transactions is being send and might fail
=> feat(kadena-cli) auto select network or fallback to prompt

.changeset/curly-pumpkins-type.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/graph/objects/block.ts, packages/apps/graph/src/graph/objects/fungible-chain-account.ts, packages/apps/graph/src/graph/objects/non-fungible-chain-account.ts, packages/apps/graph/src/graph/objects/non-fungible-token-balance.ts
There were some fields exposed as IDs which resulted in these having the same type as the node IDs which can confuse. Retyped these non-id fields in the graph to their actual primitive type
---
- https://app.asana.com/0/0/1207034879037532
=> Correct non-id fields types

packages/apps/tools/src/components/Global/ModuleExplorer/SidePanel/index.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/SidePanel/outline.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/SidePanel/results.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/SidePanel/utils.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/editor.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/index.tsx, packages/apps/tools/src/components/Global/ModuleExplorer/types.ts, packages/apps/tools/src/components/Global/ModuleExplorer/utils.ts, packages/apps/tools/src/pages/modules/explorer/index.tsx, packages/apps/tools/src/services/modules/list-module.ts, packages/apps/tools/src/services/utils/transform.ts
This PR makes it possible to switch networks while having opened modules in the editor section. E.g.; you can now open the same module on the same chain on different networks in different tabs, this wasn't possible before. The network of the opened module is now also stored as part of the URL for deep linking purposes
=> Tools dApp: Module explorer - Add network info to modules

packages/tools/kadena-cli/src/constants/config.ts, packages/tools/kadena-cli/src/networks/commands/networkManage.ts, packages/tools/kadena-cli/src/networks/utils/networkHelpers.ts, packages/tools/kadena-cli/src/prompts/account.ts, packages/tools/kadena-cli/src/prompts/network.ts, packages/tools/kadena-cli/src/prompts/wallets.ts
**Refactor:**
- Currently wallet does validation for the filename contains any special characters like `\ / : * ? " < > |` but network and account not doing the same. For consistency updated it to use the same.
- Network name - only allowing alpha numeric to keep it consistent removed the alpha numeric validation
**Bug:**
`kadena network update` command - added more details in this ticket https://app.asana.com/0/1205969628270714/1207147099820716
=> fix: network update command + refactor consistent file name validation

.github/workflows/ci.yml
Do not fail on apt-update temporary workaround for [#9773](https://github.com/actions/runner-images/issues/9733) and  [#130](https://github.com/microsoft/linux-package-repositories/issues/130)
=> fix: temp workaround for apt-get update failures

.changeset/ten-dots-prove.md, packages/apps/dev-wallet/src/App/layout.tsx, packages/apps/tools/src/components/Common/Layout/partials/Header/Header.tsx, packages/apps/tools/src/components/Global/ChainSelect/index.tsx, packages/libs/react-ui/src/components/Form/Form.css.ts, packages/libs/react-ui/src/components/Form/NumberField/NumberField.tsx, packages/libs/react-ui/src/components/Form/NumberField/NumberFieldActions.tsx, packages/libs/react-ui/src/components/Form/Select/Select.css.ts, packages/libs/react-ui/src/components/Form/Select/Select.stories.tsx, packages/libs/react-ui/src/components/Form/Select/Select.tsx, packages/libs/react-ui/src/components/Form/Select/SelectButton.tsx, packages/libs/react-ui/src/components/ListBox/ListBox.css.ts, packages/libs/react-ui/src/components/ListBox/ListBox.tsx, packages/libs/react-ui/src/components/ListBox/ListBoxOption.tsx, packages/libs/react-ui/src/components/Popover/Popover.css.ts, packages/libs/react-ui/src/components/Popover/Popover.tsx, packages/libs/react-ui/src/styles/global.css.ts, packages/libs/react-ui/src/styles/utils.css.ts
updated the select component with the new styling updates. These include new size variants, font variants and consistent states like the other form elements. Internally the component uses the new Field component to abstract the formfield logic and simplify the select component.
- startIcon has been renamed to startVisual to be consistent with other rebranded components.
=> Feat(react UI)/new select component

.changeset/dry-trees-begin.md, packages/apps/graph/cwd-extra-migrations/2.3.0.0.6_replace_reconcile_view.sql, packages/apps/graph/package.json, packages/apps/graph/prisma/schema.prisma, packages/apps/graph/src/services/token-service.ts
In Marmalade, non fungible token balances can be decimal. Due to the view having these fields as integer. To correct this, I am adding a migration to drop the view and recreate it with a decimal column type
---
- https://app.asana.com/0/0/1207100487482658
=> Adjust reconcile view amount fields to decimals

packages/tools/kadena-cli/src/account/commands/accountFund.ts, packages/tools/kadena-cli/src/account/utils/fundHelpers.ts, packages/tools/kadena-cli/src/devnet/utils/network.ts
This PR addresses couple of issues
- Use `health-check` end point to check the dev/local server status https://app.asana.com/0/1205969628270714/1207158683269813/f
- In node version `v20.12.1` specifically the account fund command gets hang even after command execution is done 
https://app.asana.com/0/1205969628270714/1206951762878097/f
=> fix: account fund healthcheck

.changeset/breezy-oranges-pump.md, packages/libs/hd-wallet/src/chainweaver/compatibility/kadenaSign.ts, packages/libs/hd-wallet/src/chainweaver/compatibility/kadenaSignFromRootKey.ts, packages/libs/hd-wallet/src/chainweaver/tests/chainweaver.test.ts, packages/libs/hd-wallet/src/chainweaver/vendor/kadena-crypto.d.cts
* Chainweaver sign expects base64 decoded hash as a "message".
=> bugfix(hd-wallet): chainweaver sign did not use the right hash

packages/tools/kadena-cli/README.md, packages/tools/kadena-cli/src/config/commands/configInit.ts, packages/tools/kadena-cli/src/wallets/commands/walletAdd.ts
account alias option is an optional field because it's required only when create account is passed as true
So, incase when `--quiet` flag is used with `--create-account=true` but `account-alias` is **not** passed. it still create the wallet but doesn't create a account alias fails with error 
---
- https://app.asana.com/0/0/1207158682603351
=> fix: add account alias prompt for init + wallet add command

packages/tools/kadena-cli/src/prompts/tx.ts
https://github.com/kadena-community/kadena.js/pull/2020 - another PR to add alias for keys on add-from-wallet subcommand
---
- https://app.asana.com/0/0/1207158682603332
=> fix: tx add command prefix alias + index for keys and account

packages/tools/kadena-cli/src/networks/commands/networkManage.ts, packages/tools/kadena-cli/src/prompts/network.ts
https://app.asana.com/0/0/1207147099820716/1207150008413583/f
Based on the comment from @Ghislain89, I also think this makes sense since we're merging it anyway with the existing network config values but prefilling the values make it more explicit to the user.
=> fix: network update command prefill values from existing config

packages/tools/kadena-cli/src/prompts/account.ts, packages/tools/kadena-cli/src/prompts/wallets.ts, packages/tools/kadena-cli/src/wallets/tests/walletDelete.test.ts
Currently for wallet and account add commands if alias and wallet already exists on the same name we thrown an error at the end. It might be improved when we validate whether file exists or not at the time of user input. 
---
- https://app.asana.com/0/0/1207265443085992
=> fix: validate alias and wallet name exists on input prompt

packages/apps/docs/src/components/SearchDialog/styles.css.ts, packages/libs/react-ui/src/components/Modal/Modal.css.ts
i guess with solid background-color and backdrop filter seems doesn't work. so, i just making it to fix for docs based on the background base default `#222121` version to rgba. Maybe we can revisit fixing it better. 
it's breaking the docs for now. so creating a PR as short term fix
=> fix: react-ui dialog opacity

packages/e2e/e2e-graph/playwright.config.ts
This PR bumps the timeout for the graph server slightly to give graph a bit more time to start up in CI
=> Fix: Increase timeout for starting the graph server

.changeset/shiny-crews-sleep.md, packages/libs/react-ui/src/components/Divider/Divider.css.ts, packages/libs/react-ui/src/components/Divider/Divider.stories.tsx, packages/libs/react-ui/src/components/Divider/Divider.tsx
In this PR I've updated the divider to support the new colors and have the options to choose which one to use. 
Different colors are being used when using the new variant prop.
=> feat: add variant options with new colors

packages/apps/dev-wallet/package.json, packages/apps/dev-wallet/vite.config.ts, pnpm-lock.yaml
Themes didn't work from react-ui in the dev mode built with Vite. Turned out that there is an issue with libraries built with Vanilla Extract in development mode with Vite https://github.com/vanilla-extract-css/vanilla-extract/discussions/1051
=> fix: vanilla extract issue with vite in dev mode

.changeset/funny-cherries-drive.md, packages/apps/graph/src/graph/mappers/transaction-mapper.ts, packages/apps/graph/src/graph/objects/transaction.ts, packages/apps/graph/src/graph/subscription/transaction.ts, packages/apps/graph/src/services/chainweb-node/mempool.ts
- Fixed issue in mapper which was causing an error on yielding the mempool data
- Found a way around the transaction being both in the database and in the mempool: we now check for the `blockHash` before looking for a mempool status
---
- https://app.asana.com/0/0/1207399826642810
=> Fixed issue with transaction subscription

.changeset/brown-toys-divide.md, packages/tools/kadena-cli/src/account/commands/accountList.ts, packages/tools/kadena-cli/src/account/tests/accountList.test.ts
---
- https://app.asana.com/0/0/1207275180683040
=> fix(kadena-cli): Improved account list display formatting in account list command

.changeset/polite-suns-dress.md, packages/tools/kadena-cli/src/account/commands/accountFund.ts, packages/tools/kadena-cli/src/account/tests/accountFund.test.ts
- Add warning log message when user selects "no" for deploying the faucet.
- Improve clarity of unit test descriptions.
---
- https://app.asana.com/0/0/1207343169763167
=> fix(kadena-cli): add warning message for not deploying faucet + update test case descriptions

.changeset/five-pans-reply.md, packages/tools/kadena-cli/src/account/commands/accountList.ts, packages/tools/kadena-cli/src/keys/utils/keysDisplay.ts, packages/tools/kadena-cli/src/networks/tests/networkList.test.ts, packages/tools/kadena-cli/src/networks/utils/networkDisplay.ts, packages/tools/kadena-cli/src/wallets/commands/walletList.ts
---
- https://app.asana.com/0/0/1207343169763162
=> fix(kadena-cli): add empty log message for networks + empty state level to warning

.changeset/thick-trees-dance.md, packages/tools/kadena-cli/src/account/accountAddOptions.ts, packages/tools/kadena-cli/src/account/accountOptions.ts, packages/tools/kadena-cli/src/account/commands/accountAdd.ts, packages/tools/kadena-cli/src/account/commands/accountAddFromKey.ts, packages/tools/kadena-cli/src/account/tests/accountAdd.test.ts, packages/tools/kadena-cli/src/account/tests/accountDelete.test.ts, packages/tools/kadena-cli/src/account/tests/accountDetails.test.ts, packages/tools/kadena-cli/src/account/tests/accountFund.test.ts, packages/tools/kadena-cli/src/account/tests/accountList.test.ts, packages/tools/kadena-cli/src/prompts/account.ts
- Renamed `--type` option to `--from` in the `account add` command.
- Updated `--type=manual` to `--from=key` for specifying account addition via key file or manual entry.
- Improved descriptions in account from selection prompts for better clarity on available options.
---
- https://app.asana.com/0/0/1207307903477051
=> feat(add-account): rename account type to from option and manual to key value

packages/apps/marmalade-marketplace/turbo.json
This PR adds missing turbo config to the marmalade marketplace
=> FIX: add Turbo config to Marmalade Marketplace

packages/apps/tools/src/pages/faucet/existing/index.tsx, packages/apps/tools/src/pages/faucet/new/index.tsx, packages/apps/tools/src/pages/transactions/cross-chain-transfer-finisher/index.tsx, packages/apps/tools/src/pages/transactions/transfer/index.tsx
Related Issue/Asana ticket: https://app.asana.com/0/1205607256237316/1207446193153933/f
Short description: the Trans component does not provide a wrapper around and the notification displays the content as column for all the children, so in order to make it one element we need to wrap ir
=> chore: fixing Trans component that does not wrap

.changeset/calm-numbers-grin.md, packages/libs/react-ui/src/components/Form/Checkbox/Checkbox.css.ts, packages/libs/react-ui/src/components/Form/Checkbox/Checkbox.tsx, packages/libs/react-ui/src/components/Form/Checkbox/CheckboxGroup.stories.tsx, packages/libs/react-ui/src/components/Form/Checkbox/CheckboxGroup.tsx
In this PR I've added the Checkbox group component with the story similar to the radioGroup component.
=> feat: add checkboxgroup component

packages/libs/client-utils/src/integration-tests/marmalade-conventional-auction.int.test.ts, packages/libs/client-utils/src/integration-tests/marmalade-dutch-auction.int.test.ts, packages/libs/client-utils/src/integration-tests/utils.int.test.ts, packages/libs/client-utils/src/marmalade/create-token.ts
Adding back guard to `marmalade-v2.ledger.CREATE-TOKEN` to adopt the Point Release 1.1.0 update
=> chore: client-utils marmalade.js point release update

.github/CODEOWNERS
Adding Marmalade team as codeowners to marmalade marketplace app and client-utils
=> chore: add marmalade team as codeowners

.changeset/lovely-trees-flow.md, packages/libs/react-ui/src/components/TextLink/TextLink.stories.tsx, packages/libs/react-ui/src/components/TextLink/TextLink.tsx
Ticket: https://app.asana.com/0/1206752931509995/1207525414079731
The icon should be optional, this was the intended behaviour by design but implemented incorrect.
This PR will fix that, you can show the icon if you provide the withIcon prop.
=> fix: make the icon optional for the textlink component

.changeset/cool-dolls-add.md, packages/libs/react-ui/src/components/Layout/Grid/Grid.css.ts
The grid styles were being applied to a layer but all the other styles were being applied via the atoms function. This caused a mismatch and certain styles weren't applied. 
As you don't have any use overriding the styles of a layout component I removed the layer from the layout components.
=> fix: grid components were not behaving correct due to layers

.changeset/small-cows-shout.md, packages/apps/graph/src/services/network.ts
**In this PR I implemented logic to deal with total difficulty calculations when having multiple blocks for the same height and chain. At this point, these blocks are the latest ones and can at max have confirmation depth 3, so we cannot determine if they are canonical or orphans. For that reason, the implemented behavior is to average the difficulty of the two blocks in the same chain. What was verified also is that in most cases these 2 blocks have the same difficulty anyways.**
projects)
---
- …
=> Difficulty calculations - with orphan blocks

packages/apps/graph/generated-schema.graphql, packages/apps/graph/src/devnet/deployment/marmalade/config/namespaces.ts, packages/apps/graph/src/devnet/deployment/marmalade/namespace.ts, packages/apps/graph/src/graph/query/completed-block-heights.ts, packages/apps/graph/src/graph/query/events.ts
=> Aditional documentation

.changeset/early-apes-give.md, packages/apps/explorer/src/components/routing/useRouter.tsx, packages/apps/explorer/src/pages/[networkId]/account/[accountName].tsx, packages/apps/explorer/src/pages/index.tsx
there was an issue on account page. when you clicked the tabs the networkid would be removed from the url
=> fix(explorer): fix the tablinks in account

.github/actions/merge-publish-reports/action.yaml, .github/workflows/ci.yml, .github/workflows/report-cleanup.yaml, .gitignore, packages/e2e/e2e-base/playwright.config.ts, packages/e2e/e2e-docs/playwright.config.ts, packages/e2e/e2e-graph/playwright.config.ts, packages/e2e/e2e-proof-of-us/playwright.config.ts, packages/e2e/e2e-tools/playwright.config.ts
Related Issue/Asana ticket: https://app.asana.com/0/1206316065856327/1207502644848065/f
Prior to this PR, running end-to-end tests in CI would result in three separate HTML reports that would be added as artifacts to the run. Inspecting them meant downloading them individually and opening up the index.html.  This was considered tedious and slow.
This PR aims to resolve these barriers by essentially doing two things:
1. Add post processing, merging these three reports in to 1 report.
2. Publishing the merged HTML report to Github pages to make viewing it as easy as clicking the link.
Upon completion, the report link is added to the github summary 
In case a testcase fails or is considered flaky, devs can directly open up the trace file from the report without having …
=> FEAT: Enable blob reporter and merging reports

packages/apps/docs/src/docs/reference/chainweb/chainweb-data-models.md, packages/apps/docs/src/docs/reference/chainweb/chainweb-encoding.md
https://kadena-io.github.io/chainweb-openapi/#tag/cut_model
This PR converts those sections to standard Markdown to be included in the docs site.
projects)
=> [docs] Chainweb API - Move data models and binary encoding into main docs

.changeset/giant-gifts-fold.md, packages/libs/kode-ui/src/patterns/Card/CardContentBlock.tsx, packages/libs/kode-ui/src/patterns/Card/CardFixedContainer.tsx, packages/libs/kode-ui/src/patterns/Card/CardPattern.css.ts, packages/libs/kode-ui/src/patterns/Card/CardPattern.stories.tsx
- Updated the CardFixedContainer to not have padding on the bottom when it is not the last child so that the right spacing is provided when used in conjunction with an external CardFooterGroup
- Updated the `Heading` fontSize to be reduced in blocks that follow the leading block
- Added optional `className` props to the `CardFixedContainer`, `CardContentBlock`, and `CardFooterGroup` to allow for customization
- Made the `children` prop of `CardContentBlock` optional to allow for cases where providing content via other props is sufficient
=> Updated Card Pattern

packages/libs/client-utils/src/marmalade/README.md
Wrote the documentation of marmalade client-utils to showcase how to use all the different functions
=> chore: docs for marmalade client utils

packages/libs/kode-icons/src/product/SpireKeyKdacolorLogoGreen.tsx
=> Fix logo height

.changeset/quiet-berries-appear.md, packages/libs/client/etc/client.api.md, packages/libs/client/src/signing/eckoWallet/eckoCommon.ts, packages/libs/client/src/signing/eckoWallet/eckoTypes.ts, packages/libs/client/src/signing/eckoWallet/quicksignWithEckoWallet.ts, packages/libs/client/src/signing/eckoWallet/signWithEckoWallet.ts, packages/libs/client/src/signing/eckoWallet/tests/eckoCommon.test.ts, packages/libs/client/src/signing/index.ts
Adds a wrapper around the `kda_checkStatus` function from Ecko Wallet, which returns the currently connected account.
Closes #1613
=> Add checkStatus to Ecko signing functions

packages/apps/docs/src/docs/reference/pact/pact-repl-cli.md
I wasn't able to get the `--unsigned` option or the `add-sig`, `combine-sig` commands to work.
It isn't completely clear to me whether Pact server should be a standalone topic, live with the CLI reference, or be part of a different Local testing topic.
projects)
=> Update CLI reference section

.syncpackrc.js, packages/libs/snap/package.json, pnpm-lock.yaml
Add `dev` to pinned internal packages types. This fixes an issue where using an internal package in `devDependencies` could complain about `workspace:*` not being "in sync".
=> fix(syncpack): add dev to internal pinned workspace dependencies

.changeset/wicked-crews-burn.md, packages/libs/kode-ui/src/components/Typography/Text/Text.css.ts, packages/libs/kode-ui/src/components/Typography/Text/Text.stories.tsx, packages/libs/kode-ui/src/components/Typography/Text/Text.tsx
=> text component extended with text size inherit

packages/apps/dev-wallet/src/Components/AccountBalanceDistribution/components/ChainBalance.tsx, packages/apps/dev-wallet/src/Components/AccountBalanceDistribution/components/style.css.ts, packages/apps/dev-wallet/src/Components/FundOnTestnet/FundOnTestnet.tsx, packages/apps/dev-wallet/src/modules/db/db.service.tsx, packages/apps/dev-wallet/src/modules/transaction/transaction.repository.ts, packages/apps/dev-wallet/src/pages/signature-builder/signature-builder.tsx, packages/apps/dev-wallet/src/pages/signature-builder/style.css.ts, packages/apps/dev-wallet/src/pages/transfer-v2/Steps/style.css.ts
=> fix(dw): Fund btn + networkId

packages/apps/docs/src/docs/learn/accounts-keys.md
Title
Fix Grammar in Documentation: Update 'Kadena has also set up **gas stations** cover' -> 'Kadena has also set up **gas stations** to cover'
Related Issue/Asana Ticket
N/A
Short Description
This pull request corrects minor grammar in the documentation, changing 'of one public' to 'of one or more public.'
Test Scenarios
Visual inspection of the documentation to confirm grammar changes.
=> Minor Grammar Correction In Docs (4)

packages/apps/docs/src/docs/learn/accounts-keys.md
Title
Fix Grammar in Documentation: Update 'Of one public' to 'of one or more public'
Related Issue/Asana Ticket
N/A
Short Description
This pull request corrects minor grammar in the documentation, changing 'of one public' to 'of one or more public.'
Test Scenarios
Visual inspection of the documentation to confirm grammar changes.
=> Minor Grammar Correction In Docs (1).

packages/apps/dev-wallet/src/App/routes.tsx, packages/apps/dev-wallet/src/config.ts, packages/apps/dev-wallet/src/modules/account/account.repository.ts, packages/apps/dev-wallet/src/modules/db/migration/migrateFrom42to43.ts, packages/apps/dev-wallet/src/modules/db/migration/migration.ts, packages/apps/dev-wallet/src/modules/security/fallback.service.ts, packages/apps/dev-wallet/src/modules/security/security.service.ts, packages/apps/dev-wallet/src/modules/transaction/transaction.repository.ts, packages/apps/dev-wallet/src/modules/wallet/wallet.provider.tsx, packages/apps/dev-wallet/src/pages/settings/export-data/export-data.tsx, packages/apps/dev-wallet/src/pages/settings/settings.tsx, packages/apps/dev-wallet/src/pages/transaction/Transaction.tsx, packages/apps/dev-wallet/src/service-worker/encryption.ts, packages/apps/dev-wallet/src/service-worker/service-worker.ts, packages/apps/dev-wallet/src/service-worker/types.ts, packages/apps/dev-wallet/src/utils/session.ts
=> fix(dw): transfer page crash + csv export

.github/workflows/ci.yml
Dockerfile should be built with buildx for easier tagging and pushing
This is consistent with chainweb-node etc builds
=> Replace compose build with Dockerfile buildx

packages/apps/rwa-demo/src/app/(app)/page.tsx, packages/apps/rwa-demo/src/components/DistributionForm/DistributionForm.tsx, packages/apps/rwa-demo/src/components/InvestorBalance/InvestorBalance.tsx, packages/apps/rwa-demo/src/components/NoComplianceMessage/NoComplianceMessage.tsx, packages/apps/rwa-demo/src/components/SetComplianceForm/SetComplianceForm.tsx, packages/apps/rwa-demo/src/components/TransactionsProvider/TransactionsProvider.tsx, packages/apps/rwa-demo/src/hooks/getAgents.ts, packages/apps/rwa-demo/src/hooks/getInvestors.ts, packages/apps/rwa-demo/src/utils/store/index.ts
---
- https://app.asana.com/0/0/1209032514767395
=> fix(rwa): fix small bugs

packages/apps/tools/src/scripts/graphCron/index.ts
- use totalCutHeight from Graph by adding up all heights. 
- Add lastBlockHeight to message. 
- Adds types
---
- https://app.asana.com/0/0/1209191585829839
=> graph cron: use totalCutHeight from Graph by adding up all heights

packages/apps/dev-wallet/src/pages/transaction/components/TxPipeLine.tsx, packages/apps/dev-wallet/src/pages/transaction/components/TxTile.tsx, packages/apps/dev-wallet/src/pages/transfer/Steps/TransferForm.tsx
=> fix(dw): add share btn next to preflight and describe it

packages/apps/dev-wallet/src/pages/signature-builder/signature-builder.tsx, packages/apps/dev-wallet/src/pages/transaction/components/ExpandedTransaction.tsx
=> fix(dw): share tx

.changeset/config.json
=> fix: changeset config

packages/apps/dev-wallet/src/Components/Guard/KeySelector.tsx, packages/apps/dev-wallet/src/Components/Guard/keyset.tsx, packages/apps/dev-wallet/src/modules/wallet/wallet.hook.tsx, packages/apps/dev-wallet/src/pages/account/account.tsx, packages/apps/dev-wallet/src/pages/transaction/components/Signer.tsx, packages/apps/dev-wallet/src/pages/transfer/Steps/TransferForm.tsx
=> feat(dw): show alias for keys

packages/libs/client-examples/src/example-contract/call-contract-function.ts, packages/libs/client-examples/src/example-contract/deploy-contract.ts, packages/libs/client-examples/src/example-contract/util/requestToSign.ts
=> feat(client-example): deploy contract example using @kadena/client

.changeset/moody-poems-rescue.md, packages/tools/kadena-cli/src/commands/tx/txOptions.ts
Fixes: https://github.com/kadena-community/kadena.js/issues/2625
projects)
=> [kadena-cli] Fix warning when passing -u in tx sign

packages/apps/dev-wallet/src/pages/networks/Components/NetworkForm.tsx
if I dont type in the fields, but copy the text.
the form submit button will not be enabled when it needs to
=> fix(wallet):  the network form dirty state

.changeset/grumpy-taxis-grab.md, packages/apps/graph/generated-schema.graphql, packages/apps/graph/issue_events.md, packages/apps/graph/src/graph/subscription/events.ts
When opening subscriptions for qualifiedEventNames or requestKeys, we're looking
every second for a new record. When we find one, we return it to the consumer.
We poll every second, which could lead to the depletion of connections to the
database
Maybe some queries take more than a second, which leads to a buildup of queries
that are not being processed.
1. We can increase the polling interval to 5 seconds, which would reduce the
number of queries to the database.
2. If a query takes more than 5 seconds, the next polling will be ignored. The
maximum timeout of a query is already set at 15 seconds. So we miss a max of
2 polls
3. For every event we do a separate query. It would be better to create a single
polling mechanism that'll check for all events that have open subscription
The query …
=> fix(graph): optimize event polling interval and correct lastEventId query

packages/apps/dev-wallet/src/Components/BackupMnemonic/BackupMnemonic.tsx
=> fix(dw): confirm mnemonic

packages/apps/dev-wallet/src/Components/BackupMnemonic/BackupMnemonic.tsx
=> fix(dw): mnemonic

.changeset/calm-bats-joke.md, .changeset/clever-sheep-play.md, packages/e2e/e2e-graph/tests/transaction.test.ts, packages/libs/client-utils/README.md, packages/libs/client-utils/etc/client-utils-core.api.md, packages/libs/client-utils/src/core/estimate-gas.ts, packages/libs/client-utils/src/core/estimateGasPrice/estimateGasPrice.ts, packages/libs/client-utils/src/core/estimateGasPrice/index.ts, packages/libs/client-utils/src/core/estimateGasPrice/tests/estimateGasPrice.test.ts, packages/libs/client-utils/src/core/estimateGasPrice/utils.ts, packages/libs/client-utils/src/core/index.ts, packages/libs/client-utils/src/core/test/cross-chain-client.test.ts, packages/libs/client-utils/src/core/test/preflight-client.test.ts, packages/libs/client-utils/src/core/test/submit-client.test.ts, packages/libs/client-utils/src/faucet/test/fund-existing-account-on-testnet.test.ts, packages/libs/client-utils/src/faucet/test/fund-new-account-on-testnet.test.ts, packages/libs/client-utils/src/integration-tests/estimate-gas-price.int.test.ts, packages/libs/client-utils/vitest.config.ts, packages/libs/client/src/composePactCommand/composePactCommand.ts, packages/libs/client/src/createTransactionBuilder/tests/createTransactionBuilder.test.ts, packages/libs/client/src/signing/keypair/tests/signWithKeypair.test.ts, packages/libs/wallet-sdk/src/sdk/tests/crossChainFinishCreate.test.ts
**client**:
* Changed default TTL to 900 (15 min)
**cleint-utils**:
* `estimateGasPrice`:  estimate gas price on a chain
```TS
const currentGasPriceEstimation: number = await estimateGasPrice({ chainId: "0" });
```
* `getBlocksGasInformation`: returns useful information about gas 
```TS
const gasInformation :IBlockGasInformation[] = await getBlocksGasInformation({ chainId: "0" });
type IBlockGasInformation = Array<{
blockHeight: number;
totalGasConsumed: number; // sum of all gas consumed in the block transactions extracted from gas field of tx result
totalGasLimit: number; // sum of all gas limits in the block transactions extracted from gasLimit field of tx command
totalGasPaid: number; // sum of all gasPrice * gasLimit in the block transactions extracted from meta field of tx command …
```
=> feat(client): add gas estimation + change default TTL to 15 min

.changeset/metal-laws-peel.md, packages/libs/wallet-adapter-chainweaver-legacy/.prettierignore, packages/libs/wallet-adapter-chainweaver/.prettierignore, packages/libs/wallet-adapter-core/.prettierignore, packages/libs/wallet-adapter-core/src/utils/constants.ts, packages/libs/wallet-adapter-core/vitest.config.ts, packages/libs/wallet-adapter-ecko/.prettierignore, packages/libs/wallet-adapter-ecko/src/constants.ts, packages/libs/wallet-adapter-magic/.prettierignore, packages/libs/wallet-adapter-metamask-snap/.prettierignore, packages/libs/wallet-adapter-metamask-snap/package.json, packages/libs/wallet-adapter-react/.prettierignore, packages/libs/wallet-adapter-react/src/index.ts, packages/libs/wallet-adapter-react/vitest.config.ts, packages/libs/wallet-adapter-walletconnect/.prettierignore, packages/libs/wallet-adapter-zelcore/.prettierignore, packages/libs/wallet-sdk/src/sdk/tests/getGasLimitEstimate.test.ts
Run `pnpm run format` on each package and add `.prettierignore` files to ignore files that shouldn't be formatted.
=> fix(wallet-adapter): format wallet adapter packages
